<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Whm;

use Itxshakil\CpanelWhm\Api\WhmGroup;
use Itxshakil\CpanelWhm\Enums\HttpMethod;
use Itxshakil\CpanelWhm\Exceptions\WhmException;
use Itxshakil\CpanelWhm\WhmResponse;

/**
 * WHM API 1: Account Restoration (16 functions).
 *
 * Every method returns the checked WhmResponse; a failure throws a WhmException.
 */
final class AccountRestoration extends WhmGroup
{
    /**
     * Return backup modules list.
     *
     * This function lists backup modules and their descriptions.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-queue-reporting/transfers-restore_modules_summary
     */
    public function restoreModulesSummary(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restore_modules_summary', [], $extra);
    }

    /**
     * Start restoration.
     *
     * This function activates the restore queue. This triggers a process that restores all queued
     * accounts.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-queue-management/backup-restore_queue_activate
     */
    public function restoreQueueActivate(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restore_queue_activate', [], $extra, HttpMethod::Post);
    }

    /**
     * Restore user account from backup.
     *
     * This function restores a user's cPanel account from a backup file.
     *
     * @param  string  $restorePoint  The date of the backup to use, in `YYYY-MM-DD` format.
     * @param  string  $user  The cPanel account's username.
     * @param  string|null  $destid  The destination's identification string.
     * @param  bool|int|null  $giveIp  Whether to assign the account a dedicated IP address.
     * @param  bool|int|null  $mailConfig  Whether to restore the account's email configuration.
     * @param  bool|int|null  $mysql  Whether to restore the account's MySQL databases.
     * @param  bool|int|null  $subdomains  Whether to restore the account's subdomains.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-account/backup-restore_queue_add_task
     */
    public function restoreQueueAddTask(
        string $restorePoint,
        string $user,
        ?string $destid = null,
        bool|int|null $giveIp = null,
        bool|int|null $mailConfig = null,
        bool|int|null $mysql = null,
        bool|int|null $subdomains = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restore_queue_add_task', [
            'restore_point' => $restorePoint,
            'user' => $user,
            'destid' => $destid,
            'give_ip' => $giveIp,
            'mail_config' => $mailConfig,
            'mysql' => $mysql,
            'subdomains' => $subdomains,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Remove all completed restoration tasks.
     *
     * This function removes successfully completed tasks from the restoration queue.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-queue-management/backup-restore_queue_clear_all_completed_tasks
     */
    public function restoreQueueClearAllCompletedTasks(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restore_queue_clear_all_completed_tasks', [], $extra, HttpMethod::Post);
    }

    /**
     * Remove all failed restoration tasks.
     *
     * This function removes any failed tasks from the restoration queue.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-queue-management/backup-restore_queue_clear_all_failed_tasks
     */
    public function restoreQueueClearAllFailedTasks(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restore_queue_clear_all_failed_tasks', [], $extra, HttpMethod::Post);
    }

    /**
     * Remove all pending restoration tasks.
     *
     * This function removes any pending tasks from the restoration queue.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-queue-management/backup-restore_queue_clear_all_pending_tasks
     */
    public function restoreQueueClearAllPendingTasks(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restore_queue_clear_all_pending_tasks', [], $extra, HttpMethod::Post);
    }

    /**
     * Remove all restoration tasks.
     *
     * This function removes all tasks from the restoration queue.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-queue-management/backup-restore_queue_clear_all_tasks
     */
    public function restoreQueueClearAllTasks(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restore_queue_clear_all_tasks', [], $extra, HttpMethod::Post);
    }

    /**
     * Remove completed restoration task.
     *
     * This function removes a single completed task from the restoration queue.
     *
     * @param  int  $startTime  When the restoration queue started the restoration.
     * @param  string  $user  The cPanel account's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-queue-management/backup-restore_queue_clear_completed_task
     */
    public function restoreQueueClearCompletedTask(
        int $startTime,
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restore_queue_clear_completed_task', [
            'start_time' => $startTime,
            'user' => $user,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Remove pending restoration task.
     *
     * This function removes a single pending task from the restoration queue.
     *
     * @param  string  $user  The cPanel account's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-queue-management/backup-restore_queue_clear_pending_task
     */
    public function restoreQueueClearPendingTask(
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restore_queue_clear_pending_task', [
            'user' => $user,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Validate restoration queue is active.
     *
     * This function checks whether the system's restoration queue is actively processing tasks.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-queue-reporting/backup-restore_queue_is_active
     */
    public function restoreQueueIsActive(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restore_queue_is_active', [], $extra);
    }

    /**
     * Return active restoration tasks list.
     *
     * This function lists the tasks that the restoration queue is actively processing.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-queue-reporting/backup-restore_queue_list_active
     */
    public function restoreQueueListActive(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restore_queue_list_active', [], $extra);
    }

    /**
     * Return completed restoration tasks list.
     *
     * This function lists the restoration queue's completed tasks.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-queue-reporting/backup-restore_queue_list_completed
     */
    public function restoreQueueListCompleted(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restore_queue_list_completed', [], $extra);
    }

    /**
     * Return pending restoration tasks list.
     *
     * This function lists the tasks that the restoration queue has not yet processed.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-queue-reporting/backup-restore_queue_list_pending
     */
    public function restoreQueueListPending(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restore_queue_list_pending', [], $extra);
    }

    /**
     * Return restoration tasks list.
     *
     * This function lists the tasks in the restoration queue.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-queue-reporting/backup-restore_queue_state
     */
    public function restoreQueueState(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restore_queue_state', [], $extra);
    }

    /**
     * Restore account backup.
     *
     * This function restores an account backup. You can use this function to restore daily, weekly, or
     * monthly backups.
     *
     * @param  string  $type  The type of backup to restore.
     * @param  string  $user  The account's username.
     * @param  bool|int|null  $all  Whether to create the account before restoration.
     * @param  bool|int|null  $ip  Whether to assign a dedicated IP address to the restored account.
     * @param  bool|int|null  $mail  Whether to restore account-level filters (vfilters) and forwarders (valiases).
     * @param  bool|int|null  $mysql  Whether to restore the account's MySQL databases.
     * @param  bool|int|null  $subs  Whether to restore the account's subdomains.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-account/backup-restoreaccount
     */
    public function restoreaccount(
        string $type,
        string $user,
        bool|int|null $all = null,
        bool|int|null $ip = null,
        bool|int|null $mail = null,
        bool|int|null $mysql = null,
        bool|int|null $subs = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('restoreaccount', [
            'type' => $type,
            'user' => $user,
            'all' => $all,
            'ip' => $ip,
            'mail' => $mail,
            'mysql' => $mysql,
            'subs' => $subs,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Validate username during restoration.
     *
     * This function checks for username conflicts during account restoration. If the function detects a
     * username conflict, it outputs an error message in the `reason` return.
     *
     * @param  string  $user  The cPanel account that you wish to transfer to the server.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/restore-account/nameconflict-verify_new_username_for_restore
     */
    public function verifyNewUsernameForRestore(
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('verify_new_username_for_restore', [
            'user' => $user,
        ], $extra);
    }
}
