<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Whm;

use Itxshakil\CpanelWhm\Api\WhmGroup;
use Itxshakil\CpanelWhm\Enums\HttpMethod;
use Itxshakil\CpanelWhm\Exceptions\WhmException;
use Itxshakil\CpanelWhm\WhmResponse;
use SensitiveParameter;

/**
 * WHM API 1: Authentication (38 functions).
 *
 * Every method returns the checked WhmResponse; a failure throws a WhmException.
 */
final class Authentication extends WhmGroup
{
    /**
     * Return cPanel account access hash.
     *
     * This function regenerates or retrieves a user's access hash. For more information about access
     * hashes, read our Remote Access Key documentation.
     *
     * @param  bool|int  $generate  Whether to regenerate the access hash.
     * @param  string  $user  The user's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @deprecated cPanel has deprecated this function.
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ssh-keys-and-connections/resellers-accesshash
     */
    public function accesshash(
        bool|int $generate,
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('accesshash', [
            'generate' => $generate,
            'user' => $user,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Create WHM API token.
     *
     * This function creates an API token. You can use API tokens instead of a password or access hash key
     * to execute WHM API 1 functions over HTTPS. For more information about API tokens, read our Manage
     * API Tokens in WHM documentation.
     *
     * @param  string  $tokenName  The API token's name.
     * @param  string|null  $acl  The privileges to assign to the token.
     * @param  int|null  $expiresAt  The API token's expiration time.
     * @param  string|null  $whitelistIp  One or more optional remote IP or CIDR IP ranges this token may be used from.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/api-token-management/tokens-api_token_create
     */
    public function apiTokenCreate(
        string $tokenName,
        ?string $acl = null,
        ?int $expiresAt = null,
        ?string $whitelistIp = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('api_token_create', [
            'token_name' => $tokenName,
            'acl' => $acl,
            'expires_at' => $expiresAt,
            'whitelist_ip' => $whitelistIp,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Look up API token details.
     *
     * This function looks up an API token’s details based on the token itself.
     *
     * @param  string  $token  The API token.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/api-token-management/tokens-api_token_get_details
     */
    public function apiTokenGetDetails(
        #[SensitiveParameter] string $token,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('api_token_get_details', [
            'token' => $token,
        ], $extra);
    }

    /**
     * Return WHM API tokens.
     *
     * This function lists a WHM account's API tokens.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/api-token-management/tokens-api_token_list
     */
    public function apiTokenList(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('api_token_list', [], $extra);
    }

    /**
     * Disable WHM API token.
     *
     * This function revokes an API token from the WHM account.
     *
     * @param  string  $tokenName  The API token's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/api-token-management/tokens-api_token_revoke
     */
    public function apiTokenRevoke(
        string $tokenName,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('api_token_revoke', [
            'token_name' => $tokenName,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update WHM API token's settings.
     *
     * This function updates an API token's settings.
     *
     * @param  string  $tokenName  The API token's name.
     * @param  string|null  $acl  The new privileges to assign to the token.
     * @param  int|null  $expiresAt  The API token's expiration time.
     * @param  string|null  $newName  The API token's new name.
     * @param  string|null  $whitelistIp  The new remote IP or CIDR IP ranges to assign to this token.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/api-token-management/tokens-api_token_update
     */
    public function apiTokenUpdate(
        string $tokenName,
        ?string $acl = null,
        ?int $expiresAt = null,
        ?string $newName = null,
        ?string $whitelistIp = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('api_token_update', [
            'token_name' => $tokenName,
            'acl' => $acl,
            'expires_at' => $expiresAt,
            'new_name' => $newName,
            'whitelist_ip' => $whitelistIp,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Enable SSH key for server.
     *
     * This function authorizes a public SSH key to access the server. When you call this function, it adds
     * the key to the `/root/.ssh/authorized_keys` file.
     *
     * @param  bool|int  $authorize  Whether to authorize the public SSH key to access the server.
     * @param  string  $file  The public SSH key file's name.
     * @param  string  $text  The text of the SSH public key file.
     * @param  string|null  $options  A comma-separated list of options to include with the public SSH key.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ssh-keys-and-connections/ssh-authorizesshkey
     */
    public function authorizesshkey(
        bool|int $authorize,
        string $file,
        string $text,
        ?string $options = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('authorizesshkey', [
            'authorize' => $authorize,
            'file' => $file,
            'text' => $text,
            'options' => $options,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Validate SSH connection to another server.
     *
     * This function tests an SSH connection to another server.
     *
     * @param  string  $host  The remote server's hostname.
     * @param  int|null  $port  The remote server's port number.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ssh-keys-and-connections/ssh-check_remote_ssh_connection
     */
    public function checkRemoteSshConnection(
        string $host,
        ?int $port = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('check_remote_ssh_connection', [
            'host' => $host,
            'port' => $port,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Migrate OpenSSH key to PuTTY format.
     *
     * This function converts an OpenSSH private key to a PuTTY key.
     *
     * @param  string  $file  The private key file's name.
     * @param  bool|int|null  $keepFile  Whether to keep the OpenSSH file on the server after conversion.
     * @param  string|null  $passphrase  The private key file's passphrase.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ssh-keys-and-connections/ssh-convertopensshtoputty
     */
    public function convertopensshtoputty(
        string $file,
        bool|int|null $keepFile = null,
        #[SensitiveParameter] ?string $passphrase = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('convertopensshtoputty', [
            'file' => $file,
            'keep_file' => $keepFile,
            'passphrase' => $passphrase,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Delete SSH key.
     *
     * This function function deletes an SSH key from the server.
     *
     * @param  string  $file  The SSH key file's name.
     * @param  bool|int|null  $leaveAuthorized  Whether to authorize the SSH key to access the server.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ssh-keys-and-connections/ssh-deletesshkey
     */
    public function deletesshkey(
        string $file,
        bool|int|null $leaveAuthorized = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('deletesshkey', [
            'file' => $file,
            'leave_authorized' => $leaveAuthorized,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Disable identity provider.
     *
     * This function disables a external authentication identity provider for a specified service.
     *
     * @param  string  $providerId  A valid identity provider's identification key.
     * @param  string  $serviceName  The cPanel & WHM service's name:
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/external-authentication/authentication-disable_authentication_provider
     */
    public function disableAuthenticationProvider(
        string $providerId,
        string $serviceName,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('disable_authentication_provider', [
            'provider_id' => $providerId,
            'service_name' => $serviceName,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Disable identity provider modules that fail to load.
     *
     * This function disables any enabled identity provider modules that fail to load.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/external-authentication/authentication-disable_failing_authentication_providers
     */
    public function disableFailingAuthenticationProviders(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('disable_failing_authentication_providers', [], $extra, HttpMethod::Post);
    }

    /**
     * Enable identity provider.
     *
     * This function enables an external authentication identity provider for a specified service.
     *
     * @param  string  $providerId  A valid identity provider's identification key.
     * @param  string  $serviceName  The cPanel & WHM service's name:
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/external-authentication/authentication-enable_authentication_provider
     */
    public function enableAuthenticationProvider(
        string $providerId,
        string $serviceName,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('enable_authentication_provider', [
            'provider_id' => $providerId,
            'service_name' => $serviceName,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Create SSH key pair.
     *
     * This function generates an SSH key pair.
     *
     * @param  bool|int|null  $abortOnExistingKey  Whether to abort the function if the user already has a key with the same name.
     * @param  string|null  $algorithm  The key's encryption algorithm.
     * @param  int|null  $bits  The key's bits:
     * @param  string|null  $comment  A comment.
     * @param  string|null  $name  The key's filename.
     * @param  string|null  $passphrase  The key's secure passphrase.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ssh-keys-and-connections/ssh-generatesshkeypair
     */
    public function generatesshkeypair(
        bool|int|null $abortOnExistingKey = null,
        ?string $algorithm = null,
        ?int $bits = null,
        ?string $comment = null,
        ?string $name = null,
        #[SensitiveParameter] ?string $passphrase = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('generatesshkeypair', [
            'abort_on_existing_key' => $abortOnExistingKey,
            'algorithm' => $algorithm,
            'bits' => $bits,
            'comment' => $comment,
            'name' => $name,
            'passphrase' => $passphrase,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return available identity providers.
     *
     * This function lists available external authentication identity providers for all services.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/external-authentication/authentication-get_available_authentication_providers
     */
    public function getAvailableAuthenticationProviders(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_available_authentication_providers', [], $extra);
    }

    /**
     * Return cPanel Store or cPanel Market login URL.
     *
     * This function retrieves the login URL for the cPanel Store or a cPanel Market provider.
     *
     * @param  string  $provider  The cPanel Store or cPanel Market provider's name.
     * @param  string  $urlAfterLogin  The location to which the cPanel Store or cPanel Market provider redirects the user's browser after they log in.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/login-url/market-get_login_url
     */
    public function getLoginUrl(
        string $provider,
        string $urlAfterLogin,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_login_url', [
            'provider' => $provider,
            'url_after_login' => $urlAfterLogin,
        ], $extra);
    }

    /**
     * Return identity provider client configuration.
     *
     * This function retrieves the configuration details for the client of an external authentication
     * identity provider.
     *
     * @param  string  $providerId  The identity provider's key.
     * @param  string  $serviceName  The cPanel & WHM service's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/external-authentication/authentication-get_provider_client_configurations
     */
    public function getProviderClientConfigurations(
        string $providerId,
        string $serviceName,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_provider_client_configurations', [
            'provider_id' => $providerId,
            'service_name' => $serviceName,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return identity provider configuration fields.
     *
     * This function retrieves the configuration fields for a external authentication identity provider.
     *
     * @param  string  $providerId  The identity provider's key.
     * @param  string  $serviceName  The cPanel & WHM service's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/external-authentication/authentication-get_provider_configuration_fields
     */
    public function getProviderConfigurationFields(
        string $providerId,
        string $serviceName,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_provider_configuration_fields', [
            'provider_id' => $providerId,
            'service_name' => $serviceName,
        ], $extra);
    }

    /**
     * Return identity provider login interface appearance.
     *
     * This function retrieves the display configuration for the login button of an external authentication
     * identity provider.
     *
     * @param  string  $providerId  The identity provider's key.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/external-authentication/authentication-get_provider_display_configurations
     */
    public function getProviderDisplayConfigurations(
        string $providerId,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_provider_display_configurations', [
            'provider_id' => $providerId,
        ], $extra);
    }

    /**
     * Return accounts linked to identity providers.
     *
     * This function lists all accounts that link to available external authentication identity providers.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/external-authentication/accounts-get_users_authn_linked_accounts
     */
    public function getUsersAuthnLinkedAccounts(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_users_authn_linked_accounts', [], $extra);
    }

    /**
     * Import SSH key.
     *
     * This function imports an SSH key.
     *
     * @param  string  $key  The key's contents.
     * @param  string  $name  The key's name.
     * @param  bool|int|null  $extractPrivate  Whether to extract and save only the private key.
     * @param  bool|int|null  $extractPublic  Whether to extract and save only the public key.
     * @param  string|null  $passphrase  The key's passphrase.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ssh-keys-and-connections/ssh-importsshkey
     */
    public function importsshkey(
        #[SensitiveParameter] string $key,
        string $name,
        bool|int|null $extractPrivate = null,
        bool|int|null $extractPublic = null,
        #[SensitiveParameter] ?string $passphrase = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('importsshkey', [
            'key' => $key,
            'name' => $name,
            'extract_private' => $extractPrivate,
            'extract_public' => $extractPublic,
            'passphrase' => $passphrase,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Add identity provider to cPanel account.
     *
     * This function adds an External Authentication authorization link to an account.
     *
     * @param  string  $preferredUsername  The preferred username of the account on the identity provider.
     * @param  string  $providerId  The name of the identity provider.
     * @param  string  $subjectUniqueIdentifier  The unique identifier for the user at the identity provider.
     * @param  string  $username  The account's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/external-authentication/accounts-link_user_authn_provider
     */
    public function linkUserAuthnProvider(
        string $preferredUsername,
        string $providerId,
        string $subjectUniqueIdentifier,
        string $username,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('link_user_authn_provider', [
            'preferred_username' => $preferredUsername,
            'provider_id' => $providerId,
            'subject_unique_identifier' => $subjectUniqueIdentifier,
            'username' => $username,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return SSH keys list.
     *
     * This function lists the server's SSH keys.
     *
     * @param  string|null  $files  A filename, to limit the results to keys that have that filename.
     * @param  bool|int|null  $private  Whether to display only private keys.
     * @param  bool|int|null  $privateTexts  Whether to include private key text.
     * @param  bool|int|null  $public  Whether to display only public keys.
     * @param  bool|int|null  $publicTexts  Whether to include public key text.
     * @param  bool|int|null  $syncAuthorized  Whether to synchronize the keys that can access the server.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ssh-keys-and-connections/ssh-listsshkeys
     */
    public function listsshkeys(
        ?string $files = null,
        bool|int|null $private = null,
        bool|int|null $privateTexts = null,
        bool|int|null $public = null,
        bool|int|null $publicTexts = null,
        bool|int|null $syncAuthorized = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('listsshkeys', [
            'files' => $files,
            'private' => $private,
            'private_texts' => $privateTexts,
            'public' => $public,
            'public_texts' => $publicTexts,
            'sync_authorized' => $syncAuthorized,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update identity provider client configuration.
     *
     * This function sets the values of configuration fields for an external authentication identity
     * provider.
     *
     * @param  string  $configurations  The configuration values to set for the identity provider.
     * @param  string  $providerId  The identity provider's key.
     * @param  string  $serviceName  The cPanel & WHM service's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/external-authentication/authentication-set_provider_client_configurations
     */
    public function setProviderClientConfigurations(
        string $configurations,
        string $providerId,
        string $serviceName,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('set_provider_client_configurations', [
            'configurations' => $configurations,
            'provider_id' => $providerId,
            'service_name' => $serviceName,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update identity provider login interface appearance.
     *
     * This function sets the display configuration for the login button of an external authentication
     * identity provider.
     *
     * @param  mixed  $configurations  The display configuration in JSON-encoded key-value format.
     * @param  string  $providerId  The identity provider's key.
     * @param  string  $serviceName  The cPanel & WHM service's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/external-authentication/authentication-set_provider_display_configurations
     */
    public function setProviderDisplayConfigurations(
        mixed $configurations,
        string $providerId,
        string $serviceName,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('set_provider_display_configurations', [
            'configurations' => $configurations,
            'provider_id' => $providerId,
            'service_name' => $serviceName,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Disable 2FA.
     *
     * This function disables the Two-Factor Authentication (2FA) security policy on the server.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/two-factor-authentication/twofactorauth-twofactorauth_disable_policy
     */
    public function twofactorauthDisablePolicy(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('twofactorauth_disable_policy', [], $extra, HttpMethod::Post);
    }

    /**
     * Enable 2FA.
     *
     * This function enables the Two-Factor Authentication (2FA) security policy on the server.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/two-factor-authentication/twofactorauth-twofactorauth_enable_policy
     */
    public function twofactorauthEnablePolicy(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('twofactorauth_enable_policy', [], $extra, HttpMethod::Post);
    }

    /**
     * Create a one-time authentication secret and code.
     *
     * This function generates a random secret and a one-time password authentication (OTP auth) URL for
     * the user. Use the secret that this function returns and a valid verification token with WHM API 1's
     * `twofactorauth_set_tfa_config` function to configure Two-Factor Authentication (2FA) on an account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/two-factor-authentication/twofactorauth-twofactorauth_generate_tfa_config
     */
    public function twofactorauthGenerateTfaConfig(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('twofactorauth_generate_tfa_config', [], $extra, HttpMethod::Post);
    }

    /**
     * Return configured issuer for current user.
     *
     * This function returns the currently configured issuer. The issuer appears within the authentication
     * app.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/two-factor-authentication/twofactorauth-twofactorauth_get_issuer
     */
    public function twofactorauthGetIssuer(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('twofactorauth_get_issuer', [], $extra);
    }

    /**
     * Return cPanel account 2FA data.
     *
     * This function returns the Two-Factor Authentication (2FA) configuration for a cPanel account, its
     * email accounts, and its team user accounts.
     *
     * @param  string  $user  The username for the account.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/two-factor-authentication/twofactorauth-twofactorauth_get_tfa_config_for_user
     */
    public function twofactorauthGetTfaConfigForUser(
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('twofactorauth_get_tfa_config_for_user', [
            'user' => $user,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return cPanel accounts with 2FA enabled.
     *
     * This function returns a list of user-controlled accounts and whether the accounts have Two-Factor
     * Authentication (2FA) enabled.
     *
     * @param  string|null  $user  The username for a specified account.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/two-factor-authentication/twofactorauth-twofactorauth_get_user_configs
     */
    public function twofactorauthGetUserConfigs(
        ?string $user = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('twofactorauth_get_user_configs', [
            'user' => $user,
        ], $extra);
    }

    /**
     * Return 2FA policy status.
     *
     * This function displays the Two-Factor Authentication (2FA) policy status on the server.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/two-factor-authentication/twofactorauth-twofactorauth_policy_status
     */
    public function twofactorauthPolicyStatus(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('twofactorauth_policy_status', [], $extra);
    }

    /**
     * Remove 2FA settings.
     *
     * This function removes the Two-Factor Authentication (2FA) settings for one or more specified user
     * accounts.
     *
     * @param  string  $user  The account's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/two-factor-authentication/twofactorauth-twofactorauth_remove_user_config
     */
    public function twofactorauthRemoveUserConfig(
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('twofactorauth_remove_user_config', [
            'user' => $user,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update 2FA issuer value.
     *
     * This function sets the `issuer` value that the system uses to generate the `secret` and `otpurls`
     * values for Two-Factor Authentication on your accounts.
     *
     * @param  string  $issuer  The issuer's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/two-factor-authentication/twofactorauth-twofactorauth_set_issuer
     */
    public function twofactorauthSetIssuer(
        string $issuer,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('twofactorauth_set_issuer', [
            'issuer' => $issuer,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update 2FA authentication secret and code.
     *
     * This function sets the secret and the authentication code for Two-Factor Authentication (2FA) for
     * the `root` or reseller account. You can generate a random secret and an OTP authentication URL with
     * WHM API 1's `twofactorauth_generate_tfa_configorauth_generate_tfa_config` function.
     *
     * @param  string  $secret  A generated code for use with 2FA in Base32 format.
     * @param  string  $tfaToken  The time-based one-time password (TOTP) that the authentication app provides.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/two-factor-authentication/twofactorauth-twofactorauth_set_tfa_config
     */
    public function twofactorauthSetTfaConfig(
        #[SensitiveParameter] string $secret,
        #[SensitiveParameter] string $tfaToken,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('twofactorauth_set_tfa_config', [
            'secret' => $secret,
            'tfa_token' => $tfaToken,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Unregister cPanel account from authentication provider.
     *
     * This function unlinks a cPanel account from an external authentication identity provider.
     *
     * @param  string  $providerId  The system's internal key for the identity provider.
     * @param  string  $subjectUniqueIdentifier  The unique identifier for the user at the identity provider.
     * @param  string  $username  The account's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/authentication-providers/accounts-unlink_user_authn_provider
     */
    public function unlinkUserAuthnProvider(
        string $providerId,
        string $subjectUniqueIdentifier,
        string $username,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('unlink_user_authn_provider', [
            'provider_id' => $providerId,
            'subject_unique_identifier' => $subjectUniqueIdentifier,
            'username' => $username,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Validate login token and return access token.
     *
     * This function validates a login token with the cPanel Store or a cPanel Market provider, and then
     * returns access tokens.
     *
     * @param  string  $loginToken  The login token to validate.
     * @param  string  $provider  The cPanel Store or cPanel Market provider's name.
     * @param  string  $urlAfterLogin  The location to which the cPanel Store or cPanel Market provider redirects the user's browser after they log in.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/market-integration/market-validate_login_token
     */
    public function validateLoginToken(
        #[SensitiveParameter] string $loginToken,
        string $provider,
        string $urlAfterLogin,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('validate_login_token', [
            'login_token' => $loginToken,
            'provider' => $provider,
            'url_after_login' => $urlAfterLogin,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Create API token for Dashboard.
     *
     * This function creates a WHM API token for WebPros Dashboard.
     *
     * @param  string  $acl  The privileges to assign to the token.
     * @param  string  $tokenName  The API token's name.
     * @param  int|null  $expiresAt  The API token's expiration time, in Unix Epoch format.
     * @param  string|null  $whitelistIp  One or more optional remote IP address or CIDR IP address ranges that can use this token.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/api-token-management/wpdashboard-wp_dashboard_create_api_token
     */
    public function wpDashboardCreateApiToken(
        string $acl,
        string $tokenName,
        ?int $expiresAt = null,
        ?string $whitelistIp = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('wp_dashboard_create_api_token', [
            'acl' => $acl,
            'token_name' => $tokenName,
            'expires_at' => $expiresAt,
            'whitelist_ip' => $whitelistIp,
        ], $extra, HttpMethod::Post);
    }
}
