<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Whm;

use Itxshakil\CpanelWhm\Api\WhmGroup;
use Itxshakil\CpanelWhm\Enums\HttpMethod;
use Itxshakil\CpanelWhm\Exceptions\WhmException;
use Itxshakil\CpanelWhm\WhmResponse;

/**
 * WHM API 1: Backups (27 functions).
 *
 * Every method returns the checked WhmResponse; a failure throws a WhmException.
 */
final class Backups extends WhmGroup
{
    /**
     * Return backup configuration file data.
     *
     * This function retrieves your backup destination configuration file data.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-settings/backup-backup_config_get
     */
    public function backupConfigGet(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_config_get', [], $extra);
    }

    /**
     * Update the system's backup configuration.
     *
     * This function configures a server's backup system. The system saves these settings in the
     * `/var/cpanel/backups/config` file.
     *
     * @param  bool|int|null  $backupDailyEnable  Whether to enable daily backups.
     * @param  int|null  $backupDailyRetention  The number of daily backups to retain.
     * @param  int|null  $backupMonthlyDates  Which days of the month to run backups.
     * @param  bool|int|null  $backupMonthlyEnable  Whether to enable monthly backups.
     * @param  int|null  $backupMonthlyRetention  The number of monthly backups to retain.
     * @param  int|null  $backupWeeklyDay  Which day of the week to run weekly backups.
     * @param  bool|int|null  $backupWeeklyEnable  Whether to enable weekly backups.
     * @param  int|null  $backupWeeklyRetention  The number of weekly backups to retain.
     * @param  bool|int|null  $backupaccts  Whether to back up cPanel user accounts.
     * @param  bool|int|null  $backupbwdata  Whether to back up bandwidth tracking data.
     * @param  string|null  $backupdays  Which days of the week to run daily backups.
     * @param  string|null  $backupdir  The primary backup directory.
     * @param  bool|int|null  $backupenable  Whether to enable backups.
     * @param  bool|int|null  $backupfiles  Whether to back up system files.
     * @param  bool|int|null  $backuplogs  Whether to back up the error logs.
     * @param  bool|int|null  $backupmount  Whether to mount a backup partition.
     * @param  bool|int|null  $backupsuspendedaccts  Whether to back up suspended accounts.
     * @param  string|null  $backuptype  The type of backup to create.
     * @param  bool|int|null  $checkMinFreeSpace  Whether to ensure that the destination server possesses the minimum free disk space available.
     * @param  bool|int|null  $disableMetadata  Whether the backup system will create metadata when a backup runs.
     * @param  int|null  $errorthreshhold  The number of times that the system will try to use the additional backup destination.
     * @param  bool|int|null  $forcePruneDaily  Whether to strictly enforce the value of the `backup_daily_retention` parameter.
     * @param  bool|int|null  $forcePruneMonthly  Whether to strictly enforce the value of the `backup_monthly_retention` parameter.
     * @param  bool|int|null  $forcePruneWeekly  Whether to strictly enforce the value of the `backup_weekly_retention` parameter.
     * @param  string|null  $gziprsyncopts  The `gzip` environment variables.
     * @param  bool|int|null  $keeplocal  Whether to delete backups from the local directory.
     * @param  bool|int|null  $linkdest  Whether to check the `rsync` function for hardlink support.
     * @param  bool|int|null  $localzonesonly  Whether to use a local zone file from the `/var/named/domain.tld` file or the `dnsadmin` daemon, where `domain.tld` represents the target domain.
     * @param  int|null  $maximumRestoreTimeout  How long a restoration will attempt to run, in seconds.
     * @param  int|null  $maximumTimeout  How long a backup will attempt to run, in seconds.
     * @param  int|null  $minFreeSpace  The minimum amount of free disk to check for on the destination server.
     * @param  string|null  $minFreeSpaceUnit  The units of measurement of disk space for the `min_free_space` return.
     * @param  string|null  $mysqlbackup  The backup method to use for MySQL databases.
     * @param  bool|int|null  $postbackup  Whether to run the `/usr/local/cpanel/scripts/postcpbackup` script after the backup finishes.
     * @param  bool|int|null  $prebackup  Whether to run the `/usr/local/cpanel/scripts/precpbackup` script before the system processes backups.
     * @param  bool|int|null  $psqlbackup  Whether to back up PostgreSQL databases.
     * @param  string|null  $remoteRestoreStagingDir  The directory that temporarily stores a remote backup's data during a backup restoration.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-settings/backup-backup_config_set
     */
    public function backupConfigSet(
        bool|int|null $backupDailyEnable = null,
        ?int $backupDailyRetention = null,
        ?int $backupMonthlyDates = null,
        bool|int|null $backupMonthlyEnable = null,
        ?int $backupMonthlyRetention = null,
        ?int $backupWeeklyDay = null,
        bool|int|null $backupWeeklyEnable = null,
        ?int $backupWeeklyRetention = null,
        bool|int|null $backupaccts = null,
        bool|int|null $backupbwdata = null,
        ?string $backupdays = null,
        ?string $backupdir = null,
        bool|int|null $backupenable = null,
        bool|int|null $backupfiles = null,
        bool|int|null $backuplogs = null,
        bool|int|null $backupmount = null,
        bool|int|null $backupsuspendedaccts = null,
        ?string $backuptype = null,
        bool|int|null $checkMinFreeSpace = null,
        bool|int|null $disableMetadata = null,
        ?int $errorthreshhold = null,
        bool|int|null $forcePruneDaily = null,
        bool|int|null $forcePruneMonthly = null,
        bool|int|null $forcePruneWeekly = null,
        ?string $gziprsyncopts = null,
        bool|int|null $keeplocal = null,
        bool|int|null $linkdest = null,
        bool|int|null $localzonesonly = null,
        ?int $maximumRestoreTimeout = null,
        ?int $maximumTimeout = null,
        ?int $minFreeSpace = null,
        ?string $minFreeSpaceUnit = null,
        ?string $mysqlbackup = null,
        bool|int|null $postbackup = null,
        bool|int|null $prebackup = null,
        bool|int|null $psqlbackup = null,
        ?string $remoteRestoreStagingDir = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_config_set', [
            'backup_daily_enable' => $backupDailyEnable,
            'backup_daily_retention' => $backupDailyRetention,
            'backup_monthly_dates' => $backupMonthlyDates,
            'backup_monthly_enable' => $backupMonthlyEnable,
            'backup_monthly_retention' => $backupMonthlyRetention,
            'backup_weekly_day' => $backupWeeklyDay,
            'backup_weekly_enable' => $backupWeeklyEnable,
            'backup_weekly_retention' => $backupWeeklyRetention,
            'backupaccts' => $backupaccts,
            'backupbwdata' => $backupbwdata,
            'backupdays' => $backupdays,
            'backupdir' => $backupdir,
            'backupenable' => $backupenable,
            'backupfiles' => $backupfiles,
            'backuplogs' => $backuplogs,
            'backupmount' => $backupmount,
            'backupsuspendedaccts' => $backupsuspendedaccts,
            'backuptype' => $backuptype,
            'check_min_free_space' => $checkMinFreeSpace,
            'disable_metadata' => $disableMetadata,
            'errorthreshhold' => $errorthreshhold,
            'force_prune_daily' => $forcePruneDaily,
            'force_prune_monthly' => $forcePruneMonthly,
            'force_prune_weekly' => $forcePruneWeekly,
            'gziprsyncopts' => $gziprsyncopts,
            'keeplocal' => $keeplocal,
            'linkdest' => $linkdest,
            'localzonesonly' => $localzonesonly,
            'maximum_restore_timeout' => $maximumRestoreTimeout,
            'maximum_timeout' => $maximumTimeout,
            'min_free_space' => $minFreeSpace,
            'min_free_space_unit' => $minFreeSpaceUnit,
            'mysqlbackup' => $mysqlbackup,
            'postbackup' => $postbackup,
            'prebackup' => $prebackup,
            'psqlbackup' => $psqlbackup,
            'remote_restore_staging_dir' => $remoteRestoreStagingDir,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return dates where backup files exist.
     *
     * This function lists the dates where backup file exists, whether stored locally or stored on remote
     * backup destinations when local backups are disabled.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-settings/backup-backup_date_list
     */
    public function backupDateList(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_date_list', [], $extra, HttpMethod::Post);
    }

    /**
     * Add a backup destination.
     *
     * This function adds a backup destination.
     *
     * @param  string  $applicationKey  The application key's name.
     * @param  string  $applicationKeyId  The application key ID that authenticates the Backblaze B2 account.
     * @param  string  $authtype  The authorization type.
     * @param  string  $awsAccessKeyId  The Amazon S3 Access Key ID.
     * @param  string  $bucket  The Amazon S3 bucket.
     * @param  string  $bucketId  The bucket's ID string.
     * @param  string  $bucketName  The bucket's name.
     * @param  string  $clientId  The Google Drive client ID.
     * @param  string  $clientSecret  The Google Drive client secret.
     * @param  bool|int  $disabled  Whether to disable the backup destination.
     * @param  string  $host  The remote server's hostname.
     * @param  string  $name  The backup destination's name.
     * @param  string  $password  The remote server account's password or secret access key.
     * @param  string  $script  The absolute file path to the user-supplied transport solution script.
     * @param  string  $type  The type of backup destination.
     * @param  string  $username  The remote server account's username.
     * @param  string|null  $folder  The path to the backups directory on the remote server.
     * @param  bool|int|null  $mount  Whether the path is mounted.
     * @param  bool|int|null  $noMountFail  Whether to fail the backup attempt if the mount fails.
     * @param  bool|int|null  $onlyUsedForLogs  Whether to use this transport only for logs.
     * @param  bool|int|null  $passive  Whether to use passive FTP.
     * @param  string|null  $passphrase  The private key file's passphrase, if the `authtype` parameter is the `key` value.
     * @param  string|null  $path  The path to the backups directory on the remote server.
     * @param  int|null  $port  The TCP port to use.
     * @param  string|null  $privatekey  The file path to the private key file, if the `authtype` parameter is the `key` value.
     * @param  bool|int|null  $ssl  Whether to use SSL.
     * @param  int|null  $timeout  The session timeout, measured in seconds.
     * @param  bool|int|null  $uploadSystemBackup  Whether to upload system backups.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-destination/backup-backup_destination_add
     */
    public function backupDestinationAdd(
        string $applicationKey,
        string $applicationKeyId,
        string $authtype,
        string $awsAccessKeyId,
        string $bucket,
        string $bucketId,
        string $bucketName,
        string $clientId,
        string $clientSecret,
        bool|int $disabled,
        string $host,
        string $name,
        string $password,
        string $script,
        string $type,
        string $username,
        ?string $folder = null,
        bool|int|null $mount = null,
        bool|int|null $noMountFail = null,
        bool|int|null $onlyUsedForLogs = null,
        bool|int|null $passive = null,
        ?string $passphrase = null,
        ?string $path = null,
        ?int $port = null,
        ?string $privatekey = null,
        bool|int|null $ssl = null,
        ?int $timeout = null,
        bool|int|null $uploadSystemBackup = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_destination_add', [
            'application_key' => $applicationKey,
            'application_key_id' => $applicationKeyId,
            'authtype' => $authtype,
            'aws_access_key_id' => $awsAccessKeyId,
            'bucket' => $bucket,
            'bucket_id' => $bucketId,
            'bucket_name' => $bucketName,
            'client_id' => $clientId,
            'client_secret' => $clientSecret,
            'disabled' => $disabled,
            'host' => $host,
            'name' => $name,
            'password' => $password,
            'script' => $script,
            'type' => $type,
            'username' => $username,
            'folder' => $folder,
            'mount' => $mount,
            'no_mount_fail' => $noMountFail,
            'only_used_for_logs' => $onlyUsedForLogs,
            'passive' => $passive,
            'passphrase' => $passphrase,
            'path' => $path,
            'port' => $port,
            'privatekey' => $privatekey,
            'ssl' => $ssl,
            'timeout' => $timeout,
            'upload_system_backup' => $uploadSystemBackup,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Delete a backup destination.
     *
     * This function removes a backup destination from the backup configuration file.
     *
     * @param  string  $id  The destination's ID.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-destination/backup-backup_destination_delete
     */
    public function backupDestinationDelete(
        string $id,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_destination_delete', [
            'id' => $id,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return a backup destination's settings.
     *
     * Use this function to obtain a backup destination's settings.
     *
     * @param  string  $id  The backup destination's ID.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-destination/backup-backup_destination_get
     */
    public function backupDestinationGet(
        string $id,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_destination_get', [
            'id' => $id,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return a list of backup destinations.
     *
     * This function lists backup destinations.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-destination/backup-backup_destination_list
     */
    public function backupDestinationList(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_destination_list', [], $extra, HttpMethod::Post);
    }

    /**
     * Update backup destination settings.
     *
     * Use this function to edit a backup destination's settings.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-destination/backup-backup_destination_set
     */
    public function backupDestinationSet(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_destination_set', [], $extra, HttpMethod::Post);
    }

    /**
     * Validate a backup destination.
     *
     * This function validates a backup destination.
     *
     * @param  bool|int  $disableonfail  Whether to disable the backup destination if validation fails.
     * @param  string  $id  The destination's ID.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-destination/backup-backup_destination_validate
     */
    public function backupDestinationValidate(
        bool|int $disableonfail,
        string $id,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_destination_validate', [
            'disableonfail' => $disableonfail,
            'id' => $id,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return Google Drive client ID credentials.
     *
     * This function returns whether a Google Drive client ID credential file exists.
     *
     * @param  string  $clientId  The user's Google Drive client ID.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-destination/backup-backup_does_client_id_have_google_credentials
     */
    public function backupDoesClientIdHaveGoogleCredentials(
        string $clientId,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_does_client_id_have_google_credentials', [
            'client_id' => $clientId,
        ], $extra);
    }

    /**
     * Create Google Drive OAuth redirect URI.
     *
     * This function generates a Google Drive OAuth redirect URI.
     *
     * @param  string  $clientId  The Google Drive client ID.
     * @param  string  $clientSecret  The Google Drive client secret.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-destination/backup-backup_generate_google_oauth_uri
     */
    public function backupGenerateGoogleOauthUri(
        string $clientId,
        string $clientSecret,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_generate_google_oauth_uri', [
            'client_id' => $clientId,
            'client_secret' => $clientSecret,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return backup transport events' status.
     *
     * This function retrieves the status of any backup transport events on the account.
     *
     * @param  string|null  $state  That transport's current state.
     * @param  string|null  $transportId  The transport's identification (ID).
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-or-restore/backup-backup_get_transport_status
     */
    public function backupGetTransportStatus(
        ?string $state = null,
        ?string $transportId = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_get_transport_status', [
            'state' => $state,
            'transport_id' => $transportId,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return backup files sent through transport.
     *
     * This function lists backup files that the system sent through a specified additional backup
     * transport.
     *
     * @param  string|null  $transport  The transport ID.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-or-restore/backup-backup_list_transported
     */
    public function backupListTransported(
        ?string $transport = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_list_transported', [
            'transport' => $transport,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return backup files in the local disk.
     *
     * This function lists backup files for the server's accounts in the local disk.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-or-restore/backup-backup_set_list
     */
    public function backupSetList(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_set_list', [], $extra, HttpMethod::Post);
    }

    /**
     * Return backup files for the server's accounts.
     *
     * This function lists locally-stored and backup-destination stored backup files for the server's
     * accounts.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-or-restore/backup-backup_set_list_combined
     */
    public function backupSetListCombined(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_set_list_combined', [], $extra, HttpMethod::Post);
    }

    /**
     * Enable or disable backups.
     *
     * This function enables and disables the backup and legacy backups.
     *
     * @param  string  $backupversion  The type of backup.
     * @param  bool|int  $state  Whether to enable the backup type that the `backupversion` parameter specifies for all users.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-settings/backup-backup_skip_users_all
     */
    public function backupSkipUsersAll(
        string $backupversion,
        bool|int $state,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_skip_users_all', [
            'backupversion' => $backupversion,
            'state' => $state,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return backup configuration status.
     *
     * This function checks each user's backup configuration status while the `backup_skip_users_all`
     * function runs.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-settings/backup-backup_skip_users_all_status
     */
    public function backupSkipUsersAllStatus(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_skip_users_all_status', [], $extra, HttpMethod::Post);
    }

    /**
     * Return users with a backup file.
     *
     * This function lists users with a backup file, stored locally or on additional backup destinations,
     * on a specified date.
     *
     * @param  string  $restorePoint  The desired date.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-settings/backup-backup_user_list
     */
    public function backupUserList(
        string $restorePoint,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('backup_user_list', [
            'restore_point' => $restorePoint,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Migrate server to new backup system.
     *
     * This function converts and migrates a server from the Legacy Backup system to the Backup system.
     *
     * @param  bool|int|null  $noConvert  Whether to convert the server from the Legacy Backup system to the Backup system.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/legacy-migration/backup-convert_and_migrate_from_legacy_config
     */
    public function convertAndMigrateFromLegacyConfig(
        bool|int|null $noConvert = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('convert_and_migrate_from_legacy_config', [
            'no_convert' => $noConvert,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return start_background_pkgacct session log file.
     *
     * This function returns the contents of a `start_background_pkgacct` session's master log file.
     *
     * @param  string  $sessionId  The `start_background_pkgacct` session ID.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-or-restore/backup-fetch_pkgacct_master_log
     */
    public function fetchPkgacctMasterLog(
        string $sessionId,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('fetch_pkgacct_master_log', [
            'session_id' => $sessionId,
        ], $extra);
    }

    /**
     * Return start_background_pkgacct session state.
     *
     * This function returns the state of a `start_background_pkgacct` session.
     *
     * @param  string  $sessionId  The `start_background_pkgacct` session ID.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-or-restore/backup-get_pkgacct_session_state
     */
    public function getPkgacctSessionState(
        string $sessionId,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_pkgacct_session_state', [
            'session_id' => $sessionId,
        ], $extra);
    }

    /**
     * Return users and domains with backup metadata.
     *
     * This function lists all users and their domains that have backup metadata.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-or-restore/backup-get_users_and_domains_with_backup_metadata
     */
    public function getUsersAndDomainsWithBackupMetadata(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_users_and_domains_with_backup_metadata', [], $extra);
    }

    /**
     * Return users with backup metadata.
     *
     * This function lists users with backup metadata.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-or-restore/backup-get_users_with_backup_metadata
     */
    public function getUsersWithBackupMetadata(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_users_with_backup_metadata', [], $extra);
    }

    /**
     * Return cparchive files list.
     *
     * This function lists all available cparchive files.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-or-restore/backup-list_cparchive_files
     */
    public function listCparchiveFiles(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('list_cparchive_files', [], $extra);
    }

    /**
     * Back up an account using the pkgacct script.
     *
     * This function backs up an account with the pkgacct script.
     *
     * @param  string  $user  The cPanel account to back up.
     * @param  string|null  $compressionsetting  Whether to compress the data in .gzip format.
     * @param  bool|int|null  $incremental  Whether to update the destination file with any new content since the previous backup.
     * @param  bool|int|null  $lowPriority  Whether to run the background task with a reduced priority.
     * @param  string|null  $mysqlver  The minimum version of MySQL that the system requires to restore the backed up database files.
     * @param  bool|int|null  $serializedOutput  Whether to encode each line of the script's output in JSON format in order to allow the `live_tail_log.cgi` script to stream it.
     * @param  bool|int|null  $skipacctdb  Whether to exclude the account's databases from the cpmove archive.
     * @param  bool|int|null  $skipapitokens  Whether to exclude the account's API tokens from the archive.
     * @param  bool|int|null  $skipauthnlinks  Whether to exclude the account's external authentication credentials from the archive.
     * @param  bool|int|null  $skipbwdata  Whether to exclude the account's bandwidth data from the archive.
     * @param  bool|int|null  $skipdnssec  Whether to exclude the account's DNSSEC configuration from the archive.
     * @param  bool|int|null  $skipdnszones  Whether to exclude the account's DNS zone file information from the archive.
     * @param  bool|int|null  $skipftpusers  Whether to exclude the account's FTP user accounts from the archive.
     * @param  bool|int|null  $skiphomedir  Whether to skip the home directory's contents.
     * @param  bool|int|null  $skiplinkednodes  Whether to exclude the account's cPanel & WHM linked server nodes configuration from the archive.
     * @param  bool|int|null  $skiplogs  Whether to exclude the account's log files from the archive.
     * @param  bool|int|null  $skipresellerconfig  Whether to exclude the account's reseller privileges from the archive.
     * @param  bool|int|null  $skipshell  Whether to exclude the account's shell information and privileges from the archive.
     * @param  bool|int|null  $skipvhosttemplates  Whether to exclude the account's virtual host (vhost) templates from the archive.
     * @param  bool|int|null  $split  Whether to create the cpmove archive in chunks.
     * @param  string|null  $tarroot  The path to the directory in which you wish to store the cpmove archive.
     * @param  bool|int|null  $useBackups  Whether to use the account's last known successful backup as a template when the script creates the cpmove archive, if any exist.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-or-restore/backup-start_background_pkgacct
     */
    public function startBackgroundPkgacct(
        string $user,
        ?string $compressionsetting = null,
        bool|int|null $incremental = null,
        bool|int|null $lowPriority = null,
        ?string $mysqlver = null,
        bool|int|null $serializedOutput = null,
        bool|int|null $skipacctdb = null,
        bool|int|null $skipapitokens = null,
        bool|int|null $skipauthnlinks = null,
        bool|int|null $skipbwdata = null,
        bool|int|null $skipdnssec = null,
        bool|int|null $skipdnszones = null,
        bool|int|null $skipftpusers = null,
        bool|int|null $skiphomedir = null,
        bool|int|null $skiplinkednodes = null,
        bool|int|null $skiplogs = null,
        bool|int|null $skipresellerconfig = null,
        bool|int|null $skipshell = null,
        bool|int|null $skipvhosttemplates = null,
        bool|int|null $split = null,
        ?string $tarroot = null,
        bool|int|null $useBackups = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('start_background_pkgacct', [
            'user' => $user,
            'compressionsetting' => $compressionsetting,
            'incremental' => $incremental,
            'low_priority' => $lowPriority,
            'mysqlver' => $mysqlver,
            'serialized_output' => $serializedOutput,
            'skipacctdb' => $skipacctdb,
            'skipapitokens' => $skipapitokens,
            'skipauthnlinks' => $skipauthnlinks,
            'skipbwdata' => $skipbwdata,
            'skipdnssec' => $skipdnssec,
            'skipdnszones' => $skipdnszones,
            'skipftpusers' => $skipftpusers,
            'skiphomedir' => $skiphomedir,
            'skiplinkednodes' => $skiplinkednodes,
            'skiplogs' => $skiplogs,
            'skipresellerconfig' => $skipresellerconfig,
            'skipshell' => $skipshell,
            'skipvhosttemplates' => $skipvhosttemplates,
            'split' => $split,
            'tarroot' => $tarroot,
            'use_backups' => $useBackups,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Restore one cPanel account from a backup.
     *
     * This function performs a full restoration of a single cPanel account from a `cpmove` tarball.
     *
     * @param  string  $cpmovepath  A filepath that contains the account's `cpmove` tarball or the directory path that contains the extracted `cpmove` tarball.
     * @param  bool|int|null  $dedicatedIp  Whether to assign the account a dedicated IP address.
     * @param  bool|int|null  $deleteArchive  Whether to delete the `cpmove` tarball or extracted directory, given in the `cpmovepath` parameter, after the system completes the account restoration.
     * @param  string|null  $mailLocation  The server on which the account's email will reside after the system completes the transfer.
     * @param  bool|int|null  $overwrite  Whether to overwrite an existing account on the server, if one exists.
     * @param  bool|int|null  $restricted  Whether to perform a restricted restore for the account.
     * @param  string|null  $updateARecords  Whether to perform one of the following actions to the account's A records:
     * @param  string|null  $username  The username to give to the restored cPanel account.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-or-restore/transfers-start_local_cpmove_restore
     */
    public function startLocalCpmoveRestore(
        string $cpmovepath,
        bool|int|null $dedicatedIp = null,
        bool|int|null $deleteArchive = null,
        ?string $mailLocation = null,
        bool|int|null $overwrite = null,
        bool|int|null $restricted = null,
        ?string $updateARecords = null,
        ?string $username = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('start_local_cpmove_restore', [
            'cpmovepath' => $cpmovepath,
            'dedicated_ip' => $dedicatedIp,
            'delete_archive' => $deleteArchive,
            'mail_location' => $mailLocation,
            'overwrite' => $overwrite,
            'restricted' => $restricted,
            'update_a_records' => $updateARecords,
            'username' => $username,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Enable or disable legacy backups.
     *
     * This function enables or disables legacy backups for a user.
     *
     * @param  string  $user  The cPanel account's username.
     * @param  bool|int|null  $legacy  Whether the account should use the legacy backup system.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/backup-settings/backup-toggle_user_backup_state
     */
    public function toggleUserBackupState(
        string $user,
        bool|int|null $legacy = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('toggle_user_backup_state', [
            'user' => $user,
            'legacy' => $legacy,
        ], $extra, HttpMethod::Post);
    }
}
