<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Whm;

use Itxshakil\CpanelWhm\Api\WhmGroup;
use Itxshakil\CpanelWhm\Enums\HttpMethod;
use Itxshakil\CpanelWhm\Exceptions\WhmException;
use Itxshakil\CpanelWhm\WhmResponse;

/**
 * WHM API 1: Customizations (3 functions).
 *
 * Every method returns the checked WhmResponse; a failure throws a WhmException.
 */
final class Customizations extends WhmGroup
{
    /**
     * Delete customization data.
     *
     * This function deletes customization data.
     *
     * @param  string  $application  The application name for the customization.
     * @param  string  $theme  The theme name for the customization.
     * @param  string|null  $path  The JSONPath expression to reach to property you want to delete.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/customizations/customizations-delete_customizations
     */
    public function deleteCustomizations(
        string $application,
        string $theme,
        ?string $path = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('delete_customizations', [
            'application' => $application,
            'theme' => $theme,
            'path' => $path,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Retrieve customization data.
     *
     * This function retrieves customization data.
     *
     * @param  string  $application  The application name for the customization.
     * @param  string  $theme  The theme for the customization.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/customizations/customizations-retrieve_customizations
     */
    public function retrieveCustomizations(
        string $application,
        string $theme,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('retrieve_customizations', [
            'application' => $application,
            'theme' => $theme,
        ], $extra);
    }

    /**
     * Update customization data.
     *
     * This function supplies branding data for a specific application and theme.
     *
     * @param  string  $application  The application name for the customization.
     * @param  mixed  $data  The theme data to save.
     * @param  string  $theme  The theme name for the customization.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/customizations/customizations-update_customizations
     */
    public function updateCustomizations(
        string $application,
        mixed $data,
        string $theme,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('update_customizations', [
            'application' => $application,
            'data' => $data,
            'theme' => $theme,
        ], $extra, HttpMethod::Post);
    }
}
