<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Whm;

use Itxshakil\CpanelWhm\Api\WhmGroup;
use Itxshakil\CpanelWhm\Enums\HttpMethod;
use Itxshakil\CpanelWhm\Exceptions\WhmException;
use Itxshakil\CpanelWhm\WhmResponse;
use SensitiveParameter;

/**
 * WHM API 1: Databases (26 functions).
 *
 * Every method returns the checked WhmResponse; a failure throws a WhmException.
 */
final class Databases extends WhmGroup
{
    /**
     * Validate MySQL status before upgrade.
     *
     * This function checks your MySQL configuration file and table engine before an upgrade to MySQL 8.0.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/manage-mysql-server/mysql-background_mysql_upgrade_checker_run
     */
    public function backgroundMysqlUpgradeCheckerRun(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('background_mysql_upgrade_checker_run', [], $extra, HttpMethod::Post);
    }

    /**
     * Return MySQL or MariaDB upgrade status.
     *
     * This function retrieves the status of a background MySQL or MariaDB upgrade.
     *
     * @param  string  $upgradeId  The logfile's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/manage-mysql-server/mysql-background_mysql_upgrade_status
     */
    public function backgroundMysqlUpgradeStatus(
        string $upgradeId,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('background_mysql_upgrade_status', [
            'upgrade_id' => $upgradeId,
        ], $extra);
    }

    /**
     * Return MySQL version.
     *
     * This function retrieves the server's version of MySQL or MariaDB.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/manage-mysql-server/mysql-current_mysql_version
     */
    public function currentMysqlVersion(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('current_mysql_version', [], $extra);
    }

    /**
     * Return MySQL database optimizations.
     *
     * This function retrieves available database optimizations.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mysql-databases/db-get_database_optimizations
     */
    public function getDatabaseOptimizations(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_database_optimizations', [], $extra);
    }

    /**
     * Return available MySQL versions.
     *
     * This function lists all available versions of MySQL and MariaDB.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/manage-mysql-server/mysql-installable_mysql_versions
     */
    public function installableMysqlVersions(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('installable_mysql_versions', [], $extra);
    }

    /**
     * Return latest MySQL version.
     *
     * This function retrieves the latest available version of MySQL or MariaDB.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/manage-mysql-server/mysql-latest_available_mysql_version
     */
    public function latestAvailableMysqlVersion(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('latest_available_mysql_version', [], $extra);
    }

    /**
     * Return MySQL users.
     *
     * This function lists the server's database users.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mysql-databases/db-list_database_users
     */
    public function listDatabaseUsers(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('list_database_users', [], $extra);
    }

    /**
     * Return MySQL databases.
     *
     * This function lists the server's databases.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mysql-databases/db-list_databases
     */
    public function listDatabases(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('list_databases', [], $extra);
    }

    /**
     * Return MySQL databases and users for account.
     *
     * This function retrieves the MySQL database and user data for the specified account.
     *
     * @param  string  $user  The username for a specified account.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mysql-databases/db-list_mysql_databases_and_users
     */
    public function listMysqlDatabasesAndUsers(
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('list_mysql_databases_and_users', [
            'user' => $user,
        ], $extra);
    }

    /**
     * Create remote MySQL profile.
     *
     * This function creates a profile to access a remote MySQL server.
     *
     * @param  string  $mysqlHost  The MySQL server's IP address or hostname.
     * @param  string  $mysqlPass  The MySQL server's password.
     * @param  int  $mysqlPort  The MySQL server's port.
     * @param  string  $mysqlUser  The MySQL server's username.
     * @param  string  $name  The new profile's name.
     * @param  int|null  $cpcloud  Whether the remote database profile is a cPanel Cloud deployment.
     * @param  string|null  $setupVia  A description of the profile data.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/remote-mysql-databases/remotemysql-remote_mysql_create_profile
     */
    public function remoteMysqlCreateProfile(
        string $mysqlHost,
        #[SensitiveParameter] string $mysqlPass,
        int $mysqlPort,
        string $mysqlUser,
        string $name,
        ?int $cpcloud = null,
        ?string $setupVia = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('remote_mysql_create_profile', [
            'mysql_host' => $mysqlHost,
            'mysql_pass' => $mysqlPass,
            'mysql_port' => $mysqlPort,
            'mysql_user' => $mysqlUser,
            'name' => $name,
            'cpcloud' => $cpcloud,
            'setup_via' => $setupVia,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Create remote MySQL profile via SSH.
     *
     * This function uses SSH to create a profile to access a remote MySQL server.
     *
     * @param  string  $host  The MySQL server's IP address or hostname.
     * @param  string  $name  The new profile's name.
     * @param  int  $port  The SSH server's port.
     * @param  string  $user  The SSH username.
     * @param  int|null  $cpcloud  Whether the remote database profile is a cPanel Cloud deployment.
     * @param  string|null  $password  The SSH username's password.
     * @param  string|null  $rootEscalationMethod  The escalation method to use to authenticate the account.
     * @param  string|null  $rootPassword  The MySQL server's root user's password.
     * @param  string|null  $sshkeyName  The name of the SSH key.
     * @param  string|null  $sshkeyPassphrase  The SSH key's passphrase.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/remote-mysql-databases/remotemysql-remote_mysql_create_profile_via_ssh
     */
    public function remoteMysqlCreateProfileViaSsh(
        string $host,
        string $name,
        int $port,
        string $user,
        ?int $cpcloud = null,
        #[SensitiveParameter] ?string $password = null,
        ?string $rootEscalationMethod = null,
        #[SensitiveParameter] ?string $rootPassword = null,
        ?string $sshkeyName = null,
        #[SensitiveParameter] ?string $sshkeyPassphrase = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('remote_mysql_create_profile_via_ssh', [
            'host' => $host,
            'name' => $name,
            'port' => $port,
            'user' => $user,
            'cpcloud' => $cpcloud,
            'password' => $password,
            'root_escalation_method' => $rootEscalationMethod,
            'root_password' => $rootPassword,
            'sshkey_name' => $sshkeyName,
            'sshkey_passphrase' => $sshkeyPassphrase,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Delete remote MySQL profile.
     *
     * This function deletes a specified remote MySQL profile.
     *
     * @param  string  $name  The profile's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/remote-mysql-databases/remotemysql-remote_mysql_delete_profile
     */
    public function remoteMysqlDeleteProfile(
        string $name,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('remote_mysql_delete_profile', [
            'name' => $name,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Start remote MySQL profile activation.
     *
     * This function initiates the activation process for a remote MySQL profile.
     *
     * @param  string  $name  The profile's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/remote-mysql-databases/remotemysql-remote_mysql_initiate_profile_activation
     */
    public function remoteMysqlInitiateProfileActivation(
        string $name,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('remote_mysql_initiate_profile_activation', [
            'name' => $name,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return remote MySQL profile activation.
     *
     * This function reports the current status of the remote MySQL profile activation process. The
     * activation process contains several steps that take some time to complete, so so you may need to
     * call this function multiple times multiple times to monitor the progress.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/remote-mysql-databases/remotemysql-remote_mysql_monitor_profile_activation
     */
    public function remoteMysqlMonitorProfileActivation(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('remote_mysql_monitor_profile_activation', [], $extra);
    }

    /**
     * Return remote MySQL profile.
     *
     * This function displays the details of a specified remote MySQL profile.
     *
     * @param  string  $name  The MySQL profile's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/remote-mysql-databases/remotemysql-remote_mysql_read_profile
     */
    public function remoteMysqlReadProfile(
        string $name,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('remote_mysql_read_profile', [
            'name' => $name,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return remote MySQL profiles.
     *
     * This function displays the details of all remote MySQL profiles available in WHM.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/remote-mysql-databases/remotemysql-remote_mysql_read_profiles
     */
    public function remoteMysqlReadProfiles(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('remote_mysql_read_profiles', [], $extra, HttpMethod::Post);
    }

    /**
     * Update remote MySQL profile.
     *
     * This function updates one or more parameters for a remote MySQL profile.
     *
     * @param  string  $name  The profile's name.
     * @param  string|null  $mysqlHost  The MySQL server's IP address or hostname.
     * @param  string|null  $mysqlPass  The MySQL server's password.
     * @param  int|null  $mysqlPort  The MySQL server's port.
     * @param  string|null  $mysqlUser  The MySQL server's username.
     * @param  string|null  $setupVia  A description of the profile data.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/remote-mysql-databases/remotemysql-remote_mysql_update_profile
     */
    public function remoteMysqlUpdateProfile(
        string $name,
        ?string $mysqlHost = null,
        #[SensitiveParameter] ?string $mysqlPass = null,
        ?int $mysqlPort = null,
        ?string $mysqlUser = null,
        ?string $setupVia = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('remote_mysql_update_profile', [
            'name' => $name,
            'mysql_host' => $mysqlHost,
            'mysql_pass' => $mysqlPass,
            'mysql_port' => $mysqlPort,
            'mysql_user' => $mysqlUser,
            'setup_via' => $setupVia,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Validate remote MySQL profile connection.
     *
     * This function validates a specified remote MySQL profile's connection details.
     *
     * @param  string  $name  The profile's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/remote-mysql-databases/remotemysql-remote_mysql_validate_profile
     */
    public function remoteMysqlValidateProfile(
        string $name,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('remote_mysql_validate_profile', [
            'name' => $name,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update MySQL database name.
     *
     * This function changes a MySQL database's name. MySQL does not allow you to rename a database. When
     * cPanel & WHM "renames" a database, the system performs the following steps: 1. The system creates a
     * new database. 2. The system moves data from the old database to the new database. 3.
     *
     * @param  string  $newname  The database's new name.
     * @param  string  $oldname  The database's current name.
     * @param  string|null  $cpuser  The database's owner.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mysql-databases/db-rename_mysql_database
     */
    public function renameMysqlDatabase(
        string $newname,
        string $oldname,
        ?string $cpuser = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('rename_mysql_database', [
            'newname' => $newname,
            'oldname' => $oldname,
            'cpuser' => $cpuser,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update MySQL username.
     *
     * This function changes a MySQL database user's name.
     *
     * @param  string  $newname  The database user's new name.
     * @param  string  $oldname  The database user's current name.
     * @param  string|null  $cpuser  The database user's owner.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mysql-databases/db-rename_mysql_user
     */
    public function renameMysqlUser(
        string $newname,
        string $oldname,
        ?string $cpuser = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('rename_mysql_user', [
            'newname' => $newname,
            'oldname' => $oldname,
            'cpuser' => $cpuser,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update PostgreSQL database name.
     *
     * This function changes a PostgreSQL database's name.
     *
     * @param  string  $newname  The database's new name.
     * @param  string  $oldname  The database's current name.
     * @param  string|null  $cpuser  The database's owner.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/postgresql-databases/db-rename_postgresql_database
     */
    public function renamePostgresqlDatabase(
        string $newname,
        string $oldname,
        ?string $cpuser = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('rename_postgresql_database', [
            'newname' => $newname,
            'oldname' => $oldname,
            'cpuser' => $cpuser,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update PostgreSQL username.
     *
     * This function changes a PostgreSQL database user's name.
     *
     * @param  string  $newname  The database user's new name.
     * @param  string  $oldname  The database user's current name.
     * @param  string  $password  The database user's new password.
     * @param  string|null  $cpuser  The database user's owner.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/postgresql-databases/db-rename_postgresql_user
     */
    public function renamePostgresqlUser(
        string $newname,
        string $oldname,
        #[SensitiveParameter] string $password,
        ?string $cpuser = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('rename_postgresql_user', [
            'newname' => $newname,
            'oldname' => $oldname,
            'password' => $password,
            'cpuser' => $cpuser,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update MySQL root password.
     *
     * This function resets the root user's password on the local MySQL server.
     *
     * @param  string  $password  The new MySQL root user's password.
     * @param  bool|int|null  $updateConfig  Whether to update the configuration files.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/manage-mysql-server/localmysql-set_local_mysql_root_password
     */
    public function setLocalMysqlRootPassword(
        #[SensitiveParameter] string $password,
        bool|int|null $updateConfig = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('set_local_mysql_root_password', [
            'password' => $password,
            'update_config' => $updateConfig,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update MySQL user password.
     *
     * This function changes a MySQL database user's password.
     *
     * @param  string  $password  The database user's new password.
     * @param  string  $user  The database username.
     * @param  string|null  $cpuser  The cPanel user that controls the database user.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mysql-databases/db-set_mysql_password
     */
    public function setMysqlPassword(
        #[SensitiveParameter] string $password,
        string $user,
        ?string $cpuser = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('set_mysql_password', [
            'password' => $password,
            'user' => $user,
            'cpuser' => $cpuser,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update PostgreSQL user password.
     *
     * This function changes a PostgreSQL database user's password.
     *
     * @param  string  $password  The database user's new password.
     * @param  string  $user  The account's username.
     * @param  string|null  $cpuser  The database user's owner.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/postgresql-databases/db-set_postgresql_password
     */
    public function setPostgresqlPassword(
        #[SensitiveParameter] string $password,
        string $user,
        ?string $cpuser = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('set_postgresql_password', [
            'password' => $password,
            'user' => $user,
            'cpuser' => $cpuser,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Start background MySQL upgrade.
     *
     * This function upgrades MySQL or MariaDB in the background. This will reinstall MySQL or MariaDB if
     * the version given is the installed version.
     *
     * @param  float|int  $version  The desired MySQL or MariaDB version.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/manage-mysql-server/mysql-start_background_mysql_upgrade
     */
    public function startBackgroundMysqlUpgrade(
        float|int $version,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('start_background_mysql_upgrade', [
            'version' => $version,
        ], $extra, HttpMethod::Post);
    }
}
