<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Whm;

use Itxshakil\CpanelWhm\Api\WhmGroup;
use Itxshakil\CpanelWhm\Enums\HttpMethod;
use Itxshakil\CpanelWhm\Exceptions\WhmException;
use Itxshakil\CpanelWhm\WhmResponse;

/**
 * WHM API 1: IP Address Management (16 functions).
 *
 * Every method returns the checked WhmResponse; a failure throws a WhmException.
 */
final class IpAddressManagement extends WhmGroup
{
    /**
     * Add IP addresses.
     *
     * This function adds an IPv4 address or addresses to the server. When you add an IP address, the
     * system attempts to add an alias of that IP address to the main network interface. This process
     * rebuilds the IP address pool, which resides in the `/etc/ipaddrpool` file.
     *
     * @param  string  $ips  The IPv4 address or address range in Class C CIDR format.
     * @param  string  $netmask  The IPv4 address' netmask.
     * @param  string|null  $excludes  An IPv4 address or comma-delimited list of IPv4 addresses to exclude.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/ips-addips
     */
    public function addips(
        string $ips,
        string $netmask,
        ?string $excludes = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('addips', [
            'ips' => $ips,
            'netmask' => $netmask,
            'excludes' => $excludes,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Remove IP address.
     *
     * This function removes an IP address from the server.
     *
     * @param  string  $ip  The IPv4 address.
     * @param  string|null  $ethernetdev  The network alias to which the IPv4 address is bound.
     * @param  bool|int|null  $skipifshutdown  Whether to remove the IP address if the ethernet interface is down.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/ips-delip
     */
    public function delip(
        string $ip,
        ?string $ethernetdev = null,
        bool|int|null $skipifshutdown = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('delip', [
            'ip' => $ip,
            'ethernetdev' => $ethernetdev,
            'skipifshutdown' => $skipifshutdown,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return public IP address of private IP address.
     *
     * This function returns the public IP address for a specified public or private IP address. You can
     * use this function to determine the system's main public IP address, especially for systems that use
     * a 1:1 NAT configuration. * cPanel & WHM uses the main public IP address to perform many different
     * functions.
     *
     * @param  string  $ip  A valid public or private IP address to query.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/ips-get_public_ip
     */
    public function getPublicIp(
        string $ip,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_public_ip', [
            'ip' => $ip,
        ], $extra);
    }

    /**
     * Return shared IP address.
     *
     * This function retrieves the IP address that an account shares with the accounts that it owns.
     *
     * @param  string|null  $user  The WHM user's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/ips-get_shared_ip
     */
    public function getSharedIp(
        ?string $user = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_shared_ip', [
            'user' => $user,
        ], $extra);
    }

    /**
     * Remove IPv6 address range from account.
     *
     * This function removes the IPv6 address from an account.
     *
     * @param  string  $user  A comma delimited list of account names.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/ipv6-ipv6_disable_account
     */
    public function ipv6DisableAccount(
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('ipv6_disable_account', [
            'user' => $user,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Add IPv6 address range to accounts.
     *
     * This function assigns an IPv6 address to one or more accounts.
     *
     * @param  string  $range  The IPv6 address range's name.
     * @param  string  $user  A comma-delimited list of account names.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/ipv6-ipv6_enable_account
     */
    public function ipv6EnableAccount(
        string $range,
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('ipv6_enable_account', [
            'range' => $range,
            'user' => $user,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Add IPv6 address range.
     *
     * This function adds a range of IPv6 addresses to the server.
     *
     * @param  string  $name  The IPv6 address range's name.
     * @param  string  $range  The IPv6 address range and network portion in CIDR format.
     * @param  bool|int|null  $enabled  Whether the IPv6 address range is available.
     * @param  string|null  $note  A note for the IPv6 address range.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/ipv6-ipv6_range_add
     */
    public function ipv6RangeAdd(
        string $name,
        string $range,
        bool|int|null $enabled = null,
        ?string $note = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('ipv6_range_add', [
            'name' => $name,
            'range' => $range,
            'enabled' => $enabled,
            'note' => $note,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update IPv6 address range name or note.
     *
     * This function changes an IPv6 address range's name and/or note.
     *
     * @param  string  $name  The IPv6 address range's current name.
     * @param  string|null  $newName  The IPv6 address range's new name.
     * @param  string|null  $note  The IPv6 address range's new note.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/ipv6-ipv6_range_edit
     */
    public function ipv6RangeEdit(
        string $name,
        ?string $newName = null,
        ?string $note = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('ipv6_range_edit', [
            'name' => $name,
            'new_name' => $newName,
            'note' => $note,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return available IPv6 address ranges.
     *
     * This function lists available IPv6 address ranges.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/ipv6-ipv6_range_list
     */
    public function ipv6RangeList(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('ipv6_range_list', [], $extra);
    }

    /**
     * Remove IPv6 address range.
     *
     * This function removes an IPv6 address range from the server.
     *
     * @param  string  $name  The IPv6 address range's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/ipv6-ipv6_range_remove
     */
    public function ipv6RangeRemove(
        string $name,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('ipv6_range_remove', [
            'name' => $name,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return IPv6 address usage.
     *
     * This function retrieves usage information for IPv6 addresses in an IPv6 range.
     *
     * @param  string  $name  The IPv6 address range's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/ipv6-ipv6_range_usage
     */
    public function ipv6RangeUsage(
        string $name,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('ipv6_range_usage', [
            'name' => $name,
        ], $extra);
    }

    /**
     * Return server's IP addresses.
     *
     * This function lists a server's IP addresses.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/ips-listips
     */
    public function listips(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('listips', [], $extra);
    }

    /**
     * Return server's IPv6 addresses.
     *
     * This function lists the IPv6 addresses bound to a server’s network interfaces.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/ips-listipv6s
     */
    public function listipv6S(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('listipv6s', [], $extra);
    }

    /**
     * Validate public IP address for NAT.
     *
     * This function validates a public IP address on a NAT-configured server.
     *
     * @param  string  $ip  The local IPv4 address.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/nat-nat_checkip
     */
    public function natCheckip(
        string $ip,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('nat_checkip', [
            'ip' => $ip,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Register NAT IP address to public IP address.
     *
     * This function pairs a local IP address with a public IP address on NAT-configured servers.
     *
     * @param  string  $localIp  The local IPv4 address.
     * @param  string  $publicIp  The public IPv4 address.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/nat-nat_set_public_ip
     */
    public function natSetPublicIp(
        string $localIp,
        string $publicIp,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('nat_set_public_ip', [
            'local_ip' => $localIp,
            'public_ip' => $publicIp,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update domain or cPanel account IP address.
     *
     * This function changes a site's or account's IP address.
     *
     * @param  string  $ip  The site's or user's IPv4 address.
     * @param  string|null  $domain  The domain's name.
     * @param  string|null  $user  The user's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/ip-addresses/accounts-setsiteip
     */
    public function setsiteip(
        string $ip,
        ?string $domain = null,
        ?string $user = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('setsiteip', [
            'ip' => $ip,
            'domain' => $domain,
            'user' => $user,
        ], $extra, HttpMethod::Post);
    }
}
