<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Whm;

use Itxshakil\CpanelWhm\Api\WhmGroup;
use Itxshakil\CpanelWhm\Exceptions\WhmException;
use Itxshakil\CpanelWhm\WhmResponse;

/**
 * WHM API 1: Logs (1 functions).
 *
 * Every method returns the checked WhmResponse; a failure throws a WhmException.
 */
final class Logs extends WhmGroup
{
    /**
     * List accounts' web log retention settings.
     *
     * List each cPanel account's web server log retention preference alongside the server default.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/web-log-retention/weblogretention-list_accounts_retention
     */
    public function listAccountsRetention(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('list_accounts_retention', [], $extra);
    }
}
