<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Whm;

use Itxshakil\CpanelWhm\Api\WhmGroup;
use Itxshakil\CpanelWhm\Enums\HttpMethod;
use Itxshakil\CpanelWhm\Exceptions\WhmException;
use Itxshakil\CpanelWhm\WhmResponse;
use SensitiveParameter;

/**
 * WHM API 1: Mail (66 functions).
 *
 * Every method returns the checked WhmResponse; a failure throws a WhmException.
 */
final class Mail extends WhmGroup
{
    /**
     * Apply a DMARC record to a domain.
     *
     * This function applies a DMARC record to the specified domain(s).
     *
     * @param  string  $policy  The DMARC record to apply to the requested domains.
     * @param  string|null  $domain  The domain for which to apply the DMARC record.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/emailauth-apply_dmarc
     */
    public function applyDmarc(
        string $policy,
        ?string $domain = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('apply_dmarc', [
            'policy' => $policy,
            'domain' => $domain,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Add block on emails from specific countries.
     *
     * This function blocks email from specific countries.
     *
     * @param  string  $countryCode  The country to block.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/spam-management/exim-block_incoming_email_from_country
     */
    public function blockIncomingEmailFromCountry(
        string $countryCode,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('block_incoming_email_from_country', [
            'country_code' => $countryCode,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Add block on emails from specific domains.
     *
     * This function blocks email from specific domains.
     *
     * @param  string  $domain  The domain to block.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/spam-management/exim-block_incoming_email_from_domain
     */
    public function blockIncomingEmailFromDomain(
        string $domain,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('block_incoming_email_from_domain', [
            'domain' => $domain,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return Greylisting trust status of server netblock.
     *
     * This function returns the Greylisting trusted status of the server's netblock.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-cpgreylist_is_server_netblock_trusted
     */
    public function cpgreylistIsServerNetblockTrusted(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('cpgreylist_is_server_netblock_trusted', [], $extra);
    }

    /**
     * Return Greylisting IP addresses of mail providers.
     *
     * This function lists Greylisting's IP addresses for the specified mail provider.
     *
     * @param  string  $provider  The mail provider.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-cpgreylist_list_entries_for_common_mail_provider
     */
    public function cpgreylistListEntriesForCommonMailProvider(
        string $provider,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('cpgreylist_list_entries_for_common_mail_provider', [
            'provider' => $provider,
        ], $extra);
    }

    /**
     * Return Greylisting mail providers.
     *
     * This function returns Greylisting's list of common mail service providers.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-cpgreylist_load_common_mail_providers_config
     */
    public function cpgreylistLoadCommonMailProvidersConfig(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('cpgreylist_load_common_mail_providers_config', [], $extra);
    }

    /**
     * Update Greylisting new mail provider handling.
     *
     * This function sets whether Greylisting trusts new entries to cPanel's common mail providers list.
     *
     * @param  bool|int|null  $autotrustNewCommonMailProviders  Whether Greylisting automatically trusts new mail providers that cPanel adds to the common mail providers list.
     * @param  bool|int|null  $providerkey  Whether Greylisting automatically trusts new IP addresses that cPanel adds to this mail provider.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-cpgreylist_save_common_mail_providers_config
     */
    public function cpgreylistSaveCommonMailProvidersConfig(
        bool|int|null $autotrustNewCommonMailProviders = null,
        bool|int|null $providerkey = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('cpgreylist_save_common_mail_providers_config', [
            'autotrust_new_common_mail_providers' => $autotrustNewCommonMailProviders,
            'PROVIDERKEY' => $providerkey,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return Greylisting status.
     *
     * This function returns the status of Greylisting.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-cpgreylist_status
     */
    public function cpgreylistStatus(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('cpgreylist_status', [], $extra);
    }

    /**
     * Add mail provider to Greylisting trusted hosts.
     *
     * This function marks the IP addresses for the specified mail provider as trusted. Greylisting will
     * not defer emails from trusted IP addresses.
     *
     * @param  string  $provider  The mail providers’ names.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-cpgreylist_trust_entries_for_common_mail_provider
     */
    public function cpgreylistTrustEntriesForCommonMailProvider(
        string $provider,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('cpgreylist_trust_entries_for_common_mail_provider', [
            'provider' => $provider,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Add mail provider to Greylisting non-trusted hosts.
     *
     * This function marks the IP addresses for the specified mail provider as not trusted. Greylisting
     * defers emails from non-trusted IP addresses.
     *
     * @param  string  $provider  The mail provider.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-cpgreylist_untrust_entries_for_common_mail_provider
     */
    public function cpgreylistUntrustEntriesForCommonMailProvider(
        string $provider,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('cpgreylist_untrust_entries_for_common_mail_provider', [
            'provider' => $provider,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Add IP address to Greylisting trusted hosts.
     *
     * This function adds an IP address to the *Greylisting Trusted Hosts* list.
     *
     * @param  string  $ip  The record's IP address, or a range of IP addresses.
     * @param  string|null  $comment  A comment.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-create_cpgreylist_trusted_host
     */
    public function createCpgreylistTrustedHost(
        string $ip,
        ?string $comment = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('create_cpgreylist_trusted_host', [
            'ip' => $ip,
            'comment' => $comment,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Remove IP address from Greylisting trusted hosts.
     *
     * This function deletes an IP address from the Greylisting _Trusted Hosts_ list.
     *
     * @param  string  $ip  The record's IP address, or a range of IP addresses.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-delete_cpgreylist_trusted_host
     */
    public function deleteCpgreylistTrustedHost(
        string $ip,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('delete_cpgreylist_trusted_host', [
            'ip' => $ip,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Disable Greylisting.
     *
     * This function disables Greylisting.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-disable_cpgreylist
     */
    public function disableCpgreylist(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('disable_cpgreylist', [], $extra, HttpMethod::Post);
    }

    /**
     * Disable domain's DKIM records.
     *
     * This function removes the DomainKeys Identified Mail (DKIM) records on the DNS server for one or
     * more domains.
     *
     * @param  string  $domain  The domain for which to remove DKIM records on the DNS server.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/emailauth-disable_dkim
     */
    public function disableDkim(
        string $domain,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('disable_dkim', [
            'domain' => $domain,
        ], $extra, HttpMethod::Post);
    }

    /**
     * (Deprecated) Disable SNI mail services for domains.
     *
     * This function is deprecated and always fails.
     *
     * @param  string|null  $domain  The account's domain.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @deprecated cPanel has deprecated this function.
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-server-settings/ssl-disable_mail_sni
     */
    public function disableMailSni(
        ?string $domain = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('disable_mail_sni', [
            'domain' => $domain,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return email delivery records by search criteria.
     *
     * This function retrieves email delivery records.
     *
     * @param  bool|int|null  $defer  Whether to return delivery deferral events.
     * @param  string|null  $deliverytype  The type of delivery records to retrieve.
     * @param  bool|int|null  $failure  Whether to return delivery failure events.
     * @param  bool|int|null  $inprogress  Whether to return delivery attempts in progress.
     * @param  int|null  $maxResultsByType  The number of results to return for each type.
     * @param  bool|int|null  $success  Whether to return successful delivery attempts.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/exim-emailtrack_search
     */
    public function emailtrackSearch(
        bool|int|null $defer = null,
        ?string $deliverytype = null,
        bool|int|null $failure = null,
        bool|int|null $inprogress = null,
        ?int $maxResultsByType = null,
        bool|int|null $success = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('emailtrack_search', [
            'defer' => $defer,
            'deliverytype' => $deliverytype,
            'failure' => $failure,
            'inprogress' => $inprogress,
            'max_results_by_type' => $maxResultsByType,
            'success' => $success,
        ], $extra);
    }

    /**
     * Return cPanel account email tracking statistics.
     *
     * This function retrieves email tracking statistics.
     *
     * @param  string|null  $deliverytype  The type of delivery to query.
     * @param  int|null  $enddate  The end date of the search window.
     * @param  int|null  $endtime  The end time of the search window.
     * @param  bool|int|null  $nosize  Whether to return the `TOTALSIZE` parameter.
     * @param  bool|int|null  $nosuccess  Whether to return the `SUCCESSCOUNT` parameter.
     * @param  int|null  $startdate  The start date of the search window.
     * @param  int|null  $starttime  The start time of the search window.
     * @param  string|null  $user  The cPanel username to query.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/exim-emailtrack_stats
     */
    public function emailtrackStats(
        ?string $deliverytype = null,
        ?int $enddate = null,
        ?int $endtime = null,
        bool|int|null $nosize = null,
        bool|int|null $nosuccess = null,
        ?int $startdate = null,
        ?int $starttime = null,
        ?string $user = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('emailtrack_stats', [
            'deliverytype' => $deliverytype,
            'enddate' => $enddate,
            'endtime' => $endtime,
            'nosize' => $nosize,
            'nosuccess' => $nosuccess,
            'startdate' => $startdate,
            'starttime' => $starttime,
            'user' => $user,
        ], $extra);
    }

    /**
     * Return all cPanel accounts email tracking statistics.
     *
     * This function retrieves email tracking statistics for each user.
     *
     * @param  string|null  $deliverytype  The type of delivery to query.
     * @param  int|null  $endtime  The end time of the search window.
     * @param  string|null  $sender  The sender's email address.
     * @param  int|null  $starttime  The start time of the search window.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/exim-emailtrack_user_stats
     */
    public function emailtrackUserStats(
        ?string $deliverytype = null,
        ?int $endtime = null,
        ?string $sender = null,
        ?int $starttime = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('emailtrack_user_stats', [
            'deliverytype' => $deliverytype,
            'endtime' => $endtime,
            'sender' => $sender,
            'starttime' => $starttime,
        ], $extra);
    }

    /**
     * Enable Greylisting.
     *
     * This function enables Greylisting.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-enable_cpgreylist
     */
    public function enableCpgreylist(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('enable_cpgreylist', [], $extra, HttpMethod::Post);
    }

    /**
     * Enable domain's DKIM records.
     *
     * This function enables DomainKeys Identified Mail (DKIM) records on the DNS server for one or more
     * domains.
     *
     * @param  string  $domain  The domain for which to enable DKIM records on the DNS server.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/emailauth-enable_dkim
     */
    public function enableDkim(
        string $domain,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('enable_dkim', [
            'domain' => $domain,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Enable SNI mail services for domains.
     *
     * This function enables SNI for mail services on the specified domains.
     *
     * @param  string  $domain  The account's domain.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-server-settings/ssl-enable_mail_sni
     */
    public function enableMailSni(
        string $domain,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('enable_mail_sni', [
            'domain' => $domain,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Validate domain's DKIM keys.
     *
     * This function confirms the validity of a DomainKeys Identified Mail (DKIM) key for one or more
     * domains.
     *
     * @param  string  $domain  The domain for which to confirm a valid DKIM key exists.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/emailauth-ensure_dkim_keys_exist
     */
    public function ensureDkimKeysExist(
        string $domain,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('ensure_dkim_keys_exist', [
            'domain' => $domain,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Repair Exim configuration file.
     *
     * This function scans the Exim configuration file for errors, and if it finds errors attempts to
     * repair them.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-server-settings/exim-exim_configuration_check
     */
    public function eximConfigurationCheck(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('exim_configuration_check', [], $extra, HttpMethod::Post);
    }

    /**
     * Remove email account messages by Dovecot query.
     *
     * This function removes mail messages from a cPanel account that you select with a query.
     *
     * @param  string  $account  An email account that exists on the server.
     * @param  string  $mailbox  A mailbox name on the account.
     * @param  string  $query  A Dovecot search query to select which messages you wish to remove from the mailbox.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/mailboxes-expunge_mailbox_messages
     */
    public function expungeMailboxMessages(
        string $account,
        string $mailbox,
        string $query,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('expunge_mailbox_messages', [
            'account' => $account,
            'mailbox' => $mailbox,
            'query' => $query,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Remove email account messages by mailbox GUID.
     *
     * This function removes mail messages from a cPanel account.
     *
     * @param  string  $account  The email account's name.
     * @param  string  $mailboxGuid  The mailbox's globally unique identifier (GUID).
     * @param  string  $query  The Dovecot search query to select which messages you wish to remove from the mailbox.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/mailboxes-expunge_messages_for_mailbox_guid
     */
    public function expungeMessagesForMailboxGuid(
        string $account,
        string $mailboxGuid,
        string $query,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('expunge_messages_for_mailbox_guid', [
            'account' => $account,
            'mailbox_guid' => $mailboxGuid,
            'query' => $query,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return domain's DKIM private key.
     *
     * This function returns a domain's installed DKIM private key in Privacy-Enhanced Mail (PEM) format.
     *
     * @param  string  $domain  The queried domain.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/emailauth-fetch_dkim_private_keys
     */
    public function fetchDkimPrivateKeys(
        string $domain,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('fetch_dkim_private_keys', [
            'domain' => $domain,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return server mail queue contents.
     *
     * This function retrieves the contents of the server's mail queue.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-server-settings/exim-fetch_mail_queue
     */
    public function fetchMailQueue(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('fetch_mail_queue', [], $extra);
    }

    /**
     * Create email account mobile profile configuration.
     *
     * This function generates a mobile configuration profile for an email account.
     *
     * @param  string  $account  The email account's username.
     * @param  bool|int  $useSsl  Whether to use an SSL-encrypted connection.
     * @param  string|null  $selectedAccountServices  A comma-separated list of the email account service's `.mobileconfig` file names.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-server-settings/email-generate_mobileconfig
     */
    public function generateMobileconfig(
        string $account,
        bool|int $useSsl,
        ?string $selectedAccountServices = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('generate_mobileconfig', [
            'account' => $account,
            'use_ssl' => $useSsl,
            'selected_account_services' => $selectedAccountServices,
        ], $extra);
    }

    /**
     * Get the server's default DMARC record.
     *
     * This function retrieves the server's default DMARC record.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/emailauth-get_default_dmarc_record
     */
    public function getDefaultDmarcRecord(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_default_dmarc_record', [], $extra);
    }

    /**
     * Return cPanel account mailboxes status by name.
     *
     * This function lists the status of a cPanel's mail account's mailboxes.
     *
     * @param  string  $account  An email account or cPanel account's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/mailboxes-get_mailbox_status
     */
    public function getMailboxStatus(
        string $account,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_mailbox_status', [
            'account' => $account,
        ], $extra);
    }

    /**
     * Return cPanel account mailboxes status list.
     *
     * This function lists the status of a cPanel's mail account's mailboxes.
     *
     * @param  string  $account  The email account's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/mailboxes-get_mailbox_status_list
     */
    public function getMailboxStatusList(
        string $account,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_mailbox_status_list', [
            'account' => $account,
        ], $extra);
    }

    /**
     * Return cPanel account unique email recipients.
     *
     * This function gets the number of unique recipients that a system user sent mail to within a period
     * of time. It groups this data by each of the user's email accounts.
     *
     * @param  int  $endTime  An end time to query.
     * @param  int  $startTime  A start time to query.
     * @param  string  $user  The system user's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/exim-get_unique_recipient_count_per_sender_for_user
     */
    public function getUniqueRecipientCountPerSenderForUser(
        int $endTime,
        int $startTime,
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_unique_recipient_count_per_sender_for_user', [
            'end_time' => $endTime,
            'start_time' => $startTime,
            'user' => $user,
        ], $extra);
    }

    /**
     * Return all cPanel account unique email recipients.
     *
     * This function gets a count of the email addresses that each system account sent mail to within a
     * specific period of time. It groups the data by each system user for all the system's users.
     *
     * @param  int  $endTime  An end time to query.
     * @param  int  $startTime  A start time to query.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/exim-get_unique_sender_recipient_count_per_user
     */
    public function getUniqueSenderRecipientCountPerUser(
        int $endTime,
        int $startTime,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_unique_sender_recipient_count_per_user', [
            'end_time' => $endTime,
            'start_time' => $startTime,
        ], $extra);
    }

    /**
     * Return cPanel account forward destination.
     *
     * This function retrieves the destination to which the system forwards a system account's email.
     *
     * @param  string  $user  The system account name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/email-get_user_email_forward_destination
     */
    public function getUserEmailForwardDestination(
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_user_email_forward_destination', [
            'user' => $user,
        ], $extra);
    }

    /**
     * Add cPanel account to outbound email hold queue.
     *
     * This function sets Exim's queue to hold email that a user sends to an external address.
     *
     * @param  string  $user  The cPanel account.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/accounts-hold_outgoing_email
     */
    public function holdOutgoingEmail(
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('hold_outgoing_email', [
            'user' => $user,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Install existing private key to DKIM record.
     *
     * This function installs existing keys for use in a DomainKeys Identified Mail (DKIM) record. This is
     * useful if you do not want the system to generate keys for DKIM records.
     *
     * @param  string  $domain  The domain for which to install an RSA private key to the local server's DKIM record.
     * @param  string  $key  An RSA key in Privacy-Enhanced Mail (PEM) format.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/emailauth-install_dkim_private_keys
     */
    public function installDkimPrivateKeys(
        string $domain,
        #[SensitiveParameter] string $key,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('install_dkim_private_keys', [
            'domain' => $domain,
            'key' => $key,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Install domain SPF record.
     *
     * This function installs a Sender Policy Framework (SPF) record for a domain on the DNS server.
     *
     * @param  string  $domain  The domain for which to install an SPF record on the DNS server.
     * @param  string  $record  An SPF record.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/emailauth-install_spf_records
     */
    public function installSpfRecords(
        string $domain,
        string $record,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('install_spf_records', [
            'domain' => $domain,
            'record' => $record,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return server SNI support status.
     *
     * This function checks whether the server supports SNI (Server Name Indication).
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-server-settings/ssl-is_sni_supported
     */
    public function isSniSupported(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('is_sni_supported', [], $extra);
    }

    /**
     * Return blocked email countries list.
     *
     * This function lists which countries cannot send email to the server.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/spam-management/exim-list_blocked_incoming_email_countries
     */
    public function listBlockedIncomingEmailCountries(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('list_blocked_incoming_email_countries', [], $extra);
    }

    /**
     * Return blocked email domains list.
     *
     * This function lists which domains cannot send email to the server.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/spam-management/exim-list_blocked_incoming_email_domains
     */
    public function listBlockedIncomingEmailDomains(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('list_blocked_incoming_email_domains', [], $extra);
    }

    /**
     * Return cPanel account's email accounts.
     *
     * This function lists a cPanel account’s email accounts. To prevent falsified data or symlink
     * exploitation, the function uses the specified cPanel account user, rather than `root` user, to read
     * data from the user’s home directory.
     *
     * @param  string  $user  The cPanel account user for which to list all owned email accounts.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/email-list_pops_for
     */
    public function listPopsFor(
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('list_pops_for', [
            'user' => $user,
        ], $extra);
    }

    /**
     * Return Greylisting settings.
     *
     * This function returns Greylisting's current settings.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-load_cpgreylist_config
     */
    public function loadCpgreylistConfig(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('load_cpgreylist_config', [], $extra);
    }

    /**
     * Return domain's SNI mail services status.
     *
     * This function retrieves the status of the domain's SNI mail services.
     *
     * @param  string  $domain  The account's domain.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-server-settings/ssl-mail_sni_status
     */
    public function mailSniStatus(
        string $domain,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('mail_sni_status', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Repair misconfigured email settings.
     *
     * This function fixes a user's misconfigured email settings. This includes any misconfigured email
     * file and directory ownership and permissions.
     *
     * @param  string  $username  The cPanel account's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-server-settings/email-normalize_user_email_configuration
     */
    public function normalizeUserEmailConfiguration(
        string $username,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('normalize_user_email_configuration', [
            'username' => $username,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Return Greylisting deferred incoming email triplets.
     *
     * This function lists Greylisting's deferred triplets. Greylisting identifies incoming email by
     * triplets.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-read_cpgreylist_deferred_entries
     */
    public function readCpgreylistDeferredEntries(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('read_cpgreylist_deferred_entries', [], $extra);
    }

    /**
     * Return Greylisting trusted hosts.
     *
     * This function retrieves the entries on the Greylisting Trusted Hosts list.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-read_cpgreylist_trusted_hosts
     */
    public function readCpgreylistTrustedHosts(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('read_cpgreylist_trusted_hosts', [], $extra);
    }

    /**
     * Rebuild mail SNI configuration files.
     *
     * This function rebuilds the mail SNI configuration files.
     *
     * @param  bool|int|null  $reloadDovecot  Whether to reload the Dovecot service after the system rebuilds the configuration files.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-server-settings/ssl-rebuild_mail_sni_config
     */
    public function rebuildMailSniConfig(
        bool|int|null $reloadDovecot = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('rebuild_mail_sni_config', [
            'reload_dovecot' => $reloadDovecot,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Release cPanel account queued outgoing emails.
     *
     * This function releases outgoing email in the email queue for a single cPanel account user.
     *
     * @param  string  $user  The cPanel account.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/accounts-release_outgoing_email
     */
    public function releaseOutgoingEmail(
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('release_outgoing_email', [
            'user' => $user,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Remove domains' DMARC records.
     *
     * This function removes the DMARC DNS record from a domain.
     *
     * @param  string|null  $domain  The domain for which to remove the DMARC record.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/emailauth-remove_dmarc
     */
    public function removeDmarc(
        ?string $domain = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('remove_dmarc', [
            'domain' => $domain,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update Greylisting settings.
     *
     * This function modifies the server's Greylisting configuration settings.
     *
     * @param  int|null  $childTimeoutSecs  The maximum of seconds that Greylisting waits for a child process to timeout.
     * @param  int|null  $initialBlockTimeMins  The number of minutes during which Greylisting defers email from an unknown triplet.
     * @param  int|null  $maxChildProcs  The maximum number of child processes.
     * @param  int|null  $mustTryTimeMins  The number of minutes during which Greylisting accepts a re-sent email from an unknown triplet.
     * @param  int|null  $purgeIntervalMins  The number of minutes before Greylisting deletes the records in the Greylisting database.
     * @param  int|null  $recordExpTimeMins  The number of minutes before Greylisting deletes the triplet record and treats a re-sent email as coming from a new, unknown triplet.
     * @param  bool|int|null  $spfBypass  Whether emails with SPF bypass Greylisting.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/greylisting/cpgreylist-save_cpgreylist_config
     */
    public function saveCpgreylistConfig(
        ?int $childTimeoutSecs = null,
        ?int $initialBlockTimeMins = null,
        ?int $maxChildProcs = null,
        ?int $mustTryTimeMins = null,
        ?int $purgeIntervalMins = null,
        ?int $recordExpTimeMins = null,
        bool|int|null $spfBypass = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('save_cpgreylist_config', [
            'child_timeout_secs' => $childTimeoutSecs,
            'initial_block_time_mins' => $initialBlockTimeMins,
            'max_child_procs' => $maxChildProcs,
            'must_try_time_mins' => $mustTryTimeMins,
            'purge_interval_mins' => $purgeIntervalMins,
            'record_exp_time_mins' => $recordExpTimeMins,
            'spf_bypass' => $spfBypass,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update Apache SpamAssassin configuration.
     *
     * This function configures your Apache SpamAssassin options.
     *
     * @param  string|null  $allowedips  A comma-separated list of IP addresses to authorize to access the spamd daemon.
     * @param  int|null  $maxchildren  The maximum number of children per `spamd` process.
     * @param  int|null  $maxconnperchild  The maximum number of connections that the `spamd` daemon allows per child process.
     * @param  string|null  $pidfile  The process ID's file path.
     * @param  int|null  $timeoutchild  The maximum amount of time that a child process waits before it abandons a TCP connection.
     * @param  int|null  $timeouttcp  The maximum amount of time that the `spamd` daemon waits before it abandons a TCP connection.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/spam-management/spamd-save_spamd_config
     */
    public function saveSpamdConfig(
        ?string $allowedips = null,
        ?int $maxchildren = null,
        ?int $maxconnperchild = null,
        ?string $pidfile = null,
        ?int $timeoutchild = null,
        ?int $timeouttcp = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('save_spamd_config', [
            'allowedips' => $allowedips,
            'maxchildren' => $maxchildren,
            'maxconnperchild' => $maxconnperchild,
            'pidfile' => $pidfile,
            'timeoutchild' => $timeoutchild,
            'timeouttcp' => $timeouttcp,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Set the server's default DMARC record.
     *
     * This function sets the server's default DMARC record.
     *
     * @param  string|null  $record  The DMARC record to set as the server default.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/emailauth-set_default_dmarc_record
     */
    public function setDefaultDmarcRecord(
        ?string $record = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('set_default_dmarc_record', [
            'record' => $record,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Add manual mail exchanger redirect record.
     *
     * This function lets you create a manual Exim mail exchanger (MX) redirect for a domain. An MX
     * redirection lets you bypass the domain's MX lookup via the Domain Name System (DNS). This function
     * adds the manual redirect entries to the /etc/manualmx file.
     *
     * @param  string  $domain  The domain for which to add a manual MX redirect entry.
     * @param  string  $mxHost  The domain or IP address (IPv4 or IPv6) to redirect the domain value's emails to.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/exim-set_manual_mx_redirects
     */
    public function setManualMxRedirects(
        string $domain,
        string $mxHost,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('set_manual_mx_redirects', [
            'domain' => $domain,
            'mx_host' => $mxHost,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Update cPanel account email forward destination.
     *
     * This function sets the destination to which the system forwards a system account's email.
     *
     * @param  string  $forwardTo  The system account name or email address to which you wish to forward email.
     * @param  string  $user  The system account name to forward.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/email-set_user_email_forward_destination
     */
    public function setUserEmailForwardDestination(
        string $forwardTo,
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('set_user_email_forward_destination', [
            'forward_to' => $forwardTo,
            'user' => $user,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Suspend cPanel account outgoing email.
     *
     * This function sets Exim's queue to suspend and force failure for email that a user sends to an
     * external address.
     *
     * @param  string  $user  The cPanel account.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/accounts-suspend_outgoing_email
     */
    public function suspendOutgoingEmail(
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('suspend_outgoing_email', [
            'user' => $user,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Stop cPanel account IMAP and POP3 connections.
     *
     * This function terminates all IMAP and POP3 connections for a cPanel account.
     *
     * @param  string  $username  The cPanel account's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/mailboxes-terminate_cpuser_mailbox_sessions
     */
    public function terminateCpuserMailboxSessions(
        string $username,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('terminate_cpuser_mailbox_sessions', [
            'username' => $username,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Remove block on emails from specific countries.
     *
     * This function unblocks email from specific countries.
     *
     * @param  string|null  $countryCode  The country to unblock.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/spam-management/exim-unblock_incoming_email_from_country
     */
    public function unblockIncomingEmailFromCountry(
        ?string $countryCode = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('unblock_incoming_email_from_country', [
            'country_code' => $countryCode,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Remove block on emails from specific domains.
     *
     * This function unblocks email from specific domains.
     *
     * @param  string  $domain  The domain to unblock.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/spam-management/exim-unblock_incoming_email_from_domain
     */
    public function unblockIncomingEmailFromDomain(
        string $domain,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('unblock_incoming_email_from_domain', [
            'domain' => $domain,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Remove manual mail exchanger redirect record.
     *
     * This function removes a domain's manual Exim mail exchanger (MX) redirect entry. The function also
     * removes the manual MX redirect entry from the /etc/manualmx file.
     *
     * @param  string  $domain  The domain for which to remove a manual MX redirect entry.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/exim-unset_manual_mx_redirects
     */
    public function unsetManualMxRedirects(
        string $domain,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('unset_manual_mx_redirects', [
            'domain' => $domain,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Unsuspend account outgoing email.
     *
     * This function unsuspends outgoing email for a cPanel account's users.
     *
     * @param  string  $user  The cPanel account.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/cpanel-account-mail-management/accounts-unsuspend_outgoing_email
     */
    public function unsuspendOutgoingEmail(
        string $user,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('unsuspend_outgoing_email', [
            'user' => $user,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Validate DKIM records.
     *
     * This function retrieves and checks the DomainKeys Identified Mail (DKIM) records for one or more
     * domains.
     *
     * @param  string  $domain  The domain for which to check the DKIM records.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/emailauth-validate_current_dkims
     */
    public function validateCurrentDkims(
        string $domain,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('validate_current_dkims', [
            'domain' => $domain,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Validate DMARC records.
     *
     * This function retrieves and checks the DMARC record for one or more domains.
     *
     * @param  string|null  $domain  The domain for which to check the DMARC record.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/emailauth-validate_current_dmarcs
     */
    public function validateCurrentDmarcs(
        ?string $domain = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('validate_current_dmarcs', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Validate Exim configuration.
     *
     * This function validates the system's current Exim configuration.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-server-settings/exim-validate_current_installed_exim_config
     */
    public function validateCurrentInstalledEximConfig(
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('validate_current_installed_exim_config', [], $extra);
    }

    /**
     * Validate domain PTR records.
     *
     * This function validates the pointer records (PTR) for IPv4 and IPv6 addresses an account's domains
     * send mail from. It retrieves the PTR records for each IP address and determines which of the
     * domain's IP addresses send mail.
     *
     * @param  string  $domain  The domain for which to validate the PTR records.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/emailauth-validate_current_ptrs
     */
    public function validateCurrentPtrs(
        string $domain,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('validate_current_ptrs', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Validate domain SPF records.
     *
     * This function validates a Sender Policy Framework (SPF) record for one or more domains.
     *
     * @param  string  $domain  The domain for which to check the SPF records.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-dns-settings/emailauth-validate_current_spfs
     */
    public function validateCurrentSpfs(
        string $domain,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('validate_current_spfs', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Validate Exim configure file syntax.
     *
     * This function evaluates and validates an Exim configuration file's syntax.
     *
     * @param  string|null  $cfgText  The Exim configuration file's raw text.
     * @param  string|null  $section  The Exim configuration file's section to check.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/mail-server-settings/exim-validate_exim_configuration_syntax
     */
    public function validateEximConfigurationSyntax(
        ?string $cfgText = null,
        ?string $section = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('validate_exim_configuration_syntax', [
            'cfg_text' => $cfgText,
            'section' => $section,
        ], $extra);
    }
}
