<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Whm;

use Itxshakil\CpanelWhm\Api\WhmGroup;
use Itxshakil\CpanelWhm\Enums\HttpMethod;
use Itxshakil\CpanelWhm\Exceptions\WhmException;
use Itxshakil\CpanelWhm\WhmResponse;

/**
 * WHM API 1: UserData (2 functions).
 *
 * Every method returns the checked WhmResponse; a failure throws a WhmException.
 */
final class UserData extends WhmGroup
{
    /**
     * Get scoped userdata.
     *
     * This function retrieves all userdata key/value pairs within the specified scope.
     *
     * @param  string  $scope  The scope name whose userdata you wish to retrieve.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/userdata/userdata-get_scoped_userdata
     */
    public function getScopedUserdata(
        string $scope,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('get_scoped_userdata', [
            'scope' => $scope,
        ], $extra, HttpMethod::Post);
    }

    /**
     * Set scoped userdata.
     *
     * This function sets (creates or updates) a userdata key/value pair within the specified scope and
     * returns the full updated mapping.
     *
     * @param  string  $scope  The scope name to modify.
     * @param  string|null  $json  A json string to save to the specified scope.
     * @param  string|null  $key  The userdata key to set.
     * @param  string|null  $value  The value to assign to the key.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/whm.openapi/userdata/userdata-set_scoped_userdata
     */
    public function setScopedUserdata(
        string $scope,
        ?string $json = null,
        ?string $key = null,
        ?string $value = null,
        array $extra = [],
    ): WhmResponse {
        return $this->invoke('set_scoped_userdata', [
            'scope' => $scope,
            'json' => $json,
            'key' => $key,
            'value' => $value,
        ], $extra, HttpMethod::Post);
    }
}
