<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api;

use Itxshakil\CpanelWhm\Api\Whm\AccountRestoration;
use Itxshakil\CpanelWhm\Api\Whm\Accounts;
use Itxshakil\CpanelWhm\Api\Whm\ApiDevelopmentTools;
use Itxshakil\CpanelWhm\Api\Whm\Authentication;
use Itxshakil\CpanelWhm\Api\Whm\Backups;
use Itxshakil\CpanelWhm\Api\Whm\CommerceIntegration;
use Itxshakil\CpanelWhm\Api\Whm\CpanelMarket;
use Itxshakil\CpanelWhm\Api\Whm\CpanelSupportTickets;
use Itxshakil\CpanelWhm\Api\Whm\Customizations;
use Itxshakil\CpanelWhm\Api\Whm\Databases;
use Itxshakil\CpanelWhm\Api\Whm\Dns;
use Itxshakil\CpanelWhm\Api\Whm\HostingPlans;
use Itxshakil\CpanelWhm\Api\Whm\InProductSurvey;
use Itxshakil\CpanelWhm\Api\Whm\Integrations;
use Itxshakil\CpanelWhm\Api\Whm\IpAddressManagement;
use Itxshakil\CpanelWhm\Api\Whm\LoginSecurityCpHulk;
use Itxshakil\CpanelWhm\Api\Whm\Logs;
use Itxshakil\CpanelWhm\Api\Whm\Mail;
use Itxshakil\CpanelWhm\Api\Whm\Monitoring;
use Itxshakil\CpanelWhm\Api\Whm\NginxManager;
use Itxshakil\CpanelWhm\Api\Whm\Resellers;
use Itxshakil\CpanelWhm\Api\Whm\Security;
use Itxshakil\CpanelWhm\Api\Whm\ServerAdministration;
use Itxshakil\CpanelWhm\Api\Whm\SslCertificates;
use Itxshakil\CpanelWhm\Api\Whm\SystemPackageManagement;
use Itxshakil\CpanelWhm\Api\Whm\Transfers;
use Itxshakil\CpanelWhm\Api\Whm\UserData;
use Itxshakil\CpanelWhm\Api\Whm\WebServerConfiguration;
use Itxshakil\CpanelWhm\Api\Whm\WebServerSecurityModSecurity;
use Itxshakil\CpanelWhm\Contracts\WhmClient;

/**
 * Every documented WHM API 1 function as a typed method, grouped the way cPanel's
 * documentation groups them: Whm::api()->dns()->parseDnsZone(zone: 'example.com').
 */
final class WhmApi
{
    private ?AccountRestoration $accountRestoration = null;

    private ?Accounts $accounts = null;

    private ?ApiDevelopmentTools $apiDevelopmentTools = null;

    private ?Authentication $authentication = null;

    private ?Backups $backups = null;

    private ?CommerceIntegration $commerceIntegration = null;

    private ?CpanelMarket $cpanelMarket = null;

    private ?CpanelSupportTickets $cpanelSupportTickets = null;

    private ?Customizations $customizations = null;

    private ?Databases $databases = null;

    private ?Dns $dns = null;

    private ?HostingPlans $hostingPlans = null;

    private ?InProductSurvey $inProductSurvey = null;

    private ?Integrations $integrations = null;

    private ?IpAddressManagement $ipAddressManagement = null;

    private ?LoginSecurityCpHulk $loginSecurityCpHulk = null;

    private ?Logs $logs = null;

    private ?Mail $mail = null;

    private ?Monitoring $monitoring = null;

    private ?NginxManager $nginxManager = null;

    private ?Resellers $resellers = null;

    private ?Security $security = null;

    private ?ServerAdministration $serverAdministration = null;

    private ?SslCertificates $sslCertificates = null;

    private ?SystemPackageManagement $systemPackageManagement = null;

    private ?Transfers $transfers = null;

    private ?UserData $userData = null;

    private ?WebServerConfiguration $webServerConfiguration = null;

    private ?WebServerSecurityModSecurity $webServerSecurityModSecurity = null;

    public function __construct(private readonly WhmClient $target) {}

    /**
     * Account Restoration: 16 functions.
     */
    public function accountRestoration(): AccountRestoration
    {
        return $this->accountRestoration ??= new AccountRestoration($this->target);
    }

    /**
     * Accounts: 47 functions.
     */
    public function accounts(): Accounts
    {
        return $this->accounts ??= new Accounts($this->target);
    }

    /**
     * API Development Tools: 6 functions.
     */
    public function apiDevelopmentTools(): ApiDevelopmentTools
    {
        return $this->apiDevelopmentTools ??= new ApiDevelopmentTools($this->target);
    }

    /**
     * Authentication: 38 functions.
     */
    public function authentication(): Authentication
    {
        return $this->authentication ??= new Authentication($this->target);
    }

    /**
     * Backups: 27 functions.
     */
    public function backups(): Backups
    {
        return $this->backups ??= new Backups($this->target);
    }

    /**
     * Commerce Integration: 4 functions.
     */
    public function commerceIntegration(): CommerceIntegration
    {
        return $this->commerceIntegration ??= new CommerceIntegration($this->target);
    }

    /**
     * cPanel Market: 9 functions.
     */
    public function cpanelMarket(): CpanelMarket
    {
        return $this->cpanelMarket ??= new CpanelMarket($this->target);
    }

    /**
     * cPanel Support Tickets: 14 functions.
     */
    public function cpanelSupportTickets(): CpanelSupportTickets
    {
        return $this->cpanelSupportTickets ??= new CpanelSupportTickets($this->target);
    }

    /**
     * Customizations: 3 functions.
     */
    public function customizations(): Customizations
    {
        return $this->customizations ??= new Customizations($this->target);
    }

    /**
     * Databases: 26 functions.
     */
    public function databases(): Databases
    {
        return $this->databases ??= new Databases($this->target);
    }

    /**
     * DNS: 44 functions.
     */
    public function dns(): Dns
    {
        return $this->dns ??= new Dns($this->target);
    }

    /**
     * Hosting Plans: 24 functions.
     */
    public function hostingPlans(): HostingPlans
    {
        return $this->hostingPlans ??= new HostingPlans($this->target);
    }

    /**
     * InProductSurvey: 1 function.
     */
    public function inProductSurvey(): InProductSurvey
    {
        return $this->inProductSurvey ??= new InProductSurvey($this->target);
    }

    /**
     * Integrations: 12 functions.
     */
    public function integrations(): Integrations
    {
        return $this->integrations ??= new Integrations($this->target);
    }

    /**
     * IP Address Management: 16 functions.
     */
    public function ipAddressManagement(): IpAddressManagement
    {
        return $this->ipAddressManagement ??= new IpAddressManagement($this->target);
    }

    /**
     * Login Security (cPHulk): 16 functions.
     */
    public function loginSecurityCpHulk(): LoginSecurityCpHulk
    {
        return $this->loginSecurityCpHulk ??= new LoginSecurityCpHulk($this->target);
    }

    /**
     * Logs: 1 function.
     */
    public function logs(): Logs
    {
        return $this->logs ??= new Logs($this->target);
    }

    /**
     * Mail: 66 functions.
     */
    public function mail(): Mail
    {
        return $this->mail ??= new Mail($this->target);
    }

    /**
     * Monitoring: 7 functions.
     */
    public function monitoring(): Monitoring
    {
        return $this->monitoring ??= new Monitoring($this->target);
    }

    /**
     * NGINX Manager: 6 functions.
     */
    public function nginxManager(): NginxManager
    {
        return $this->nginxManager ??= new NginxManager($this->target);
    }

    /**
     * Resellers: 21 functions.
     */
    public function resellers(): Resellers
    {
        return $this->resellers ??= new Resellers($this->target);
    }

    /**
     * Security: 5 functions.
     */
    public function security(): Security
    {
        return $this->security ??= new Security($this->target);
    }

    /**
     * Server Administration: 81 functions.
     */
    public function serverAdministration(): ServerAdministration
    {
        return $this->serverAdministration ??= new ServerAdministration($this->target);
    }

    /**
     * SSL Certificates: 34 functions.
     */
    public function sslCertificates(): SslCertificates
    {
        return $this->sslCertificates ??= new SslCertificates($this->target);
    }

    /**
     * System Package Management: 14 functions.
     */
    public function systemPackageManagement(): SystemPackageManagement
    {
        return $this->systemPackageManagement ??= new SystemPackageManagement($this->target);
    }

    /**
     * Transfers: 15 functions.
     */
    public function transfers(): Transfers
    {
        return $this->transfers ??= new Transfers($this->target);
    }

    /**
     * UserData: 2 functions.
     */
    public function userData(): UserData
    {
        return $this->userData ??= new UserData($this->target);
    }

    /**
     * Web Server Configuration: 28 functions.
     */
    public function webServerConfiguration(): WebServerConfiguration
    {
        return $this->webServerConfiguration ??= new WebServerConfiguration($this->target);
    }

    /**
     * Web Server Security (ModSecurity): 38 functions.
     */
    public function webServerSecurityModSecurity(): WebServerSecurityModSecurity
    {
        return $this->webServerSecurityModSecurity ??= new WebServerSecurityModSecurity($this->target);
    }
}
