<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI AccountEnhancements module (2 functions), run as one cPanel account through WHM.
 */
final class AccountEnhancements extends UapiModule
{
    public const string MODULE = 'AccountEnhancements';

    /**
     * Validate Account Enhancement assignment.
     *
     * This function returns whether a cPanel account has a specific Account Enhancement.
     *
     * @param  string  $id  The identifier for a specific Account Enhancement.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/account-enhancements/accountenhancements-has_enhancement
     */
    public function hasEnhancement(
        string $id,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('has_enhancement', [
            'id' => $id,
        ], $extra);
    }

    /**
     * Return all cPanel account's Account Enhancements.
     *
     * This function lists a cPanel account's Account Enhancements.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/account-enhancements/accountenhancements-list
     */
    public function list(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list', [], $extra);
    }
}
