<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI AddonDomain module (3 functions), run as one cPanel account through WHM.
 */
final class AddonDomain extends UapiModule
{
    public const string MODULE = 'AddonDomain';

    /**
     * Create an addon domain.
     *
     * This function creates an addon domain on the cPanel account. It creates a subdomain of the account's
     * primary domain and then parks the new domain on that subdomain.
     *
     * @param  string  $newdomain  The addon domain to create.
     * @param  string  $subdomain  The label of the subdomain to create on the account's primary domain and park the addon domain on.
     * @param  string|null  $dir  The addon domain's document root, given as a directory path relative to the account's home directory.
     * @param  bool|int|null  $disallowdot  Whether to remove the dot (`.`) characters from the `subdomain` value.
     * @param  bool|int|null  $force  Accepted for compatibility, but ignored for account-level callers.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/addondomain/addondomain-addaddondomain
     */
    public function addaddondomain(
        string $newdomain,
        string $subdomain,
        ?string $dir = null,
        bool|int|null $disallowdot = null,
        bool|int|null $force = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('addaddondomain', [
            'newdomain' => $newdomain,
            'subdomain' => $subdomain,
            'dir' => $dir,
            'disallowdot' => $disallowdot,
            'force' => $force,
        ], $extra);
    }

    /**
     * Remove an addon domain.
     *
     * This function removes an addon domain from the cPanel account. It unparks the addon domain and then
     * removes the subdomain that the domain was parked on.
     *
     * @param  string  $domain  The addon domain to remove.
     * @param  string  $subdomain  The subdomain that the addon domain is parked on, given in the underscore-separated `subdomain_rootdomain` form that the `AddonDomain::listaddondomains` functi…
     * @param  bool|int|null  $disallowdot  Whether to remove the dot (`.`) characters from the subdomain label when the system removes the subdomain.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/addondomain/addondomain-deladdondomain
     */
    public function deladdondomain(
        string $domain,
        string $subdomain,
        bool|int|null $disallowdot = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('deladdondomain', [
            'domain' => $domain,
            'subdomain' => $subdomain,
            'disallowdot' => $disallowdot,
        ], $extra);
    }

    /**
     * List the addon domains.
     *
     * This function lists the cPanel account's addon domains: the domains that are parked on a subdomain
     * of the account's primary domain, rather than on the primary domain itself.
     *
     * @param  string|null  $regex  A Perl regular expression.
     * @param  bool|int|null  $returnHttpsRedirectStatus  Whether to include the `can_https_redirect` and `is_https_redirecting` fields in each entry.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/addondomain/addondomain-listaddondomains
     */
    public function listaddondomains(
        ?string $regex = null,
        bool|int|null $returnHttpsRedirectStatus = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('listaddondomains', [
            'regex' => $regex,
            'return_https_redirect_status' => $returnHttpsRedirectStatus,
        ], $extra);
    }
}
