<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI BackupInfo module (3 functions), run as one cPanel account through WHM.
 */
final class BackupInfo extends UapiModule
{
    public const string MODULE = 'BackupInfo';

    /**
     * Return cPanel account backups.
     *
     * This function returns one entry for each cPanel account backup archive in the current cPanel
     * account's home directory.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/backupinfo/backupinfo-list
     */
    public function list(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list', [], $extra);
    }

    /**
     * Return account backup progress.
     *
     * This function returns progress information for a cPanel account backup.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/backupinfo/backupinfo-progress
     */
    public function progress(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('progress', [], $extra);
    }

    /**
     * Remove backup progress record.
     *
     * This function clears the authoritative run-state record, so that the `BackupInfo::progress` function
     * stops reporting a `complete` state that persists across polls.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/backupinfo/backupinfo-reset
     */
    public function reset(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('reset', [], $extra);
    }
}
