<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI CCS module (5 functions), run as one cPanel account through WHM.
 */
final class Ccs extends UapiModule
{
    public const string MODULE = 'CCS';

    /**
     * Add calendar delegation.
     *
     * This function delegates a user's calendar to another user.
     *
     * @param  string  $delegatee  The user to whom you wish to delegate the calendar.
     * @param  string  $delegator  The calendar's owner.
     * @param  bool|int|null  $readonly  Whether the delegatee will only have read-only access on the calendar.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/ccs/ccs-add_delegate
     */
    public function addDelegate(
        string $delegatee,
        string $delegator,
        bool|int|null $readonly = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('add_delegate', [
            'delegatee' => $delegatee,
            'delegator' => $delegator,
            'readonly' => $readonly,
        ], $extra);
    }

    /**
     * List cPanel account's calendar delegates.
     *
     * This function lists all calendar delegates on the cPanel account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/ccs/ccs-list_delegates
     */
    public function listDelegates(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_delegates', [], $extra);
    }

    /**
     * List cPanel account's calendar users.
     *
     * This function lists all calendar users on the cPanel account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/ccs/ccs-list_users
     */
    public function listUsers(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_users', [], $extra);
    }

    /**
     * Remove calendar delegation.
     *
     * This function removes a delegate from another user's calendar.
     *
     * @param  string  $delegatee  The user from whom you wish to remove delegation rights.
     * @param  string  $delegator  The calendar's owner.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/ccs/ccs-remove_delegate
     */
    public function removeDelegate(
        string $delegatee,
        string $delegator,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('remove_delegate', [
            'delegatee' => $delegatee,
            'delegator' => $delegator,
        ], $extra);
    }

    /**
     * Update calendar delegation.
     *
     * This function updates the delegation of a user's calendar to another user.
     *
     * @param  string  $delegatee  The user to whom you delegated the calendar.
     * @param  string  $delegator  The calendar's owner.
     * @param  int|null  $readonly  Whether the delegatee will only have read-only access on the calendar.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/ccs/ccs-update_delegate
     */
    public function updateDelegate(
        string $delegatee,
        string $delegator,
        ?int $readonly = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('update_delegate', [
            'delegatee' => $delegatee,
            'delegator' => $delegator,
            'readonly' => $readonly,
        ], $extra);
    }
}
