<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI Chkservd module (2 functions), run as one cPanel account through WHM.
 */
final class Chkservd extends UapiModule
{
    public const string MODULE = 'Chkservd';

    /**
     * Return outgoing (SMTP) mail port.
     *
     * This function lists the ports on which Exim listens.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/chkservd/chkservd-get_exim_ports
     */
    public function getEximPorts(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_exim_ports', [], $extra);
    }

    /**
     * Return outgoing mail (SMTP) SSL-secured port.
     *
     * This function retrieves Exim's SSL port.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/chkservd/chkservd-get_exim_ports_ssl
     */
    public function getEximPortsSsl(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_exim_ports_ssl', [], $extra);
    }
}
