<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI ClamScanner module (5 functions), run as one cPanel account through WHM.
 */
final class ClamScanner extends UapiModule
{
    public const string MODULE = 'ClamScanner';

    /**
     * Request disinfection process status.
     *
     * This function checks the status of the previously queued disinfection of infected files.
     *
     * @param  int|null  $lastId  The unique `id` of the message you last received from this same log.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/clamscanner/clamscanner-check_disinfection_status
     */
    public function checkDisinfectionStatus(
        ?int $lastId = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('check_disinfection_status', [
            'last_id' => $lastId,
        ], $extra);
    }

    /**
     * Return virus scan types.
     *
     * This function gets the available local paths that a cPanel account is permitted to scan.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/clamscanner/clamscanner-get_scan_paths
     */
    public function getScanPaths(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_scan_paths', [], $extra);
    }

    /**
     * Request virus scan status.
     *
     * This function gets the status of a ClamAV scan on a directory.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/clamscanner/clamscanner-get_scan_status
     */
    public function getScanStatus(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_scan_status', [], $extra);
    }

    /**
     * Return infected file list.
     *
     * This function lists infected files from a ClamAV virus scan.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/clamscanner/clamscanner-list_infected_files
     */
    public function listInfectedFiles(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_infected_files', [], $extra);
    }

    /**
     * Start virus scan.
     *
     * This function starts a ClamAV scan on a directory.
     *
     * @param  string  $scanType  The type of directory to scan.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/clamscanner/clamscanner-start_scan
     */
    public function startScan(
        string $scanType,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('start_scan', [
            'scan_type' => $scanType,
        ], $extra);
    }
}
