<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;
use SensitiveParameter;

/**
 * UAPI ContactInformation module (5 functions), run as one cPanel account through WHM.
 */
final class ContactInformation extends UapiModule
{
    public const string MODULE = 'ContactInformation';

    /**
     * Return the account's notification preferences.
     *
     * Use this function to get a cPanel or Webmail account's notification preferences.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/contactinformation/contactinformation-get_notification_preferences
     */
    public function getNotificationPreferences(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_notification_preferences', [], $extra);
    }

    /**
     * Return Pushbullet access token.
     *
     * This function retrieves the cPanel account's Pushbullet access token.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/contactinformation/contactinformation-get_pushbullet_access_token
     */
    public function getPushbulletAccessToken(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_pushbullet_access_token', [], $extra);
    }

    /**
     * Set contact email address(es).
     *
     * Use this function to set an account's contact email address(es).
     *
     * @param  array<array-key, mixed>  $address  The account’s new contact email addresses.
     * @param  array<array-key, mixed>  $oldAddress  The account’s existing contact email addresses.
     * @param  string  $password  The account’s password.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/contactinformation/contactinformation-set_email_addresses
     */
    public function setEmailAddresses(
        array $address,
        array $oldAddress,
        #[SensitiveParameter] string $password,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_email_addresses', [
            'address' => $address,
            'old_address' => $oldAddress,
            'password' => $password,
        ], $extra);
    }

    /**
     * Update Pushbullet access token.
     *
     * This function updates the cPanel account's Pushbullet access token.
     *
     * @param  string  $pushbulletAccessToken  The account’s new Pushbullet access token.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/contactinformation/contactinformation-set_pushbullet_access_token
     */
    public function setPushbulletAccessToken(
        #[SensitiveParameter] string $pushbulletAccessToken,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_pushbullet_access_token', [
            'pushbullet_access_token' => $pushbulletAccessToken,
        ], $extra);
    }

    /**
     * Unset contact email addresses.
     *
     * Use this function to unset all contact email address for an account.
     *
     * @param  array<array-key, mixed>  $oldAddress  The account’s existing contact email addresses.
     * @param  string  $password  The account’s password.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/contactinformation/contactinformation-unset_email_addresses
     */
    public function unsetEmailAddresses(
        array $oldAddress,
        #[SensitiveParameter] string $password,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('unset_email_addresses', [
            'old_address' => $oldAddress,
            'password' => $password,
        ], $extra);
    }
}
