<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI CSVImport module (1 functions), run as one cPanel account through WHM.
 */
final class CsvImport extends UapiModule
{
    public const string MODULE = 'CSVImport';

    /**
     * Import email accounts from CSV file.
     *
     * This function imports email accounts from an already uploaded CSV file.
     *
     * @param  string  $domain  The domain under which to add the email accounts.
     * @param  string  $id  The unique ID of the import operation.
     * @param  string  $type  The type of email address to add.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/csvimport/csvimport-doimport
     */
    public function doimport(
        string $domain,
        string $id,
        string $type,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('doimport', [
            'domain' => $domain,
            'id' => $id,
            'type' => $type,
        ], $extra);
    }
}
