<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI DCV module (3 functions), run as one cPanel account through WHM.
 */
final class Dcv extends UapiModule
{
    public const string MODULE = 'DCV';

    /**
     * Verify domain ownership via DNS.
     *
     * This function checks whether the account's domains can pass Domain Control Validation (DCV) via a
     * DNS request.
     *
     * @param  string  $domain  The domain or domains to check.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/dcv/dcv-check_domains_via_dns
     */
    public function checkDomainsViaDns(
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('check_domains_via_dns', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Verify domain ownership via HTTP.
     *
     * This function checks whether the account's domains can pass Domain Control Validation (DCV) via an
     * HTTP request.
     *
     * @param  string  $domain  The domains to check.
     * @param  array<array-key, mixed>|null  $dcvFileAllowedCharacters  An array of characters that the certificate provider allows in the DCV check file's filename.
     * @param  string|null  $dcvFileExtension  The DCV check file extension that the certificate provider requires.
     * @param  int|null  $dcvFileRandomCharacterCount  The number of characters that the certificate provider allows in the DCV check file's filename.
     * @param  string|null  $dcvFileRelativePath  The DCV check file's file path, relative to the domain's document `root` directory.
     * @param  int|null  $dcvMaxRedirects  The number of domain redirects the system permits the DCV check to follow.
     * @param  string|null  $dcvUserAgentString  The user agent string that the system uses for the imitated local DCV check.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/dcv/dcv-check_domains_via_http
     */
    public function checkDomainsViaHttp(
        string $domain,
        ?array $dcvFileAllowedCharacters = null,
        ?string $dcvFileExtension = null,
        ?int $dcvFileRandomCharacterCount = null,
        ?string $dcvFileRelativePath = null,
        ?int $dcvMaxRedirects = null,
        ?string $dcvUserAgentString = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('check_domains_via_http', [
            'domain' => $domain,
            'dcv_file_allowed_characters' => $dcvFileAllowedCharacters,
            'dcv_file_extension' => $dcvFileExtension,
            'dcv_file_random_character_count' => $dcvFileRandomCharacterCount,
            'dcv_file_relative_path' => $dcvFileRelativePath,
            'dcv_max_redirects' => $dcvMaxRedirects,
            'dcv_user_agent_string' => $dcvUserAgentString,
        ], $extra);
    }

    /**
     * Verify domain ownership.
     *
     * This function indicates whether the account's domains can pass a Domain Control Validation (DCV)
     * check.
     *
     * @param  string  $domain  The domains to check.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @deprecated cPanel has deprecated this function.
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/dcv/dcv-ensure_domains_can_pass_dcv
     */
    public function ensureDomainsCanPassDcv(
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('ensure_domains_can_pass_dcv', [
            'domain' => $domain,
        ], $extra);
    }
}
