<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI DNS module (11 functions), run as one cPanel account through WHM.
 */
final class Dns extends UapiModule
{
    public const string MODULE = 'DNS';

    /**
     * Return whether domains only resolve locally.
     *
     * This function indicates whether the account's domains resolve exclusively to this server.
     *
     * @param  string  $domain  The domain to check.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-ensure_domains_reside_only_locally
     */
    public function ensureDomainsResideOnlyLocally(
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('ensure_domains_reside_only_locally', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Return whether domains use recognized nameservers.
     *
     * This function indicates whether the account's domains' nameservers resolve to an IP address that
     * this server recognizes as its own. It predicts the outcome of the create-time nameserver validation
     * that runs when a domain is added to the account, without performing any privileged action.
     *
     * @param  string  $domain  The domain to check.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-ensure_domains_use_recognized_nameservers
     */
    public function ensureDomainsUseRecognizedNameservers(
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('ensure_domains_use_recognized_nameservers', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Retrieve cPanel-generated subdomains for a domain.
     *
     * This function retrieves the list of subdomains that cPanel automatically generates for a given
     * domain. These include proxy subdomains such as `webmail`, `mail`, and `cpanel`, as well as other
     * system-generated domain names.
     *
     * @param  string  $domain  The domain for which to retrieve cPanel-generated subdomains.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-fetch_cpanel_generated_domains
     */
    public function fetchCpanelGeneratedDomains(
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('fetch_cpanel_generated_domains', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Return whether local DNS server is authoritative.
     *
     * This function checks whether the local server is authoritative for the domain's DNS records.
     *
     * @param  string  $domain  The domain to check whether the local server is authoritative for the domain's DNS records.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-has_local_authority
     */
    public function hasLocalAuthority(
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('has_local_authority', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Return `ALIAS` DNS record availability & resolver.
     *
     * This function returns whether `ALIAS` and `ANAME` records are available and the value of the running
     * PowerDNS (PDNS) `resolver` setting, if any exists. For more information, read our `ALIAS`
     * documentation.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-is_alias_available
     */
    public function isAliasAvailable(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('is_alias_available', [], $extra);
    }

    /**
     * Return DNS HTTPS record support information.
     *
     * This function fetches information regarding HTTPS records support. HTTPS records are defined in RFC
     * 9460 and provide service parameters for HTTPS endpoints. For more information, read our Zone Editor
     * documentation.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-is_https_available
     */
    public function isHttpsAvailable(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('is_https_available', [], $extra);
    }

    /**
     * Return DNS SVCB record support information.
     *
     * This function fetches information regarding SVCB records support. SVCB records are defined in RFC
     * 9460 and provide service binding and aliasing for arbitrary services. For more information, read our
     * Zone Editor documentation.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-is_svcb_available
     */
    public function isSvcbAvailable(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('is_svcb_available', [], $extra);
    }

    /**
     * Return domain's DNS information.
     *
     * This function returns DNS zone information about a domain.
     *
     * @param  string  $domain  A fully qualified domain name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-lookup
     */
    public function lookup(
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('lookup', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Update a DNS zone.
     *
     * This function updates a DNS zone by allowing multiple records to be added, modified, or removed in a
     * single call. It also ensures modified records occupy the same number of lines as before the edit.
     *
     * @param  int  $serial  The current serial number in the DNS zone’s SOA (Start of Authority) record.
     * @param  string  $zone  The name of one of the user’s DNS zones.
     * @param  array<array-key, mixed>|null  $add  The records to add to the zone.
     * @param  array<array-key, mixed>|null  $edit  The records to edit in the zone.
     * @param  array<array-key, mixed>|null  $remove  The line indexes of records to remove from the zone.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-mass_edit_zone
     */
    public function massEditZone(
        int $serial,
        string $zone,
        ?array $add = null,
        ?array $edit = null,
        ?array $remove = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('mass_edit_zone', [
            'serial' => $serial,
            'zone' => $zone,
            'add' => $add,
            'edit' => $edit,
            'remove' => $remove,
        ], $extra);
    }

    /**
     * Return a parsed DNS zone.
     *
     * This function parses a given DNS zone.
     *
     * @param  string  $zone  The name of one of the user’s DNS zones.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/dns-information/dns-parse_zone
     */
    public function parseZone(
        string $zone,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('parse_zone', [
            'zone' => $zone,
        ], $extra);
    }

    /**
     * Update IP addresses in zone files.
     *
     * This function replaces a domain's IPv4 address in the DNS zone file with the specified destination
     * IPv4 address.
     *
     * @param  string  $destIp  The IPv4 address to use as the replacement in the zone files.
     * @param  string  $domain  The domain to perform the zone file updates on.
     * @param  string|null  $ftpIp  The IPv4 address to use as the replacement for FTP records in the zone files.
     * @param  string|null  $sourceIp  The IPv4 address to replace in the zone files.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/dns/dns-swap_ip_in_zones
     */
    public function swapIpInZones(
        string $destIp,
        string $domain,
        ?string $ftpIp = null,
        ?string $sourceIp = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('swap_ip_in_zones', [
            'dest_ip' => $destIp,
            'domain' => $domain,
            'ftp_ip' => $ftpIp,
            'source_ip' => $sourceIp,
        ], $extra);
    }
}
