<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI DomainRecommendations module (6 functions), run as one cPanel account through WHM.
 */
final class DomainRecommendations extends UapiModule
{
    public const string MODULE = 'DomainRecommendations';

    /**
     * Check whether a domain is available for registration.
     *
     * This function checks whether a specific domain name is available for registration through the
     * configured domain store.
     *
     * @param  string  $domain  The fully-qualified domain name (FQDN) to check for availability.
     * @param  bool|int|null  $useCache  Whether to use the local response cache.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/domainrecommendations/domainrecommendations-domain_availability
     */
    public function domainAvailability(
        string $domain,
        bool|int|null $useCache = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('domain_availability', [
            'domain' => $domain,
            'use_cache' => $useCache,
        ], $extra);
    }

    /**
     * Search for available domain names and pricing.
     *
     * This function returns available domain name suggestions and their registration pricing for a given
     * search term.
     *
     * @param  string  $searchField  The search term used to generate domain suggestions.
     * @param  int|null  $page  The page number to retrieve (1-indexed).
     * @param  int|null  $pageSize  The number of suggestions to return per page.
     * @param  bool|int|null  $useCache  Whether to use the local response cache.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/domainrecommendations/domainrecommendations-domain_suggestions
     */
    public function domainSuggestions(
        string $searchField,
        ?int $page = null,
        ?int $pageSize = null,
        bool|int|null $useCache = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('domain_suggestions', [
            'search_field' => $searchField,
            'page' => $page,
            'page_size' => $pageSize,
            'use_cache' => $useCache,
        ], $extra);
    }

    /**
     * Retrieve the sanitized domain store configuration.
     *
     * This function returns the allowlisted store configuration for the Domain Recommendations feature.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/domainrecommendations/domainrecommendations-get_store_config
     */
    public function getStoreConfig(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_store_config', [], $extra);
    }

    /**
     * Check whether Domain Recommendations is enabled.
     *
     * This function returns the enablement status of the Domain Recommendations feature on the server.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/domainrecommendations/domainrecommendations-is_enabled
     */
    public function isEnabled(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('is_enabled', [], $extra);
    }

    /**
     * Get a URL to purchase a domain.
     *
     * This function returns a URL for the configured domain store's checkout page. This URL allows the
     * user to complete the purchase of a domain name.
     *
     * @param  string  $domain  The fully-qualified domain name (FQDN) to purchase.
     * @param  int  $period  The registration period in years.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/domainrecommendations/domainrecommendations-purchase_domain
     */
    public function purchaseDomain(
        string $domain,
        int $period,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('purchase_domain', [
            'domain' => $domain,
            'period' => $period,
        ], $extra);
    }

    /**
     * List the TLDs supported by the domain store.
     *
     * This function returns the list of top-level domains (TLDs) that the configured domain store supports
     * for registration.
     *
     * @param  bool|int|null  $useCache  Whether to use the local response cache.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/domainrecommendations/domainrecommendations-supported_tlds
     */
    public function supportedTlds(
        bool|int|null $useCache = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('supported_tlds', [
            'use_cache' => $useCache,
        ], $extra);
    }
}
