<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI Domain module (4 functions), run as one cPanel account through WHM.
 */
final class Domain extends UapiModule
{
    public const string MODULE = 'Domain';

    /**
     * Convert a temporary domain to a registered domain.
     *
     * This function converts a temporary domain into a registered domain and moves its document root files
     * to the new document root location.
     *
     * @param  string  $domain  A valid temporary domain on the account.
     * @param  string  $registered  A valid domain name.
     * @param  string|null  $docroot  The path to the domain's document root directory.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/temporary-domains/domain-convert_temporary_to_registered
     */
    public function convertTemporaryToRegistered(
        string $domain,
        string $registered,
        ?string $docroot = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('convert_temporary_to_registered', [
            'domain' => $domain,
            'registered' => $registered,
            'docroot' => $docroot,
        ], $extra);
    }

    /**
     * Return whether a domain is temporary.
     *
     * This function determines whether a domain is temporary.
     *
     * @param  string  $domain  A domain on the cPanel account.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/temporary-domains/domain-is_temporary_domain
     */
    public function isTemporaryDomain(
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('is_temporary_domain', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Rename a primary, addon, or alias domain.
     *
     * This function renames a primary domain, addon domain, or alias domain on a cPanel account. The
     * system updates all relevant configuration files, document root paths, and DNS entries automatically.
     *
     * @param  string  $domain  The current domain name to rename.
     * @param  string  $newDomain  The new domain name.
     * @param  string|null  $docroot  The path to the domain's document root directory.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/domain/domain-rename_domain
     */
    public function renameDomain(
        string $domain,
        string $newDomain,
        ?string $docroot = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('rename_domain', [
            'domain' => $domain,
            'new_domain' => $newDomain,
            'docroot' => $docroot,
        ], $extra);
    }

    /**
     * Return whether temporary domains are disabled.
     *
     * This function returns whether the temporary domains feature is disabled by server configuration.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/temporary-domains/domain-temporary_domain_is_disabled
     */
    public function temporaryDomainIsDisabled(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('temporary_domain_is_disabled', [], $extra);
    }
}
