<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI DomainLookup module (4 functions), run as one cPanel account through WHM.
 */
final class DomainLookup extends UapiModule
{
    public const string MODULE = 'DomainLookup';

    /**
     * Count the domains that have their own DNS zone.
     *
     * This function counts the cPanel account's base domains: the primary domain, its addon domains and
     * its parked domains.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/domainlookup/domainlookup-countbasedomains
     */
    public function countbasedomains(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('countbasedomains', [], $extra);
    }

    /**
     * List the domains that have their own DNS zone.
     *
     * This function lists the cPanel account's base domains: the primary domain, its addon domains and its
     * parked domains.
     *
     * @param  bool|int|null  $returnTemporaryDomain  Whether to include the account's temporary domains in the result.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/domainlookup/domainlookup-getbasedomains
     */
    public function getbasedomains(
        bool|int|null $returnTemporaryDomain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('getbasedomains', [
            'return_temporary_domain' => $returnTemporaryDomain,
        ], $extra);
    }

    /**
     * Return a domain's document root.
     *
     * This function retrieves the document root for a single domain on the cPanel account.
     *
     * @param  string|null  $domain  The domain to look up.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/domainlookup/domainlookup-getdocroot
     */
    public function getdocroot(
        ?string $domain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('getdocroot', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Return every domain's document root.
     *
     * This function retrieves the document root for every domain on the cPanel account, including the
     * primary domain, addon domains, parked domains and subdomains.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/domainlookup/domainlookup-getdocroots
     */
    public function getdocroots(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('getdocroots', [], $extra);
    }
}
