<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI EA4 module (2 functions), run as one cPanel account through WHM.
 */
final class Ea4 extends UapiModule
{
    public const string MODULE = 'EA4';

    /**
     * Get custom PHP recommendations.
     *
     * This function returns a list of recommended PHP versions.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/php/ea4-get_php_recommendations
     */
    public function getPhpRecommendations(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_php_recommendations', [], $extra);
    }

    /**
     * Get EA4 configuration recommendations.
     *
     * This function retrieves a list of EasyApache 4 (EA4) configuration recommendations.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/ea4/ea4-get_recommendations
     */
    public function getRecommendations(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_recommendations', [], $extra);
    }
}
