<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;
use SensitiveParameter;

/**
 * UAPI Email module (96 functions), run as one cPanel account through WHM.
 */
final class Email extends UapiModule
{
    public const string MODULE = 'Email';

    /**
     * Return current user's account name.
     *
     * This function returns the provided value. This function works with other functions to display form
     * data within a user interface.
     *
     * @param  string|null  $account  The function will return this value in the data return.
     * @param  string|null  $display  Include this parameter to cause the function to return `All Mail On The Account` if the account parameter is blank or does not exist.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-account_name
     */
    public function accountName(
        ?string $account = null,
        ?string $display = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('account_name', [
            'account' => $account,
            'display' => $display,
        ], $extra);
    }

    /**
     * Create email account's autoresponder.
     *
     * This function creates an autoresponder for an email account.
     *
     * @param  string  $body  The contents of the autoresponder message's `Body` section.
     * @param  string  $domain  The email account's domain.
     * @param  string  $email  The email account name.
     * @param  string  $from  The contents of the autoresponder message's `From:` field.
     * @param  int  $interval  The amount of time, in hours, that the server waits between autoresponder messages to the same address.
     * @param  bool|int  $isHtml  Whether the body of the autoresponder message begins with an HTML Content-Type declaration.
     * @param  int  $start  When to enable the autoresponder.
     * @param  int  $stop  When to disable the autoresponder.
     * @param  string  $subject  The contents of the autoresponder message's `Subject:` field.
     * @param  string|null  $charset  The character set.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-add_auto_responder
     */
    public function addAutoResponder(
        string $body,
        string $domain,
        string $email,
        string $from,
        int $interval,
        bool|int $isHtml,
        int $start,
        int $stop,
        string $subject,
        ?string $charset = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('add_auto_responder', [
            'body' => $body,
            'domain' => $domain,
            'email' => $email,
            'from' => $from,
            'interval' => $interval,
            'is_html' => $isHtml,
            'start' => $start,
            'stop' => $stop,
            'subject' => $subject,
            'charset' => $charset,
        ], $extra);
    }

    /**
     * Create domain-level forwarder.
     *
     * This function creates a domain-level forwarder.
     *
     * @param  string  $destdomain  The domain to receive forwarded mail.
     * @param  string  $domain  The domain on the cPanel account from which to forward mail.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-forwarding/email-add_domain_forwarder
     */
    public function addDomainForwarder(
        string $destdomain,
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('add_domain_forwarder', [
            'destdomain' => $destdomain,
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Create email account forwarder.
     *
     * This function creates an email forwarder.
     *
     * @param  string  $domain  The domain.
     * @param  string  $email  The email address to forward.
     * @param  string  $fwdopt  The method to use to handle the email address's mail.
     * @param  string|null  $failmsgs  The failure message for the message's sender.
     * @param  string|null  $fwdemail  The email address to which the system forwards messages.
     * @param  string|null  $fwdsystem  The system user to whom the system forwards messages.
     * @param  string|null  $pipefwd  The application to which the system pipes messages.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-forwarding/email-add_forwarder
     */
    public function addForwarder(
        string $domain,
        string $email,
        string $fwdopt,
        ?string $failmsgs = null,
        ?string $fwdemail = null,
        ?string $fwdsystem = null,
        ?string $pipefwd = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('add_forwarder', [
            'domain' => $domain,
            'email' => $email,
            'fwdopt' => $fwdopt,
            'failmsgs' => $failmsgs,
            'fwdemail' => $fwdemail,
            'fwdsystem' => $fwdsystem,
            'pipefwd' => $pipefwd,
        ], $extra);
    }

    /**
     * Create mailing list.
     *
     * This function creates a Mailman mailing list.
     *
     * @param  string  $domain  The domain.
     * @param  string  $list  The mailing list name.
     * @param  string  $password  The mailing list password.
     * @param  bool|int|null  $private  Whether the mailing list is private.
     * @param  bool|int|null  $rebuildonly  Whether to rebuild the mailing list.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/mailing-lists/email-add_list
     */
    public function addList(
        string $domain,
        string $list,
        #[SensitiveParameter] string $password,
        bool|int|null $private = null,
        bool|int|null $rebuildonly = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('add_list', [
            'domain' => $domain,
            'list' => $list,
            'password' => $password,
            'private' => $private,
            'rebuildonly' => $rebuildonly,
        ], $extra);
    }

    /**
     * Add administrators to mailing list.
     *
     * This function grants mailing list administrative privileges to users.
     *
     * @param  string  $delegates  A list of the administrators to add.
     * @param  string  $list  The mailing list.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/mailing-lists/email-add_mailman_delegates
     */
    public function addMailmanDelegates(
        string $delegates,
        string $list,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('add_mailman_delegates', [
            'delegates' => $delegates,
            'list' => $list,
        ], $extra);
    }

    /**
     * Create mail exchanger record.
     *
     * This function creates a Mail Exchanger (MX) record. For more information about MX record settings,
     * read our Email Routing Configuration documentation.
     *
     * @param  string  $domain  The new mail exchanger's domain.
     * @param  string  $exchanger  The new mail exchanger's name.
     * @param  int  $priority  The new mail exchanger's priority value.
     * @param  bool|int|null  $alwaysaccept  Whether the mail exchanger accepts all mail for the domain.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-dns-settings/email-add_mx
     */
    public function addMx(
        string $domain,
        string $exchanger,
        int $priority,
        bool|int|null $alwaysaccept = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('add_mx', [
            'domain' => $domain,
            'exchanger' => $exchanger,
            'priority' => $priority,
            'alwaysaccept' => $alwaysaccept,
        ], $extra);
    }

    /**
     * Create email account.
     *
     * This function creates an email address.
     *
     * @param  string  $email  The email account username or address.
     * @param  string  $password  The email account password.
     * @param  string|null  $domain  The email account's domain.
     * @param  string|null  $passwordHash  The account's password hash.
     * @param  int|string|null  $quota  The maximum amount of disk space that the new email account may use.
     * @param  bool|int|null  $sendWelcomeEmail  Whether to send client configuration instructions to the account.
     * @param  bool|int|null  $skipUpdateDb  Whether to skip the update of the email accounts database's cache.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-add_pop
     */
    public function addPop(
        string $email,
        #[SensitiveParameter] string $password,
        ?string $domain = null,
        #[SensitiveParameter] ?string $passwordHash = null,
        int|string|null $quota = null,
        bool|int|null $sendWelcomeEmail = null,
        bool|int|null $skipUpdateDb = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('add_pop', [
            'email' => $email,
            'password' => $password,
            'domain' => $domain,
            'password_hash' => $passwordHash,
            'quota' => $quota,
            'send_welcome_email' => $sendWelcomeEmail,
            'skip_update_db' => $skipUpdateDb,
        ], $extra);
    }

    /**
     * Update minimum spam score threshold value.
     *
     * This function sets a new minimum Apache SpamAssassin spam score threshold value.
     *
     * @param  string|null  $account  The email account to apply a spam score threshold value.
     * @param  string|null  $requiredScore  Set a spam score threshold value.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-management/email-add_spam_filter
     */
    public function addSpamFilter(
        ?string $account = null,
        ?string $requiredScore = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('add_spam_filter', [
            'account' => $account,
            'required_score' => $requiredScore,
        ], $extra);
    }

    /**
     * Return mail directory's subdirectories and files.
     *
     * This function lists the mail directory's subdirectories (boxes) and files.
     *
     * @param  string|null  $account  An email address, to limit the function's results.
     * @param  string|null  $dir  A mail directory name, to limit results to specific directories.
     * @param  bool|int|null  $showdotfiles  Whether to include hidden files and directories.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-browse_mailbox
     */
    public function browseMailbox(
        ?string $account = null,
        ?string $dir = null,
        bool|int|null $showdotfiles = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('browse_mailbox', [
            'account' => $account,
            'dir' => $dir,
            'showdotfiles' => $showdotfiles,
        ], $extra);
    }

    /**
     * Update mail exchanger record.
     *
     * This function creates a Mail Exchanger (MX) record. For more information about MX record settings,
     * read our Email Routing Configuration documentation.
     *
     * @param  string  $domain  The mail exchanger's domain.
     * @param  string  $exchanger  The mail exchanger's name.
     * @param  string  $oldexchanger  The mail exchanger's current name.
     * @param  int  $priority  The mail exchanger's new priority value.
     * @param  bool|int|null  $alwaysaccept  Whether the mail exchanger accepts all mail for the domain.
     * @param  int|null  $oldpriority  The mail exchanger's current priority value.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-dns-settings/email-change_mx
     */
    public function changeMx(
        string $domain,
        string $exchanger,
        string $oldexchanger,
        int $priority,
        bool|int|null $alwaysaccept = null,
        ?int $oldpriority = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('change_mx', [
            'domain' => $domain,
            'exchanger' => $exchanger,
            'oldexchanger' => $oldexchanger,
            'priority' => $priority,
            'alwaysaccept' => $alwaysaccept,
            'oldpriority' => $oldpriority,
        ], $extra);
    }

    /**
     * Return BlackBerry FastMail support status.
     *
     * This function checks whether BlackBerry FastMail support is enabled.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-server-information/email-check_fastmail
     */
    public function checkFastmail(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('check_fastmail', [], $extra);
    }

    /**
     * Return cPanel account's autoresponders total.
     *
     * This function returns the number of autoresponders for every email address on a cPanel account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-count_auto_responders
     */
    public function countAutoResponders(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('count_auto_responders', [], $extra);
    }

    /**
     * Return cPanel account's email filters total.
     *
     * This function returns the number of email filters for every email address on a cPanel account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-filtering/email-count_filters
     */
    public function countFilters(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('count_filters', [], $extra);
    }

    /**
     * Return cPanel account's mail forwarder total.
     *
     * This function returns the number of forwarders for every email address on a cPanel account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-forwarding/email-count_forwarders
     */
    public function countForwarders(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('count_forwarders', [], $extra);
    }

    /**
     * Return cPanel account's mailing list total.
     *
     * This function returns the number of mailing lists for every email address on a cPanel account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/mailing-lists/email-count_lists
     */
    public function countLists(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('count_lists', [], $extra);
    }

    /**
     * Return cPanel account's email account total.
     *
     * This function returns the number of email accounts for a cPanel account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-count_pops
     */
    public function countPops(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('count_pops', [], $extra);
    }

    /**
     * Delete email account's autoresponder.
     *
     * This function deletes an autoresponder.
     *
     * @param  string  $email  The email account.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-delete_auto_responder
     */
    public function deleteAutoResponder(
        string $email,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('delete_auto_responder', [
            'email' => $email,
        ], $extra);
    }

    /**
     * Delete domain-level forwarder.
     *
     * This function deletes a domain-level forwarder.
     *
     * @param  string  $domain  The domain name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-forwarding/email-delete_domain_forwarder
     */
    public function deleteDomainForwarder(
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('delete_domain_forwarder', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Delete email account's email filter.
     *
     * This function deletes an email filter.
     *
     * @param  string  $account  The email address that owns the filter.
     * @param  string  $filtername  The filter's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-filtering/email-delete_filter
     */
    public function deleteFilter(
        string $account,
        string $filtername,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('delete_filter', [
            'account' => $account,
            'filtername' => $filtername,
        ], $extra);
    }

    /**
     * Delete email account's email forwarder.
     *
     * This function deletes an email forwarder.
     *
     * @param  string  $address  The forwarder's email address.
     * @param  string  $forwarder  The forwarder's destination.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-forwarding/email-delete_forwarder
     */
    public function deleteForwarder(
        string $address,
        string $forwarder,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('delete_forwarder', [
            'address' => $address,
            'forwarder' => $forwarder,
        ], $extra);
    }

    /**
     * Delete email account's outgoing messages.
     *
     * This function deletes all outbound email messages held in the mail queue for the specified email
     * account.
     *
     * @param  string  $email  The email address to query.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-delete_held_messages
     */
    public function deleteHeldMessages(
        string $email,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('delete_held_messages', [
            'email' => $email,
        ], $extra);
    }

    /**
     * Delete mailing list.
     *
     * This function deletes a Mailman mailing list.
     *
     * @param  string  $list  The mailing list.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/mailing-lists/email-delete_list
     */
    public function deleteList(
        string $list,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('delete_list', [
            'list' => $list,
        ], $extra);
    }

    /**
     * Delete mail exchanger record.
     *
     * This function deletes a Mail Exchanger (MX) record. For more information about MX record settings,
     * read our Email Routing Configuration documentation.
     *
     * @param  string  $domain  The mail exchanger's domain.
     * @param  string  $exchanger  The mail exchanger's name.
     * @param  int  $priority  The mail exchanger's priority value.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-dns-settings/email-delete_mx
     */
    public function deleteMx(
        string $domain,
        string $exchanger,
        int $priority,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('delete_mx', [
            'domain' => $domain,
            'exchanger' => $exchanger,
            'priority' => $priority,
        ], $extra);
    }

    /**
     * Delete email account.
     *
     * This function deletes an email address.
     *
     * @param  string  $email  The email account username or address.
     * @param  string|null  $domain  The email account's domain.
     * @param  string|null  $flags  Whether to remove the mail account's home mail directory.
     * @param  bool|int|null  $skipQuota  Whether to modify the mail account's quota file.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-delete_pop
     */
    public function deletePop(
        string $email,
        ?string $domain = null,
        ?string $flags = null,
        bool|int|null $skipQuota = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('delete_pop', [
            'email' => $email,
            'domain' => $domain,
            'flags' => $flags,
            'skip_quota' => $skipQuota,
        ], $extra);
    }

    /**
     * Disable email filter for email account.
     *
     * This function disables an email filter.
     *
     * @param  string  $account  The email address that owns the filter.
     * @param  string  $filtername  The filter's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-filtering/email-disable_filter
     */
    public function disableFilter(
        string $account,
        string $filtername,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('disable_filter', [
            'account' => $account,
            'filtername' => $filtername,
        ], $extra);
    }

    /**
     * Disable cPanel account mailbox autocreation.
     *
     * This function disables the system's ability to automatically create mailboxes for a cPanel account.
     *
     * @param  string  $email  The email account address for which to disable mailbox autocreation.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-server-information/email-disable_mailbox_autocreate
     */
    public function disableMailboxAutocreate(
        string $email,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('disable_mailbox_autocreate', [
            'email' => $email,
        ], $extra);
    }

    /**
     * Disable Apache SpamAssassin for cPanel account.
     *
     * This function disables Apache SpamAssassin for a cPanel account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-management/email-disable_spam_assassin
     */
    public function disableSpamAssassin(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('disable_spam_assassin', [], $extra);
    }

    /**
     * Disable spam box filtering auto-delete.
     *
     * This function disables the Apache SpamAssassin auto-delete spam feature.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-management/email-disable_spam_autodelete
     */
    public function disableSpamAutodelete(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('disable_spam_autodelete', [], $extra);
    }

    /**
     * Disable spam box filtering for cPanel account.
     *
     * This function disables spam box filtering for a cPanel account. When you disable spam box filtering,
     * the system sends all messages to the account's inbox.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-management/email-disable_spam_box
     */
    public function disableSpamBox(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('disable_spam_box', [], $extra);
    }

    /**
     * Send email client settings to an email address.
     *
     * This function sends an email account's client settings to an email address.
     *
     * @param  string  $account  The email account username or address for which to send client settings.
     * @param  string  $to  The email address to send client settings.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-dispatch_client_settings
     */
    public function dispatchClientSettings(
        string $account,
        string $to,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('dispatch_client_settings', [
            'account' => $account,
            'to' => $to,
        ], $extra);
    }

    /**
     * Update email account's quota.
     *
     * This function changes an email address's quota.
     *
     * @param  string  $domain  The email account's domain.
     * @param  string  $email  The email account username.
     * @param  string|null  $quota  The maximum amount of disk space that the new email account may use.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-edit_pop_quota
     */
    public function editPopQuota(
        string $domain,
        string $email,
        ?string $quota = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('edit_pop_quota', [
            'domain' => $domain,
            'email' => $email,
            'quota' => $quota,
        ], $extra);
    }

    /**
     * Enable email filter for email account.
     *
     * This function enables an email filter.
     *
     * @param  string  $account  The email address that owns the filter.
     * @param  string  $filtername  The filter's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-filtering/email-enable_filter
     */
    public function enableFilter(
        string $account,
        string $filtername,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('enable_filter', [
            'account' => $account,
            'filtername' => $filtername,
        ], $extra);
    }

    /**
     * Enable cPanel account mailbox autocreation.
     *
     * This function allows the system to automatically create mailboxes for a cPanel account. The system
     * will create a new mailbox when it receives an email address in plus address format and that mailbox
     * does not exist.
     *
     * @param  string  $email  The email account for which to enable mailbox autocreation.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-server-information/email-enable_mailbox_autocreate
     */
    public function enableMailboxAutocreate(
        string $email,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('enable_mailbox_autocreate', [
            'email' => $email,
        ], $extra);
    }

    /**
     * Enable Apache SpamAssassin for cPanel account.
     *
     * This function enables Apache SpamAssassin for the account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-management/email-enable_spam_assassin
     */
    public function enableSpamAssassin(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('enable_spam_assassin', [], $extra);
    }

    /**
     * Enable spam box filtering for cPanel account.
     *
     * This function enables spam box filtering for a cPanel account. When you enable spam box filtering,
     * the system sends messages marked as spam to a spam folder.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-management/email-enable_spam_box
     */
    public function enableSpamBox(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('enable_spam_box', [], $extra);
    }

    /**
     * Export cPanel account's Mailman mailing lists to a file.
     *
     * This function exports a cPanel account's Mailman mailing lists into a CSV file. This file is located
     * in mail/exported_lists under the user's home directory.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/mailing-lists/email-export_lists
     */
    public function exportLists(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('export_lists', [], $extra);
    }

    /**
     * Return server's supported character encodings.
     *
     * This function lists the available character encodings.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-server-information/email-fetch_charmaps
     */
    public function fetchCharmaps(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('fetch_charmaps', [], $extra);
    }

    /**
     * Start IMAP Full-Text Search scan for email account.
     *
     * This function requests that the IMAP Full-Text Search Indexing (powered by Apache Solr) plugin
     * rescan an email account.
     *
     * @param  string  $account  The email user's account name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-server-information/email-fts_rescan_mailbox
     */
    public function ftsRescanMailbox(
        string $account,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('fts_rescan_mailbox', [
            'account' => $account,
        ], $extra);
    }

    /**
     * Create one-time password for a mailing list.
     *
     * This function generates a one-time password (OTP) for a mailing list.
     *
     * @param  string  $list  The mailing list.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/mailing-lists/email-generate_mailman_otp
     */
    public function generateMailmanOtp(
        string $list,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('generate_mailman_otp', [
            'list' => $list,
        ], $extra);
    }

    /**
     * Return email account's autoresponder information.
     *
     * This function retrieves autoresponder information.
     *
     * @param  string  $email  The email account name.
     * @param  string|null  $tempCharset  The autoresponder's character set.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-get_auto_responder
     */
    public function getAutoResponder(
        string $email,
        ?string $tempCharset = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_auto_responder', [
            'email' => $email,
            'temp_charset' => $tempCharset,
        ], $extra);
    }

    /**
     * Return mail server's supported character encodings.
     *
     * This function lists character encodings that the mail server supports.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-server-information/email-get_charsets
     */
    public function getCharsets(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_charsets', [], $extra);
    }

    /**
     * Return email account's client settings.
     *
     * This function retrieves an email account's client settings.
     *
     * @param  string|null  $account  The email address for which to send client settings.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-get_client_settings
     */
    public function getClientSettings(
        ?string $account = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_client_settings', [
            'account' => $account,
        ], $extra);
    }

    /**
     * Return email account's default email quota.
     *
     * This function retrieves the account's default email quota size, in bytes format.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-get_default_email_quota
     */
    public function getDefaultEmailQuota(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_default_email_quota', [], $extra);
    }

    /**
     * Return email account's default email quota in MiB.
     *
     * This function retrieves the account's default email quota size in mebibytes (MiB).
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-get_default_email_quota_mib
     */
    public function getDefaultEmailQuotaMib(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_default_email_quota_mib', [], $extra);
    }

    /**
     * Return email account's disk usage.
     *
     * This function retrieves the disk space that an email account uses.
     *
     * @param  string  $domain  The email account's domain.
     * @param  string  $user  The email account username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-get_disk_usage
     */
    public function getDiskUsage(
        string $domain,
        string $user,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_disk_usage', [
            'domain' => $domain,
            'user' => $user,
        ], $extra);
    }

    /**
     * Return email filter's information.
     *
     * This function retrieves an email filter's information.
     *
     * @param  string  $account  The email address that owns the filter.
     * @param  string  $filtername  The filter's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-filtering/email-get_filter
     */
    public function getFilter(
        string $account,
        string $filtername,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_filter', [
            'account' => $account,
            'filtername' => $filtername,
        ], $extra);
    }

    /**
     * Return email account's outgoing message count.
     *
     * This function returns the count of outbound email messages held in the mail queue for the specified
     * email account.
     *
     * @param  string|null  $email  The email address to query.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-get_held_message_count
     */
    public function getHeldMessageCount(
        ?string $email = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_held_message_count', [
            'email' => $email,
        ], $extra);
    }

    /**
     * Return cPanel account's mailing list disk usage.
     *
     * This function returns the total disk usage for the mailing lists of a cPanel account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/mailing-lists/email-get_lists_total_disk_usage
     */
    public function getListsTotalDiskUsage(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_lists_total_disk_usage', [], $extra);
    }

    /**
     * Return cPanel account's mailbox autocreate status.
     *
     * This function checks whether a cPanel account will automatically create mailboxes when it receives
     * an email address in plus address format.
     *
     * @param  string  $email  The email account address to query.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-server-information/email-get_mailbox_autocreate
     */
    public function getMailboxAutocreate(
        string $email,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_mailbox_autocreate', [
            'email' => $email,
        ], $extra);
    }

    /**
     * Return mailing list administrators.
     *
     * This function lists a mailing list's administrators.
     *
     * @param  string  $list  The name of a Mailman mailing list on the cPanel account.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/mailing-lists/email-get_mailman_delegates
     */
    public function getMailmanDelegates(
        string $list,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_mailman_delegates', [
            'list' => $list,
        ], $extra);
    }

    /**
     * Return primary email account's disk usage.
     *
     * This function returns the disk space that the main account uses.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-get_main_account_disk_usage
     */
    public function getMainAccountDiskUsage(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_main_account_disk_usage', [], $extra);
    }

    /**
     * Return primary email account's disk usage in bytes.
     *
     * This function returns the disk space that the cPanel account uses.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-get_main_account_disk_usage_bytes
     */
    public function getMainAccountDiskUsageBytes(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_main_account_disk_usage_bytes', [], $extra);
    }

    /**
     * Return email account's max quota size.
     *
     * This function retrieves the account's maximum email quota size, in bytes format.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-get_max_email_quota
     */
    public function getMaxEmailQuota(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_max_email_quota', [], $extra);
    }

    /**
     * Return email account's max quota size in MiB.
     *
     * This function retrieves the account's maximum email account quota size, in Mebibytes (MiB) format.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-get_max_email_quota_mib
     */
    public function getMaxEmailQuotaMib(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_max_email_quota_mib', [], $extra);
    }

    /**
     * Return email account's quota.
     *
     * This function retrieves an email account's quota.
     *
     * @param  string  $email  The email account username.
     * @param  bool|int|null  $asBytes  Whether to return the quota as bytes.
     * @param  string|null  $domain  The email account's domain.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-get_pop_quota
     */
    public function getPopQuota(
        string $email,
        bool|int|null $asBytes = null,
        ?string $domain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_pop_quota', [
            'email' => $email,
            'as_bytes' => $asBytes,
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Return email account Apache SpamAssassin settings.
     *
     * This function retrieves the Apache SpamAssassin settings for the account.
     *
     * @param  string|null  $account  Retrieve a specific user account's SpamAssassin settings.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/spam-management/email-get_spam_settings
     */
    public function getSpamSettings(
        ?string $account = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_spam_settings', [
            'account' => $account,
        ], $extra);
    }

    /**
     * Return email account's Webmail settings.
     *
     * This function retrieves an email account's Webmail settings.
     *
     * @param  string|null  $account  The email account.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-get_webmail_settings
     */
    public function getWebmailSettings(
        ?string $account = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_webmail_settings', [
            'account' => $account,
        ], $extra);
    }

    /**
     * Return email account's mailing list privileges.
     *
     * This function checks an account's administrative privileges on mailing lists.
     *
     * @param  string  $delegate  The email address.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/mailing-lists/email-has_delegated_mailman_lists
     */
    public function hasDelegatedMailmanLists(
        string $delegate,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('has_delegated_mailman_lists', [
            'delegate' => $delegate,
        ], $extra);
    }

    /**
     * Return whether plaintext authentication is enabled.
     *
     * This function checks whether plaintext authentication is enabled on the Dovecot mail server.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-server-information/email-has_plaintext_authentication
     */
    public function hasPlaintextAuthentication(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('has_plaintext_authentication', [], $extra);
    }

    /**
     * Stop email account's outgoing mail.
     *
     * This function sets Exim's queue to not send outgoing mail from an email account.
     *
     * @param  string  $email  The email account's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-hold_outgoing
     */
    public function holdOutgoing(
        string $email,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('hold_outgoing', [
            'email' => $email,
        ], $extra);
    }

    /**
     * Return domain's autoresponders.
     *
     * This function lists a domain's autoresponders.
     *
     * @param  string  $domain  The domain name.
     * @param  string|null  $regex  A Perl Compatible Regular Expression (PCRE) that filters the results.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-list_auto_responders
     */
    public function listAutoResponders(
        string $domain,
        ?string $regex = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_auto_responders', [
            'domain' => $domain,
            'regex' => $regex,
        ], $extra);
    }

    /**
     * Return domain's default email address.
     *
     * This function retrieves a domain's default address.
     *
     * @param  string  $user  The user whose default addresses to list.
     * @param  string|null  $domain  The domain.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-list_default_address
     */
    public function listDefaultAddress(
        string $user,
        ?string $domain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_default_address', [
            'user' => $user,
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Return domain-level forwarders.
     *
     * This function lists domain-level forwarders.
     *
     * @param  string|null  $domain  The domain name to query.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-forwarding/email-list_domain_forwarders
     */
    public function listDomainForwarders(
        ?string $domain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_domain_forwarders', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Return account-level email filters.
     *
     * This function lists account-level mail filters. For more information about Exim filters, read
     * Exim’s documentation.
     *
     * @param  string|null  $account  The email address or cPanel account username for which to return a list of filters.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-filtering/email-list_filters
     */
    public function listFilters(
        ?string $account = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_filters', [
            'account' => $account,
        ], $extra);
    }

    /**
     * Return domains with domain-level email filters.
     *
     * This function lists all of the cPanel account's domains that use domain-level filters.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-filtering/email-list_filters_backups
     */
    public function listFiltersBackups(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_filters_backups', [], $extra);
    }

    /**
     * Return domain's forwarders.
     *
     * This function lists a domain's forwarders.
     *
     * @param  string  $domain  The domain.
     * @param  string|null  $regex  A Perl Compatible Regular Expression (PCRE) that filters the forwarded address or destination.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-forwarding/email-list_forwarders
     */
    public function listForwarders(
        string $domain,
        ?string $regex = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_forwarders', [
            'domain' => $domain,
            'regex' => $regex,
        ], $extra);
    }

    /**
     * Return domains with domain-level forwarders.
     *
     * This function lists the domains with domain-level forwarders.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-forwarding/email-list_forwarders_backups
     */
    public function listForwardersBackups(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_forwarders_backups', [], $extra);
    }

    /**
     * Return cPanel account's mailing lists.
     *
     * This function lists the account's Mailman mailing lists.
     *
     * @param  string|null  $domain  The domain to query.
     * @param  string|null  $regex  A Perl Compatible Regular Expression (PCRE) that filters the results.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/mailing-lists/email-list_lists
     */
    public function listLists(
        ?string $domain = null,
        ?string $regex = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_lists', [
            'domain' => $domain,
            'regex' => $regex,
        ], $extra);
    }

    /**
     * Return cPanel account's mail domains.
     *
     * This function lists the account's mail domains.
     *
     * @param  bool|int|null  $addWww  Whether to list `www.` addresses.
     * @param  bool|int|null  $includeWildcard  Whether to list wildcard addresses.
     * @param  bool|null  $returnTemporaryDomain  Whether to include temporary domains (*.cpanel.site) in the output.
     * @param  string|null  $select  The name of the domain that the function returns with the `select `output parameter.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-list_mail_domains
     */
    public function listMailDomains(
        bool|int|null $addWww = null,
        bool|int|null $includeWildcard = null,
        ?bool $returnTemporaryDomain = null,
        ?string $select = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_mail_domains', [
            'add_www' => $addWww,
            'include_wildcard' => $includeWildcard,
            'return_temporary_domain' => $returnTemporaryDomain,
            'select' => $select,
        ], $extra);
    }

    /**
     * Return mail exchanger records.
     *
     * This function lists Mail Exchanger (MX) records.
     *
     * @param  string|null  $domain  The domain to query.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-dns-settings/email-list_mxs
     */
    public function listMxs(
        ?string $domain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_mxs', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Return email accounts.
     *
     * This function lists the cPanel account's email accounts.
     *
     * @param  bool|int|null  $noValidate  Whether to skip the email database's validation check.
     * @param  string|null  $regex  A Perl Compatible Regular Expression (PCRE) that filters the results.
     * @param  bool|int|null  $skipMain  Whether to exclude the cPanel account's main account from the results.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-list_pops
     */
    public function listPops(
        bool|int|null $noValidate = null,
        ?string $regex = null,
        bool|int|null $skipMain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_pops', [
            'no_validate' => $noValidate,
            'regex' => $regex,
            'skip_main' => $skipMain,
        ], $extra);
    }

    /**
     * Return email accounts with disk information.
     *
     * This function lists the cPanel account's email accounts with disk information.
     *
     * @param  string|null  $domain  A domain name to filter the results by.
     * @param  string|null  $email  The cPanel user account to query.
     * @param  bool|int|null  $getRestrictions  Whether to display restriction status for each of the email addresses.
     * @param  string|null  $infinityimg  An image to display for email addresses with an unlimited quota.
     * @param  bool|int|null  $infinitylang  Whether to return the `∞` character for email addresses with an unlimited quota.
     * @param  int|null  $maxaccounts  The maximum number of email addresses to return.
     * @param  bool|int|null  $noDisk  Whether to skip the collection of disk usage information.
     * @param  bool|int|null  $noValidate  Whether to skip email database validation.
     * @param  string|null  $regex  A Perl Compatible Regular Expression (PCRE) that filters the results.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-list_pops_with_disk
     */
    public function listPopsWithDisk(
        ?string $domain = null,
        ?string $email = null,
        bool|int|null $getRestrictions = null,
        ?string $infinityimg = null,
        bool|int|null $infinitylang = null,
        ?int $maxaccounts = null,
        bool|int|null $noDisk = null,
        bool|int|null $noValidate = null,
        ?string $regex = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_pops_with_disk', [
            'domain' => $domain,
            'email' => $email,
            'get_restrictions' => $getRestrictions,
            'infinityimg' => $infinityimg,
            'infinitylang' => $infinitylang,
            'maxaccounts' => $maxaccounts,
            'no_disk' => $noDisk,
            'no_validate' => $noValidate,
            'regex' => $regex,
        ], $extra);
    }

    /**
     * Return system-level email filter file information.
     *
     * This function retrieves a `.yaml.gz` file that contains system-level filter information.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-filtering/email-list_system_filter_info
     */
    public function listSystemFilterInfo(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_system_filter_info', [], $extra);
    }

    /**
     * Update mailing list password.
     *
     * This function changes a mailing list's password.
     *
     * @param  string  $list  The full name (including the domain) of a Mailman mailing list on the cPanel account.
     * @param  string  $password  The new password.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/mailing-lists/email-passwd_list
     */
    public function passwdList(
        string $list,
        #[SensitiveParameter] string $password,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('passwd_list', [
            'list' => $list,
            'password' => $password,
        ], $extra);
    }

    /**
     * Update email account password.
     *
     * This function changes an email account's password.
     *
     * @param  string  $email  The email account username or address.
     * @param  string  $password  The email account password.
     * @param  string|null  $domain  The email account's domain.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-passwd_pop
     */
    public function passwdPop(
        string $email,
        #[SensitiveParameter] string $password,
        ?string $domain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('passwd_pop', [
            'email' => $email,
            'password' => $password,
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Start email account outgoing mail.
     *
     * This function sends all of the outgoing mail from Exim's queue for an email account.
     *
     * @param  string  $email  The email account's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-release_outgoing
     */
    public function releaseOutgoing(
        string $email,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('release_outgoing', [
            'email' => $email,
        ], $extra);
    }

    /**
     * Remove account mailing list admin privileges.
     *
     * This function removes an account's mailing list administrative privileges.
     *
     * @param  string  $delegates  list of the administrators to remove.
     * @param  string  $list  The mailing list.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/mailing-lists/email-remove_mailman_delegates
     */
    public function removeMailmanDelegates(
        string $delegates,
        string $list,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('remove_mailman_delegates', [
            'delegates' => $delegates,
            'list' => $list,
        ], $extra);
    }

    /**
     * Update email address's email filter order.
     *
     * This function modifies the filter order for an email address. For more information about Exim
     * filters, read Exim's documentation.
     *
     * @param  string  $mailbox  The email address.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-filtering/email-reorder_filters
     */
    public function reorderFilters(
        string $mailbox,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('reorder_filters', [
            'mailbox' => $mailbox,
        ], $extra);
    }

    /**
     * Update Mail Exchanger type.
     *
     * This function sets the Mail Exchanger (MX) type.
     *
     * @param  string  $domain  The mail exchanger's domain.
     * @param  string|null  $alwaysaccept  The mail exchanger type.
     * @param  string|null  $mxcheck  The mail exchanger type.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-server-information/email-set_always_accept
     */
    public function setAlwaysAccept(
        string $domain,
        ?string $alwaysaccept = null,
        ?string $mxcheck = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_always_accept', [
            'domain' => $domain,
            'alwaysaccept' => $alwaysaccept,
            'mxcheck' => $mxcheck,
        ], $extra);
    }

    /**
     * Create default email address.
     *
     * This function configures a default (catchall) email address.
     *
     * @param  string  $fwdopt  The method to use to handle unroutable mail.
     * @param  string|null  $domain  The domain whose default email behavior you want to configure.
     * @param  string|null  $failmsgs  The failure message for the message’s sender.
     * @param  string|null  $fwdemail  The email address to which the system forwards messages.
     * @param  string|null  $pipefwd  The application to which the system pipes messages.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-set_default_address
     */
    public function setDefaultAddress(
        string $fwdopt,
        ?string $domain = null,
        ?string $failmsgs = null,
        ?string $fwdemail = null,
        ?string $pipefwd = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_default_address', [
            'fwdopt' => $fwdopt,
            'domain' => $domain,
            'failmsgs' => $failmsgs,
            'fwdemail' => $fwdemail,
            'pipefwd' => $pipefwd,
        ], $extra);
    }

    /**
     * Update mailing list privacy options.
     *
     * This function modifies a Mailman mailing list's privacy options.
     *
     * @param  bool|int  $advertised  Whether the Mailman directory page displays the list.
     * @param  bool|int  $archivePrivate  Whether the mailing list archive is private.
     * @param  string  $list  The mailing list name.
     * @param  int  $subscribePolicy  The level of control that the mailing list administrator has over new subscribers.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/mailing-lists/email-set_list_privacy_options
     */
    public function setListPrivacyOptions(
        bool|int $advertised,
        bool|int $archivePrivate,
        string $list,
        int $subscribePolicy,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_list_privacy_options', [
            'advertised' => $advertised,
            'archive_private' => $archivePrivate,
            'list' => $list,
            'subscribe_policy' => $subscribePolicy,
        ], $extra);
    }

    /**
     * Add manual MX redirection.
     *
     * This function lets you create a manual Exim mail exchanger (MX) redirect for a domain. An MX
     * redirection lets you bypass the domain's MX lookup via the Domain Name System (DNS). This function
     * adds the manual redirect entries to the `/etc/manualmx` file.
     *
     * @param  string  $domain  The domain for which to add a manual MX redirect entry.
     * @param  string  $mxHost  The domain, IPv4, or IPv6 address to redirect the domain value's emails to.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-set_manual_mx_redirects
     */
    public function setManualMxRedirects(
        string $domain,
        string $mxHost,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_manual_mx_redirects', [
            'domain' => $domain,
            'mx_host' => $mxHost,
        ], $extra);
    }

    /**
     * Return eximstats SQLite database status.
     *
     * This function returns the status of the eximstats SQLite Database.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-server-information/email-stats_db_status
     */
    public function statsDbStatus(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('stats_db_status', [], $extra);
    }

    /**
     * Create email filter.
     *
     * This function creates a new email filter. For more information about Exim filters, read Exim's
     * documentation.
     *
     * @param  string  $filtername  The filter name.
     * @param  string|null  $account  The email address, for user-level filters.
     * @param  string|null  $oldfiltername  The name of an existing filter, to rename it.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-filtering/email-store_filter
     */
    public function storeFilter(
        string $filtername,
        ?string $account = null,
        ?string $oldfiltername = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('store_filter', [
            'filtername' => $filtername,
            'account' => $account,
            'oldfiltername' => $oldfiltername,
        ], $extra);
    }

    /**
     * Suspend email account incoming (SMTP) mail.
     *
     * This function suspends incoming email for an account. The system will reject incoming email while
     * the account is suspended.
     *
     * @param  string|null  $email  The email user's account name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-suspensions/email-suspend_incoming
     */
    public function suspendIncoming(
        ?string $email = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('suspend_incoming', [
            'email' => $email,
        ], $extra);
    }

    /**
     * Suspend email account login.
     *
     * This function suspends a user's ability to log in to their email account. This function immediately
     * suspends the user's login credentials and prevents future authenticated connections to the email
     * account.
     *
     * @param  string  $email  The email user's account name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-suspensions/email-suspend_login
     */
    public function suspendLogin(
        string $email,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('suspend_login', [
            'email' => $email,
        ], $extra);
    }

    /**
     * Suspend email account outgoing mail.
     *
     * This function rejects outgoing mail for a suspended email account. This function does not disable a
     * user's login credentials or access permissions to their email account.
     *
     * @param  string  $email  The email account's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-suspensions/email-suspend_outgoing
     */
    public function suspendOutgoing(
        string $email,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('suspend_outgoing', [
            'email' => $email,
        ], $extra);
    }

    /**
     * Stop cPanel account IMAP and POP3 connections.
     *
     * This function terminates all IMAP and POP3 connections for a cPanel account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-terminate_mailbox_sessions
     */
    public function terminateMailboxSessions(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('terminate_mailbox_sessions', [], $extra);
    }

    /**
     * Run email delivery route trace.
     *
     * This function traces the email delivery route to an email account.
     *
     * @param  string  $recipient  The email address to which to trace a message delivery path.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-trace_delivery
     */
    public function traceDelivery(
        string $recipient,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('trace_delivery', [
            'recipient' => $recipient,
        ], $extra);
    }

    /**
     * Run test for main domain email filters.
     *
     * This function tests mail filters. The function only tests filters for the cPanel account's main
     * domain, and only tests against the message's body. For more information about Exim filters, read
     * Exim's documentation.
     *
     * @param  string  $msg  The string to test.
     * @param  string|null  $account  The email address, to test legacy cPanel filters in the filters directory.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-filtering/email-trace_filter
     */
    public function traceFilter(
        string $msg,
        ?string $account = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('trace_filter', [
            'msg' => $msg,
            'account' => $account,
        ], $extra);
    }

    /**
     * Remove manual MX redirection.
     *
     * This function lets you create a manual Exim mail exchanger (MX) redirect for a domain. An MX
     * redirection lets you bypass the domain's MX lookup via the Domain Name System (DNS). This function
     * adds the manual redirect entries to the `/etc/manualmx` file.
     *
     * @param  string  $domain  The domain for which to add a manual MX redirect entry.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-unset_manual_mx_redirects
     */
    public function unsetManualMxRedirects(
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('unset_manual_mx_redirects', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Unsuspend email account incoming mail.
     *
     * This function unsuspends incoming email for an email account.
     *
     * @param  string|null  $email  The email user's account name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-suspensions/email-unsuspend_incoming
     */
    public function unsuspendIncoming(
        ?string $email = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('unsuspend_incoming', [
            'email' => $email,
        ], $extra);
    }

    /**
     * Unsuspend email account login.
     *
     * This function restores a user's ability to log in to their email account.
     *
     * @param  string|null  $email  The email user's account name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-suspensions/email-unsuspend_login
     */
    public function unsuspendLogin(
        ?string $email = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('unsuspend_login', [
            'email' => $email,
        ], $extra);
    }

    /**
     * Unsuspend email account outgoing mail.
     *
     * This function cancels the suspension action put in place by the UAPI `Email::suspend_outgoing`
     * function for outgoing mail for an email account.
     *
     * @param  string  $email  The email account's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-suspensions/email-unsuspend_outgoing
     */
    public function unsuspendOutgoing(
        string $email,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('unsuspend_outgoing', [
            'email' => $email,
        ], $extra);
    }

    /**
     * Validate email account password.
     *
     * This function verifies the password for an email account.
     *
     * @param  string  $email  The email account address.
     * @param  string  $password  The email account password.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/email-accounts/email-verify_password
     */
    public function verifyPassword(
        string $email,
        #[SensitiveParameter] string $password,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('verify_password', [
            'email' => $email,
            'password' => $password,
        ], $extra);
    }
}
