<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI Features module (5 functions), run as one cPanel account through WHM.
 */
final class Features extends UapiModule
{
    public const string MODULE = 'Features';

    /**
     * Return cPanel account's features' metadata.
     *
     * This function lists the details of a cPanel account's available feature lists.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/features/features-get_feature_metadata
     */
    public function getFeatureMetadata(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_feature_metadata', [], $extra);
    }

    /**
     * Validate cPanel account's feature access.
     *
     * This function checks whether a cPanel account has access to a feature.
     *
     * @param  string  $name  The feature's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/features/features-has_feature
     */
    public function hasFeature(
        string $name,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('has_feature', [
            'name' => $name,
        ], $extra);
    }

    /**
     * Return whether queried features are enabled.
     *
     * This function allows you to search for cPanel account features and determine whether those features
     * are enabled.
     *
     * @param  string  $pattern  The feature's name that you wish to search.
     * @param  bool|int|null  $isRegex  Whether the `pattern` parameter's value is a regular expression.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/features/features-has_features_like
     */
    public function hasFeaturesLike(
        string $pattern,
        bool|int|null $isRegex = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('has_features_like', [
            'pattern' => $pattern,
            'is_regex' => $isRegex,
        ], $extra);
    }

    /**
     * Return cPanel account's features.
     *
     * This function lists a cPanel account's features.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/features/features-list_features
     */
    public function listFeatures(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_features', [], $extra);
    }

    /**
     * Return queried cPanel account features.
     *
     * This function allows you to search for enabled cPanel account features and lists those features in
     * the returned payload.
     *
     * @param  string  $pattern  The feature's name that you wish to search.
     * @param  bool|int|null  $isRegex  Whether the `pattern` parameter's value is a regular expression.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/features/features-list_features_like
     */
    public function listFeaturesLike(
        string $pattern,
        bool|int|null $isRegex = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_features_like', [
            'pattern' => $pattern,
            'is_regex' => $isRegex,
        ], $extra);
    }
}
