<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI ImageManager module (4 functions), run as one cPanel account through WHM.
 */
final class ImageManager extends UapiModule
{
    public const string MODULE = 'ImageManager';

    /**
     * Create image with new format.
     *
     * This function converts an image to a new file format.
     *
     * @param  string  $imageFile  The image file to convert, relative to the cPanel account's `/home` directory.
     * @param  string  $type  The format to which to convert the images.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/imagemanager/imagemanager-convert_file
     */
    public function convertFile(
        string $imageFile,
        string $type,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('convert_file', [
            'image_file' => $imageFile,
            'type' => $type,
        ], $extra);
    }

    /**
     * Create image thumbnails.
     *
     * This function creates thumbnails from images. The function saves the new thumbnail images in a
     * thumbnails subdirectory inside the original directory. The system prepends thumbnail filenames with
     * ``tn_`` (for example, ``tn_picture.jpg``).
     *
     * @param  string  $dir  The path to the directory where the image resides.
     * @param  int  $heightPercentage  The percentage by which to reduce the thumbnails' height.
     * @param  int  $widthPercentage  The percentage by which to reduce the thumbnails' width.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/imagemanager/imagemanager-create_thumbnails
     */
    public function createThumbnails(
        string $dir,
        int $heightPercentage,
        int $widthPercentage,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('create_thumbnails', [
            'dir' => $dir,
            'height_percentage' => $heightPercentage,
            'width_percentage' => $widthPercentage,
        ], $extra);
    }

    /**
     * Return image dimensions.
     *
     * This function returns the dimensions of the image file that you specify.
     *
     * @param  string  $imageFile  The path to the file to measure.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/imagemanager/imagemanager-get_dimensions
     */
    public function getDimensions(
        string $imageFile,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_dimensions', [
            'image_file' => $imageFile,
        ], $extra);
    }

    /**
     * Save resized image.
     *
     * This function resizes a specified image.
     *
     * @param  int  $height  The height to which to set the image size.
     * @param  string  $imageFile  The name of the file to scale.
     * @param  int  $width  The width to which to set the image size.
     * @param  string|null  $saveOriginalAs  The path to the directory in which to save a copy the original image file.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/imagemanager/imagemanager-resize_image
     */
    public function resizeImage(
        int $height,
        string $imageFile,
        int $width,
        ?string $saveOriginalAs = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('resize_image', [
            'height' => $height,
            'image_file' => $imageFile,
            'width' => $width,
            'save_original_as' => $saveOriginalAs,
        ], $extra);
    }
}
