<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI Integration module (1 functions), run as one cPanel account through WHM.
 */
final class Integration extends UapiModule
{
    public const string MODULE = 'Integration';

    /**
     * Return integrated application URL.
     *
     * This function returns the URL for an integrated application.
     *
     * @param  string  $app  The application's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/integration/integration-fetch_url
     */
    public function fetchUrl(
        string $app,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('fetch_url', [
            'app' => $app,
        ], $extra);
    }
}
