<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI KnownHosts module (4 functions), run as one cPanel account through WHM.
 */
final class KnownHosts extends UapiModule
{
    public const string MODULE = 'KnownHosts';

    /**
     * Create host.
     *
     * This function registers a host in the cPanel account's `/home/user/.ssh/known_hosts` file.
     *
     * @param  string  $hostName  The hostname or IP address to add.
     * @param  int|null  $port  The SSH port to use, if the system uses a non-standard SSH port.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/knownhosts/knownhosts-create
     */
    public function create(
        string $hostName,
        ?int $port = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('create', [
            'host_name' => $hostName,
            'port' => $port,
        ], $extra);
    }

    /**
     * Delete host.
     *
     * This function removes a host from the cPanel account's `/home/user/.ssh/known_hosts` file.
     *
     * @param  string  $hostName  The hostname or IP address of the host to delete.
     * @param  int|null  $port  The SSH port to use.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/knownhosts/knownhosts-delete
     */
    public function delete(
        string $hostName,
        ?int $port = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('delete', [
            'host_name' => $hostName,
            'port' => $port,
        ], $extra);
    }

    /**
     * Update host in the known_hosts file.
     *
     * This function updates a host's entry in the cPanel account's /home/user/.ssh/known_hosts file.
     *
     * @param  string  $hostName  The host to update.
     * @param  int|null  $port  The SSH port to use.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/knownhosts/knownhosts-update
     */
    public function update(
        string $hostName,
        ?int $port = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('update', [
            'host_name' => $hostName,
            'port' => $port,
        ], $extra);
    }

    /**
     * Validate host.
     *
     * This function checks whether a host's public key exists in the cPanel account's
     * `/home/user/.ssh/known_hosts` file.
     *
     * @param  string  $hostName  The host to query.
     * @param  int|null  $port  The SSH port to use.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/knownhosts/knownhosts-verify
     */
    public function verify(
        string $hostName,
        ?int $port = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('verify', [
            'host_name' => $hostName,
            'port' => $port,
        ], $extra);
    }
}
