<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI Locale module (3 functions), run as one cPanel account through WHM.
 */
final class Locale extends UapiModule
{
    public const string MODULE = 'Locale';

    /**
     * Return current locale settings.
     *
     * This function retrieves information about the user's current locale setting.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/locale/locale-get_attributes
     */
    public function getAttributes(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_attributes', [], $extra);
    }

    /**
     * Return available locales.
     *
     * This function lists an account's available interface languages.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/locale/locale-list_locales
     */
    public function listLocales(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_locales', [], $extra);
    }

    /**
     * Update cPanel account locale.
     *
     * This function sets the account's locale.
     *
     * @param  string  $locale  The locale's abbreviated name according to UAPI's `Locale::list_locales` function.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/locale/locale-set_locale
     */
    public function setLocale(
        string $locale,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_locale', [
            'locale' => $locale,
        ], $extra);
    }
}
