<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;
use SensitiveParameter;

/**
 * UAPI Market module (19 functions), run as one cPanel account through WHM.
 */
final class Market extends UapiModule
{
    public const string MODULE = 'Market';

    /**
     * Delete an order.
     *
     * This function cancels an order and removes the polling for a pending certificate.
     *
     * @param  string  $orderItemId  The ID of the ordered item to cancel.
     * @param  string  $provider  The cPanel Market provider's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-cancel_pending_ssl_certificate
     */
    public function cancelPendingSslCertificate(
        string $orderItemId,
        string $provider,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('cancel_pending_ssl_certificate', [
            'order_item_id' => $orderItemId,
            'provider' => $provider,
        ], $extra);
    }

    /**
     * Create shopping cart.
     *
     * This function creates a shopping cart with which the system sends an order to the cPanel Store.
     * Typically, the system will send shopping cart orders for SSL certificates to UAPI’s
     * `Market::request_ssl_certificates` function.
     *
     * @param  string  $accessToken  The access token to connect to the provider.
     * @param  array<array-key, mixed>  $item  The items to add to the shopping cart.
     * @param  string  $provider  The cPanel Market provider’s name.
     * @param  string  $urlAfterCheckout  The location to which the provider directs the user after the checkout process is complete.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-create_shopping_cart
     */
    public function createShoppingCart(
        #[SensitiveParameter] string $accessToken,
        array $item,
        string $provider,
        string $urlAfterCheckout,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('create_shopping_cart', [
            'access_token' => $accessToken,
            'item' => $item,
            'provider' => $provider,
            'url_after_checkout' => $urlAfterCheckout,
        ], $extra);
    }

    /**
     * Create shopping cart for non-SSL products.
     *
     * This function creates a shopping cart for non-SSL products. It validates the access token, retrieves
     * product information, creates a shopping cart with the provider, and returns the order details and
     * checkout URL.
     *
     * @param  string  $accessToken  The access token obtained during login to the cPanel Market provider.
     * @param  string  $productName  The name of the product to purchase.
     * @param  string  $urlAfterCheckout  The URL to which the provider redirects the user after the checkout process is complete.
     * @param  string|null  $domain  The domain associated with the product purchase.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-create_shopping_cart_non_ssl
     */
    public function createShoppingCartNonSsl(
        #[SensitiveParameter] string $accessToken,
        string $productName,
        string $urlAfterCheckout,
        ?string $domain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('create_shopping_cart_non_ssl', [
            'access_token' => $accessToken,
            'product_name' => $productName,
            'url_after_checkout' => $urlAfterCheckout,
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Return provider's available products.
     *
     * This function lists all products available through all enabled cPanel Market providers.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-get_all_products
     */
    public function getAllProducts(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_all_products', [], $extra);
    }

    /**
     * Build cart URL for a product.
     *
     * This function builds the URL for the shopping cart page for the specified product. The system saves
     * session data and constructs a full cPanel URL pointing to the product purchase page.
     *
     * @param  string  $productName  The name of the product for which to build the cart URL.
     * @param  string|null  $domain  The domain associated with the product purchase.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-get_build_cart_url
     */
    public function getBuildCartUrl(
        string $productName,
        ?string $domain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_build_cart_url', [
            'product_name' => $productName,
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Return provider's SSL certificate request status.
     *
     * This function returns the status of an SSL certificate request. The returns include actionable URLs
     * for users to expedite the validation process, if applicable.
     *
     * @param  int  $orderItemId  The order ID that the cPanel Market provider assigned.
     * @param  string  $provider  The cPanel Market provider's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-get_certificate_status_details
     */
    public function getCertificateStatusDetails(
        int $orderItemId,
        string $provider,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_certificate_status_details', [
            'order_item_id' => $orderItemId,
            'provider' => $provider,
        ], $extra);
    }

    /**
     * Get product purchase completion URL.
     *
     * This function builds the full cPanel URL for the product purchase completion page. The URL includes
     * the security token and points to the completion page for the specified product.
     *
     * @param  string  $productName  The name of the product for which to retrieve the completion URL.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-get_completion_url
     */
    public function getCompletionUrl(
        string $productName,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_completion_url', [
            'product_name' => $productName,
        ], $extra);
    }

    /**
     * Retrieve license information for a domain.
     *
     * This function retrieves license information for the specified domain from the cPanel Store and saves
     * it to the current session.
     *
     * @param  string|null  $domain  The domain for which to retrieve license information.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-get_license_info
     */
    public function getLicenseInfo(
        ?string $domain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_license_info', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Return provider's login URL.
     *
     * This function retrieves the login URL for the cPanel Market provider.
     *
     * @param  string  $provider  The cPanel Market provider's name.
     * @param  string  $urlAfterLogin  Where the cPanel Market provider redirects the user's browser after they log in.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-get_login_url
     */
    public function getLoginUrl(
        string $provider,
        string $urlAfterLogin,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_login_url', [
            'provider' => $provider,
            'url_after_login' => $urlAfterLogin,
        ], $extra);
    }

    /**
     * Return provider's pending SSL certificates.
     *
     * This function lists all pending SSL certificates from a cPanel Market provider for which the system
     * currently polls.
     *
     * @param  string  $provider  The cPanel Market provider's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-get_pending_ssl_certificates
     */
    public function getPendingSslCertificates(
        string $provider,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_pending_ssl_certificates', [
            'provider' => $provider,
        ], $extra);
    }

    /**
     * Retrieve product information.
     *
     * This function retrieves product information for the specified product name, including the product
     * ID, redirect path, and redirect URLs for successful and failed purchases.
     *
     * @param  string  $productName  The name of the product for which to retrieve information.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-get_product_info
     */
    public function getProductInfo(
        string $productName,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_product_info', [
            'product_name' => $productName,
        ], $extra);
    }

    /**
     * Return provider's DCV filename requirements.
     *
     * This function returns the provider's filename requirements for Domain Control Validation (DCV)
     * checks.
     *
     * @param  string  $provider  The cPanel Market provider's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-get_provider_specific_dcv_constraints
     */
    public function getProviderSpecificDcvConstraints(
        string $provider,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_provider_specific_dcv_constraints', [
            'provider' => $provider,
        ], $extra);
    }

    /**
     * Return enabled providers.
     *
     * This function lists the names of enabled cPanel Market providers.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-get_providers_list
     */
    public function getProvidersList(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_providers_list', [], $extra);
    }

    /**
     * Return provider's available SSL certificates.
     *
     * This function retrieves SSL certificates when they are available from the cPanel Market provider.
     *
     * @param  string  $orderItemId  The order item for which to poll.
     * @param  string  $provider  The cPanel Market provider's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-get_ssl_certificate_if_available
     */
    public function getSslCertificateIfAvailable(
        string $orderItemId,
        string $provider,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_ssl_certificate_if_available', [
            'order_item_id' => $orderItemId,
            'provider' => $provider,
        ], $extra);
    }

    /**
     * Start processing pending queue's SSL certificates.
     *
     * This function manually processes the cPanel Market's SSL certificate request pending queue.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-process_ssl_pending_queue
     */
    public function processSslPendingQueue(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('process_ssl_pending_queue', [], $extra);
    }

    /**
     * Request SSL certificate order.
     *
     * This function submits a request for a certificate order to the cPanel Market provider.
     *
     * @param  string  $accessToken  The access token for the session to the cPanel Market provider.
     * @param  mixed  $certificate  A JSON-encoded string that contains the details of the certificate.
     * @param  string  $provider  The cPanel Market provider's name.
     * @param  mixed  $identityVerification  An object containing the required information for an EV or OV certificate.
     * @param  string|null  $urlAfterCheckout  The URL to send the browser after the user checks out.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-request_ssl_certificates
     */
    public function requestSslCertificates(
        #[SensitiveParameter] string $accessToken,
        mixed $certificate,
        string $provider,
        mixed $identityVerification = null,
        ?string $urlAfterCheckout = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('request_ssl_certificates', [
            'access_token' => $accessToken,
            'certificate' => $certificate,
            'provider' => $provider,
            'identity_verification' => $identityVerification,
            'url_after_checkout' => $urlAfterCheckout,
        ], $extra);
    }

    /**
     * Update status of items in pending queue.
     *
     * This function sets the status of an item or items in the cPanel Market pending queue.
     *
     * @param  string  $orderItemId  The ID of the ordered item.
     * @param  string  $provider  The cPanel Market provider's name.
     * @param  string  $status  The new status of the item in the cPanel Market pending queue.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-set_status_of_pending_queue_items
     */
    public function setStatusOfPendingQueueItems(
        string $orderItemId,
        string $provider,
        string $status,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_status_of_pending_queue_items', [
            'order_item_id' => $orderItemId,
            'provider' => $provider,
            'status' => $status,
        ], $extra);
    }

    /**
     * Update URL after checkout.
     *
     * This function updates the URL to which a provider sends a user after they check out.
     *
     * @param  string  $accessToken  The access token for the session to the cPanel Market provider.
     * @param  int  $orderId  The order ID that the cPanel Market provider assigned.
     * @param  string  $provider  The cPanel Market provider's name.
     * @param  string  $urlAfterCheckout  The URL to send the browser after the user checks out.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-set_url_after_checkout
     */
    public function setUrlAfterCheckout(
        #[SensitiveParameter] string $accessToken,
        int $orderId,
        string $provider,
        string $urlAfterCheckout,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_url_after_checkout', [
            'access_token' => $accessToken,
            'order_id' => $orderId,
            'provider' => $provider,
            'url_after_checkout' => $urlAfterCheckout,
        ], $extra);
    }

    /**
     * Validate login token.
     *
     * This function validates a login token to a cPanel Market provider and returns an access token.
     *
     * @param  string  $loginToken  The login token for the cPanel Market provider.
     * @param  string  $provider  The name of the cPanel Market provider.
     * @param  string  $urlAfterLogin  The `url_after_login` value that you sent to UAPI's `Market::get_login_url` function.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/market/market-validate_login_token
     */
    public function validateLoginToken(
        #[SensitiveParameter] string $loginToken,
        string $provider,
        string $urlAfterLogin,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('validate_login_token', [
            'login_token' => $loginToken,
            'provider' => $provider,
            'url_after_login' => $urlAfterLogin,
        ], $extra);
    }
}
