<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;
use SensitiveParameter;

/**
 * UAPI Nova module (11 functions), run as one cPanel account through WHM.
 */
final class Nova extends UapiModule
{
    public const string MODULE = 'Nova';

    /**
     * Return Nova account status.
     *
     * This function returns whether the cPanel user has been provisioned on the AI App Builder (Nova),
     * that is, whether the cPanel user file carries a Nova API token.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-account_exists
     */
    public function accountExists(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('account_exists', [], $extra);
    }

    /**
     * Add an existing AI App Builder API token.
     *
     * This function adds an existing AI App Builder API token to a cPanel user.
     *
     * @param  string  $apiToken  The AI App Builder API token to add.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-add_api_token
     */
    public function addApiToken(
        #[SensitiveParameter] string $apiToken,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('add_api_token', [
            'api_token' => $apiToken,
        ], $extra);
    }

    /**
     * Return domain creation availability.
     *
     * This function returns whether a cPanel account can create new subdomains or addon domains.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-can_create_domains
     */
    public function canCreateDomains(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('can_create_domains', [], $extra);
    }

    /**
     * Create AI App Builder API key.
     *
     * This function creates an AI App Builder API token for a cPanel account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-create_account
     */
    public function createAccount(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('create_account', [], $extra);
    }

    /**
     * Return disk quota information.
     *
     * This function checks whether a user has sufficient free space to back up the domain's document root.
     *
     * @param  string|null  $domain  The domain to use for the AI App Builder website.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-disk_quota_check
     */
    public function diskQuotaCheck(
        ?string $domain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('disk_quota_check', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Return Nova account SSO URL.
     *
     * This function ensures that an AI App Builder account exists for the caller, then returns an SSO URL.
     * The system reuses existing accounts. For entitled accounts of any tier, the system usually
     * provisions the account eagerly, asynchronously, during account creation or package upgrades.
     *
     * @param  string|null  $colorScheme  The color scheme Meridian is using, so Nova can match it.
     * @param  string|null  $domain  The domain to use for the AI App Builder website.
     * @param  string|null  $promptToken  A base64-encoded prompt token to pre-populate the user's website generation goals.
     * @param  string|null  $returnUrl  Where Nova's "Back to cPanel" control returns the user.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-ensure_account
     */
    public function ensureAccount(
        ?string $colorScheme = null,
        ?string $domain = null,
        ?string $promptToken = null,
        ?string $returnUrl = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('ensure_account', [
            'colorScheme' => $colorScheme,
            'domain' => $domain,
            'promptToken' => $promptToken,
            'return_url' => $returnUrl,
        ], $extra);
    }

    /**
     * Return AI App Builder domains.
     *
     * This function returns the AI App Builder domains' information for the cPanel account.
     *
     * @param  string|null  $domain  The domain to use for the AI App Builder website.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-get_all_user_nova_info
     */
    public function getAllUserNovaInfo(
        ?string $domain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_all_user_nova_info', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Return AI App Builder SSO URL.
     *
     * This function returns an AI App Builder website's SSO URL.
     *
     * @param  string|null  $colorScheme  The color scheme Meridian is using, so Nova can match it.
     * @param  string|null  $domain  The domain to use for the AI App Builder website.
     * @param  string|null  $promptToken  A base64-encoded prompt token to pre-populate the user's website generation goals.
     * @param  string|null  $returnUrl  Where Nova's "Back to cPanel" control returns the user.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-get_sso_link
     */
    public function getSsoLink(
        ?string $colorScheme = null,
        ?string $domain = null,
        ?string $promptToken = null,
        ?string $returnUrl = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_sso_link', [
            'colorScheme' => $colorScheme,
            'domain' => $domain,
            'promptToken' => $promptToken,
            'return_url' => $returnUrl,
        ], $extra);
    }

    /**
     * Return the user's Nova tier snapshot.
     *
     * This function returns the cPanel user's AI App Builder (Nova) tier snapshot for tier display and
     * upsell.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-get_tier
     */
    public function getTier(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_tier', [], $extra);
    }

    /**
     * Return AI App Builder publication process.
     *
     * This function polls the publishing progress information.
     *
     * @param  string  $fileName  The publish process's log file name.
     * @param  int  $pid  The publish action's process ID, as returned by the `publish` function.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-poll_publish
     */
    public function pollPublish(
        string $fileName,
        int $pid,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('poll_publish', [
            'file_name' => $fileName,
            'pid' => $pid,
        ], $extra);
    }

    /**
     * Run AI App Builder domain publication.
     *
     * This function publishes an AI App Builder website to the document root directory for the selected
     * domain.
     *
     * @param  string  $archiveUrl  URL to download the website archive from.
     * @param  string  $domain  The domain to use for the AI App Builder website.
     * @param  string  $signature  Security signature for request validation.
     * @param  string  $userId  Unique identifier for the website.
     * @param  int|null  $cleanup  Whether to cleanup the domain's `document_root` directory during the publication process.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/nova/nova-publish
     */
    public function publish(
        string $archiveUrl,
        string $domain,
        string $signature,
        string $userId,
        ?int $cleanup = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('publish', [
            'archiveUrl' => $archiveUrl,
            'domain' => $domain,
            'signature' => $signature,
            'userId' => $userId,
            'cleanup' => $cleanup,
        ], $extra);
    }
}
