<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI PasswdStrength module (1 functions), run as one cPanel account through WHM.
 */
final class PasswdStrength extends UapiModule
{
    public const string MODULE = 'PasswdStrength';

    /**
     * Return minimum required password strength.
     *
     * This function retrieves an application's minimum required password strength.
     *
     * @param  string  $app  The application's name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/passwdstrength/passwdstrength-get_required_strength
     */
    public function getRequiredStrength(
        string $app,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_required_strength', [
            'app' => $app,
        ], $extra);
    }
}
