<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI Pushbullet module (1 functions), run as one cPanel account through WHM.
 */
final class Pushbullet extends UapiModule
{
    public const string MODULE = 'Pushbullet';

    /**
     * Validate Pushbullet token.
     *
     * This function sends a Pushbullet test message to determine that the token is valid and that the
     * account holder can receive the message.
     *
     * @param  string  $accessToken  The Pushbullet access token.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/pushbullet/pushbullet-send_test_message
     */
    public function sendTestMessage(
        string $accessToken,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('send_test_message', [
            'access_token' => $accessToken,
        ], $extra);
    }
}
