<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI Resellers module (1 functions), run as one cPanel account through WHM.
 */
final class Resellers extends UapiModule
{
    public const string MODULE = 'Resellers';

    /**
     * Return reseller's cPanel accounts.
     *
     * This function lists all of a reseller's cPanel accounts.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/resellers/resellers-list_accounts
     */
    public function listAccounts(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list_accounts', [], $extra);
    }
}
