<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI ResourceUsage module (1 functions), run as one cPanel account through WHM.
 */
final class ResourceUsage extends UapiModule
{
    public const string MODULE = 'ResourceUsage';

    /**
     * Return resource usage and custom statistics.
     *
     * This function retrieves resource usage and custom statistics for a cPanel user account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/resourceusage/resourceusage-get_usages
     */
    public function getUsages(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_usages', [], $extra);
    }
}
