<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI ServiceProxy module (3 functions), run as one cPanel account through WHM.
 */
final class ServiceProxy extends UapiModule
{
    public const string MODULE = 'ServiceProxy';

    /**
     * Return a cPanel account’s service proxying setup.
     *
     * This function reports a cPanel account's service proxying configuration.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/serviceproxy/serviceproxy-get_service_proxy_backends
     */
    public function getServiceProxyBackends(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_service_proxy_backends', [], $extra);
    }

    /**
     * Add cPanel account service proxying.
     *
     * This function lets you configure a cPanel account's service proxying.
     *
     * @param  string|null  $general  The hostname or IP address to assign as the server that handles the account's service proxy requests.
     * @param  string|null  $serviceGroup  The name of a service group for which to assign a proxy backend.
     * @param  string|null  $serviceGroupBackend  The hostname or IP address of the server to assign as the corresponding `service_group` value's proxy backend server.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/serviceproxy/serviceproxy-set_service_proxy_backends
     */
    public function setServiceProxyBackends(
        ?string $general = null,
        ?string $serviceGroup = null,
        ?string $serviceGroupBackend = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_service_proxy_backends', [
            'general' => $general,
            'service_group' => $serviceGroup,
            'service_group_backend' => $serviceGroupBackend,
        ], $extra);
    }

    /**
     * Remove cPanel account service proxying.
     *
     * This function removes a cPanel account's service proxying.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/serviceproxy/serviceproxy-unset_all_service_proxy_backends
     */
    public function unsetAllServiceProxyBackends(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('unset_all_service_proxy_backends', [], $extra);
    }
}
