<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI Sitejet module (14 functions), run as one cPanel account through WHM.
 */
final class Sitejet extends UapiModule
{
    public const string MODULE = 'Sitejet';

    /**
     * Add an existing Sitejet API token.
     *
     * This function adds an existing Sitejet API token to a cPanel user.
     *
     * @param  string  $apiToken  The Sitejet API token to add.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/sitejet-add_api_token
     */
    public function addApiToken(
        string $apiToken,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('add_api_token', [
            'api_token' => $apiToken,
        ], $extra);
    }

    /**
     * Return Domain Availability.
     *
     * This function returns whether a cPanel account can create new subdomains or addon domains.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/sitejet-can_create_domains
     */
    public function canCreateDomains(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('can_create_domains', [], $extra);
    }

    /**
     * Generate a Sitejet API key.
     *
     * This function creates a Sitejet API token for a cPanel account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/sitejet-create_account
     */
    public function createAccount(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('create_account', [], $extra);
    }

    /**
     * Create a restore point.
     *
     * This function creates a restore point for a domain's document root and removes the domain's files.
     *
     * @param  string  $domain  A cPanel account's domain.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/sitejet-create_restore_point
     */
    public function createRestorePoint(
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('create_restore_point', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Create Sitejet domain ID.
     *
     * This function creates a Sitejet ID for the specified domain.
     *
     * @param  string  $company  The name of the company the website represents.
     * @param  string  $domain  A cPanel account's domain.
     * @param  string|null  $assignTo  Assign website to other user.
     * @param  string|null  $city  The city where the company or website owner is located.
     * @param  string|null  $country  The country where the company or website owner is located.
     * @param  string|null  $email  The email address of the website owner.
     * @param  string|null  $firstname  The first name of the website owner.
     * @param  string|null  $language  The language to use for the Sitejet Website Builder.
     * @param  string|null  $lastname  The last name of the website owner.
     * @param  string|null  $metadata  Additional metadata for the website.
     * @param  string|null  $note  Additional notes about the website.
     * @param  string|null  $phone  The phone number of the company or website owner.
     * @param  string|null  $street  The street address of the company or website owner.
     * @param  string|null  $title  The website title.
     * @param  string|null  $zip  The zip code where the company or website owner is located.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/sitejet-create_website
     */
    public function createWebsite(
        string $company,
        string $domain,
        ?string $assignTo = null,
        ?string $city = null,
        ?string $country = null,
        ?string $email = null,
        ?string $firstname = null,
        ?string $language = null,
        ?string $lastname = null,
        ?string $metadata = null,
        ?string $note = null,
        ?string $phone = null,
        ?string $street = null,
        ?string $title = null,
        ?string $zip = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('create_website', [
            'company' => $company,
            'domain' => $domain,
            'assignTo' => $assignTo,
            'city' => $city,
            'country' => $country,
            'email' => $email,
            'firstname' => $firstname,
            'language' => $language,
            'lastname' => $lastname,
            'metadata' => $metadata,
            'note' => $note,
            'phone' => $phone,
            'street' => $street,
            'title' => $title,
            'zip' => $zip,
        ], $extra);
    }

    /**
     * Return Sitejet domains.
     *
     * This function returns the Sitejet domains' information for the cPanel account.
     *
     * @param  string|null  $domain  The single domain to return Sitejet information.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/sitejet-get_all_user_sitejet_info
     */
    public function getAllUserSitejetInfo(
        ?string $domain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_all_user_sitejet_info', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Return Sitejet API token.
     *
     * This function returns the cPanel account's Sitejet API token.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/sitejet-get_api_token
     */
    public function getApiToken(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_api_token', [], $extra);
    }

    /**
     * Return Sitejet preview URL.
     *
     * This function returns a Sitejet website's preview URL.
     *
     * @param  int  $websiteId  The Sitejet website ID for the domain.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/sitejet-get_preview_url
     */
    public function getPreviewUrl(
        int $websiteId,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_preview_url', [
            'websiteId' => $websiteId,
        ], $extra);
    }

    /**
     * Return Sitejet SSO URL.
     *
     * This function returns a Sitejet website's SSO URL.
     *
     * @param  string  $domain  The cPanel account's Sitejet domain.
     * @param  string  $referrer  The cPanel interface referral URL.
     * @param  string|null  $uiMode  Specifies which Sitejet SaaS user interface mode the user will be redirected to.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/sitejet-get_sso_link
     */
    public function getSsoLink(
        string $domain,
        string $referrer,
        ?string $uiMode = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_sso_link', [
            'domain' => $domain,
            'referrer' => $referrer,
            'ui_mode' => $uiMode,
        ], $extra);
    }

    /**
     * Return Sitejet templates.
     *
     * This function fetches the list of available Sitejet templates.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @deprecated cPanel has deprecated this function.
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/sitejet-get_templates
     */
    public function getTemplates(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_templates', [], $extra);
    }

    /**
     * Check whether a Sitejet publish is running.
     *
     * This function reports whether a Sitejet publish is currently running for a domain, and under which
     * process ID.
     *
     * @param  string  $domain  The domain for the Sitejet website.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/sitejet-is_publish_in_progress
     */
    public function isPublishInProgress(
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('is_publish_in_progress', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Restore a domain from the restore point.
     *
     * This function reverts a document root to the restore point.
     *
     * @param  string  $domain  A cPanel account's domain.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/sitejet-restore_document_root
     */
    public function restoreDocumentRoot(
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('restore_document_root', [
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Update Sitejet template.
     *
     * This function sets a Sitejet website's template.
     *
     * @param  string  $domain  A cPanel account's domain.
     * @param  string  $templateId  The Sitejet template's ID.
     * @param  string  $templateName  The Sitejet template name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @deprecated cPanel has deprecated this function.
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/sitejet-set_template
     */
    public function setTemplate(
        string $domain,
        string $templateId,
        string $templateName,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_template', [
            'domain' => $domain,
            'templateId' => $templateId,
            'templateName' => $templateName,
        ], $extra);
    }

    /**
     * Publish Sitejet domain.
     *
     * This function publishes a domain's Sitejet website.
     *
     * @param  string  $domain  The domain for the Sitejet website.
     * @param  int|null  $cleanup  Whether to cleanup the domain's `document_root` directory during the publication process.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/sitejet/sitejet-start_publish
     */
    public function startPublish(
        string $domain,
        ?int $cleanup = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('start_publish', [
            'domain' => $domain,
            'cleanup' => $cleanup,
        ], $extra);
    }
}
