<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI SubDomain module (6 functions), run as one cPanel account through WHM.
 */
final class SubDomain extends UapiModule
{
    public const string MODULE = 'SubDomain';

    /**
     * Create subdomain.
     *
     * This function creates a subdomain.
     *
     * @param  string  $domain  The subdomain name to create.
     * @param  string  $rootdomain  The domain on which to create the new subdomain.
     * @param  bool|int|null  $canoff  Whether to use a canonical name (CNAME) in the Apache configuration for self-referential URLs.
     * @param  string|null  $dir  The subdomain's document `root` within the home directory, given as a valid directory path relative to the user's home directory.
     * @param  bool|int|null  $disallowdot  Whether to remove the dot (`.`) characters from the `domain` value.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/subdomain/subdomain-addsubdomain
     */
    public function addsubdomain(
        string $domain,
        string $rootdomain,
        bool|int|null $canoff = null,
        ?string $dir = null,
        bool|int|null $disallowdot = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('addsubdomain', [
            'domain' => $domain,
            'rootdomain' => $rootdomain,
            'canoff' => $canoff,
            'dir' => $dir,
            'disallowdot' => $disallowdot,
        ], $extra);
    }

    /**
     * Change a subdomain or addon domain document root.
     *
     * This function changes the document root for a subdomain or addon domain that the calling cPanel user
     * owns.
     *
     * @param  string  $docroot  The new document root as a path relative to the user's home directory.
     * @param  string  $domain  The full domain name of the subdomain or addon domain whose document root you want to change.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/subdomains/subdomain-changedocroot
     */
    public function changedocroot(
        string $docroot,
        string $domain,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('changedocroot', [
            'docroot' => $docroot,
            'domain' => $domain,
        ], $extra);
    }

    /**
     * Remove a subdomain.
     *
     * This function removes a subdomain from the cPanel account.
     *
     * @param  string  $domain  The subdomain to remove.
     * @param  bool|int|null  $disallowdot  Whether to remove the dot (`.`) characters from the subdomain label in the `domain` value.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/subdomain/subdomain-delsubdomain
     */
    public function delsubdomain(
        string $domain,
        bool|int|null $disallowdot = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('delsubdomain', [
            'domain' => $domain,
            'disallowdot' => $disallowdot,
        ], $extra);
    }

    /**
     * List the reserved subdomain names.
     *
     * This function lists the subdomain labels that the system reserves, and that an account therefore
     * cannot use to create a subdomain.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/subdomain/subdomain-getreservedsubdomains
     */
    public function getreservedsubdomains(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('getreservedsubdomains', [], $extra);
    }

    /**
     * List the subdomains.
     *
     * This function lists the subdomains on the cPanel account, including the subdomains that the
     * account's addon domains are parked on.
     *
     * @param  string|null  $regex  A Perl regular expression.
     * @param  bool|int|null  $returnHttpsRedirectStatus  Whether to include the `can_https_redirect` and `is_https_redirecting` fields in each entry.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/subdomain/subdomain-listsubdomains
     */
    public function listsubdomains(
        ?string $regex = null,
        bool|int|null $returnHttpsRedirectStatus = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('listsubdomains', [
            'regex' => $regex,
            'return_https_redirect_status' => $returnHttpsRedirectStatus,
        ], $extra);
    }

    /**
     * Return the subdomain validation pattern.
     *
     * This function retrieves the regular expression that the system uses to validate a subdomain label.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/subdomain/subdomain-validregex
     */
    public function validregex(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('validregex', [], $extra);
    }
}
