<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI Themes module (3 functions), run as one cPanel account through WHM.
 */
final class Themes extends UapiModule
{
    public const string MODULE = 'Themes';

    /**
     * Return current theme.
     *
     * This function is deprecated and does not return useful output.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @deprecated cPanel has deprecated this function.
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/themes/themes-get_theme_base
     */
    public function getThemeBase(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_theme_base', [], $extra);
    }

    /**
     * Return available themes.
     *
     * This function lists available themes.
     *
     * @param  bool|int|null  $showMailThemes  Whether to list the account's mail themes.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/themes/themes-list
     */
    public function list(
        bool|int|null $showMailThemes = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list', [
            'show_mail_themes' => $showMailThemes,
        ], $extra);
    }

    /**
     * Update current theme.
     *
     * This function applies a new theme to the cPanel interface.
     *
     * @param  string  $theme  The theme name.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/themes/themes-update
     */
    public function update(
        string $theme,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('update', [
            'theme' => $theme,
        ], $extra);
    }
}
