<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI Trash module (2 functions), run as one cPanel account through WHM.
 */
final class Trash extends UapiModule
{
    public const string MODULE = 'Trash';

    /**
     * Delete item from Trash.
     *
     * This function permanently deletes a single item from the `.trash` directory in the current cPanel
     * account's home directory.
     *
     * @param  string  $path  The path of the item to permanently delete.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/trash/trash-remove
     */
    public function remove(
        string $path,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('remove', [
            'path' => $path,
        ], $extra);
    }

    /**
     * Report the disk space used by the trash directory.
     *
     * Report the current apparent size of the trash directory's contents. Returns whether the trash
     * exists, the total apparent bytes calculated by summing each entry's lstat size, and the number of
     * items in the trash. Excludes the root-level .trash_restore bookkeeping file.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/trash/trash-usage
     */
    public function usage(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('usage', [], $extra);
    }
}
