<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;
use SensitiveParameter;

/**
 * UAPI TwoFactorAuth module (5 functions), run as one cPanel account through WHM.
 */
final class TwoFactorAuth extends UapiModule
{
    public const string MODULE = 'TwoFactorAuth';

    /**
     * Create 2FA authentication code.
     *
     * This function generates an authentication code to enable configuration of two-factor authentication.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/twofactorauth/twofactorauth-generate_user_configuration
     */
    public function generateUserConfiguration(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('generate_user_configuration', [], $extra);
    }

    /**
     * Return team user 2FA config.
     *
     * This function retrieves a team user's configuration settings for two-factor authentication.
     *
     * @param  string  $teamUser  The team user's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/twofactorauth/twofactorauth-get_team_user_configuration
     */
    public function getTeamUserConfiguration(
        string $teamUser,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_team_user_configuration', [
            'team_user' => $teamUser,
        ], $extra);
    }

    /**
     * Return cPanel account 2FA config.
     *
     * This function retrieves the cPanel account user's configuration settings for two-factor
     * authentication.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/twofactorauth/twofactorauth-get_user_configuration
     */
    public function getUserConfiguration(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_user_configuration', [], $extra);
    }

    /**
     * Remove 2FA config.
     *
     * This function removes the user from the two-factor authentication `userdata` file.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/twofactorauth/twofactorauth-remove_user_configuration
     */
    public function removeUserConfiguration(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('remove_user_configuration', [], $extra);
    }

    /**
     * Save 2FA config.
     *
     * This function configures the two-factor authentication settings for an account.
     *
     * @param  string  $secret  The 16-character string that UAPI's `TwoFactorAuth::generate_user_configuration` function generates.
     * @param  int  $tfaToken  The six-digit security code that the time-based one-time password (TOTP) authentication app generates.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/twofactorauth/twofactorauth-set_user_configuration
     */
    public function setUserConfiguration(
        #[SensitiveParameter] string $secret,
        #[SensitiveParameter] int $tfaToken,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_user_configuration', [
            'secret' => $secret,
            'tfa_token' => $tfaToken,
        ], $extra);
    }
}
