<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI VersionControlDeployment module (3 functions), run as one cPanel account through WHM.
 */
final class VersionControlDeployment extends UapiModule
{
    public const string MODULE = 'VersionControlDeployment';

    /**
     * Create Git deployment task.
     *
     * This function deploys the changes from a cPanel-managed repository.
     *
     * @param  string  $repositoryRoot  The repository's directory.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/versioncontroldeployment/versioncontroldeployment-create
     */
    public function create(
        string $repositoryRoot,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('create', [
            'repository_root' => $repositoryRoot,
        ], $extra);
    }

    /**
     * Delete Git deployment task.
     *
     * This function deletes a deployment task. For more information, read our Guide to Git - Deployment
     * documentation.
     *
     * @param  string  $deployId  The Task Queue system's task ID number.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/versioncontroldeployment/versioncontroldeployment-delete
     */
    public function delete(
        string $deployId,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('delete', [
            'deploy_id' => $deployId,
        ], $extra);
    }

    /**
     * Return Git deployment task status.
     *
     * This function retrieves the status of deployment tasks. Before deployment, repositories must meet
     * the following requirements: * A valid checked-in `.cpanel.yml` file in the top-level directory. *
     * One or more local or remote branches. * A clean working tree.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/versioncontroldeployment/versioncontroldeployment-retrieve
     */
    public function retrieve(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('retrieve', [], $extra);
    }
}
