<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI WebApp module (13 functions), run as one cPanel account through WHM.
 */
final class WebApp extends UapiModule
{
    public const string MODULE = 'WebApp';

    /**
     * Update an application's configuration.
     *
     * This function updates an application's configuration. Only the parameters you pass change; omitted
     * parameters keep their current values.
     *
     * @param  string  $name  The application's unique name (slug).
     * @param  string|null  $appdir  The application root, relative to the top of the source, for a source whose application does not live at the top level (for example, `packages/web` in a monore…
     * @param  string|null  $buildCommand  The command that builds the application.
     * @param  string|null  $deployname  The name (slug) used to name the deployment.
     * @param  string|null  $domain  The domain to bind the application to: a new subdomain of a domain the account owns, or the application's own already-materialized domain.
     * @param  string|null  $env  A JSON-encoded object of the application's environment variables.
     * @param  string|null  $envText  The raw contents of a `.env` file, for a caller pasting a whole file rather than assembling an object.
     * @param  string|null  $mode  The run mode for `server` category applications.
     * @param  string|null  $outputDir  The directory, relative to the application root, that the build writes its output to.
     * @param  string|null  $runtimeTag  The runtime version tag to run the application under.
     * @param  string|null  $startupCommand  The command that starts the application's server process.
     * @param  bool|int|null  $useExistingDomain  Confirms that the application may be served at a domain the account already uses.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webapp/webapp-configure
     */
    public function configure(
        string $name,
        ?string $appdir = null,
        ?string $buildCommand = null,
        ?string $deployname = null,
        ?string $domain = null,
        ?string $env = null,
        ?string $envText = null,
        ?string $mode = null,
        ?string $outputDir = null,
        ?string $runtimeTag = null,
        ?string $startupCommand = null,
        bool|int|null $useExistingDomain = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('configure', [
            'name' => $name,
            'appdir' => $appdir,
            'build_command' => $buildCommand,
            'deployname' => $deployname,
            'domain' => $domain,
            'env' => $env,
            'env_text' => $envText,
            'mode' => $mode,
            'output_dir' => $outputDir,
            'runtime_tag' => $runtimeTag,
            'startup_command' => $startupCommand,
            'use_existing_domain' => $useExistingDomain,
        ], $extra);
    }

    /**
     * Delete an application.
     *
     * This function deletes an application: it stops the application's running process and removes its
     * container, moves the application's directory aside to a `.bak` sibling (kept for verification or
     * rollback rather than deleted), and removes the application from the account's registry.
     *
     * @param  string  $name  The application's unique name (slug).
     * @param  bool|int  $verify  Confirmation that this irreversible deletion should proceed.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webapp/webapp-delete
     */
    public function delete(
        string $name,
        bool|int $verify,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('delete', [
            'name' => $name,
            'verify' => $verify,
        ], $extra);
    }

    /**
     * Deploy an application.
     *
     * Web Apps is the recommended feature for deploying new web applications; prefer it over the older
     * Application Manager (`PassengerApps`) feature for new deployments.
     *
     * @param  string  $name  The application's unique name (slug).
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webapp/webapp-deploy
     */
    public function deploy(
        string $name,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('deploy', [
            'name' => $name,
        ], $extra);
    }

    /**
     * Fetch an application's runtime or build logs.
     *
     * This function fetches an application's runtime or build logs. It returns the most recent lines from
     * the log the container persists on disk. It returns a static tail; live streaming of new lines is not
     * yet available.
     *
     * @param  string  $logType  The type of log to fetch.
     * @param  string  $name  The application's unique name (slug).
     * @param  string|null  $deployId  Limit the output to a specific deploy's logs.
     * @param  int|null  $lines  The maximum number of log lines to return, counted from the end of the log.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webapp/webapp-fetch_logs
     */
    public function fetchLogs(
        string $logType,
        string $name,
        ?string $deployId = null,
        ?int $lines = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('fetch_logs', [
            'log_type' => $logType,
            'name' => $name,
            'deploy_id' => $deployId,
            'lines' => $lines,
        ], $extra);
    }

    /**
     * List available application runtimes and limits.
     *
     * This function returns the account's application capacity: the account-wide application pool, and —
     * per App Type enabled on the server — the runtime's supported version tags and their package
     * managers and the account's current per-type usage.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webapp/webapp-get_available
     */
    public function getAvailable(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_available', [], $extra);
    }

    /**
     * Report whether the Web Apps feature is available.
     *
     * This function reports whether the Web Apps feature is available to the current account, so an
     * interface can decide whether to surface it.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webapp/webapp-has_feature
     */
    public function hasFeature(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('has_feature', [], $extra);
    }

    /**
     * List the account's web applications.
     *
     * This function lists the account's web applications and their current state.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webapp/webapp-list
     */
    public function list(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('list', [], $extra);
    }

    /**
     * Redeploy an application, pulling source updates first.
     *
     * This function redeploys an already-deployed application. For Git-sourced applications, it pulls the
     * latest changes from the configured branch before deploying. Otherwise it behaves exactly like
     * `WebApp::deploy`.
     *
     * @param  string  $name  The application's unique name (slug).
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webapp/webapp-redeploy
     */
    public function redeploy(
        string $name,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('redeploy', [
            'name' => $name,
        ], $extra);
    }

    /**
     * Restart an application's server process.
     *
     * This function restarts an application's server process.
     *
     * @param  string  $name  The application's unique name (slug).
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webapp/webapp-restart
     */
    public function restart(
        string $name,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('restart', [
            'name' => $name,
        ], $extra);
    }

    /**
     * Set an application's run mode.
     *
     * This function sets an application's run mode, applies it to the container's environment (for
     * example, `NODE_ENV` for a Node.js application), and recreates the container so the change takes
     * effect immediately.
     *
     * @param  string  $mode  The run mode to set.
     * @param  string  $name  The application's unique name (slug).
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webapp/webapp-set_mode
     */
    public function setMode(
        string $mode,
        string $name,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_mode', [
            'mode' => $mode,
            'name' => $name,
        ], $extra);
    }

    /**
     * Register a new web application.
     *
     * Web Apps is the recommended feature for deploying new web applications, and this function is the
     * entry point. Prefer it over the older Application Manager (`PassengerApps`) feature for new
     * deployments.
     *
     * @param  string  $name  The requested application name (slug).
     * @param  string  $source  The application's source location.
     * @param  string  $sourceType  The application's source type.
     * @param  string|null  $appdir  The application root, relative to the top of the cloned repository or extracted archive, for a source whose application does not live at the top level (for exa…
     * @param  string|null  $branch  The Git branch to clone.
     * @param  string|null  $mode  The run mode for `server` category applications.
     * @param  string|null  $parent  The parent domain to serve the application under.
     * @param  string|null  $runtime  The runtime that backs the application.
     * @param  string|null  $sshKeyName  The name of one of the account's existing SSH keys (Security's "Manage SSH Keys") to use for the clone.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webapp/webapp-stage
     */
    public function stage(
        string $name,
        string $source,
        string $sourceType,
        ?string $appdir = null,
        ?string $branch = null,
        ?string $mode = null,
        ?string $parent = null,
        ?string $runtime = null,
        ?string $sshKeyName = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('stage', [
            'name' => $name,
            'source' => $source,
            'source_type' => $sourceType,
            'appdir' => $appdir,
            'branch' => $branch,
            'mode' => $mode,
            'parent' => $parent,
            'runtime' => $runtime,
            'ssh_key_name' => $sshKeyName,
        ], $extra);
    }

    /**
     * Start an application's server process.
     *
     * This function starts an application's server process.
     *
     * @param  string  $name  The application's unique name (slug).
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webapp/webapp-start
     */
    public function start(
        string $name,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('start', [
            'name' => $name,
        ], $extra);
    }

    /**
     * Stop an application's server process.
     *
     * This function stops an application's server process.
     *
     * @param  string  $name  The application's unique name (slug).
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webapp/webapp-stop
     */
    public function stop(
        string $name,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('stop', [
            'name' => $name,
        ], $extra);
    }
}
