<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI WebDisk module (4 functions), run as one cPanel account through WHM.
 */
final class WebDisk extends UapiModule
{
    public const string MODULE = 'WebDisk';

    /**
     * Delete Web Disk account.
     *
     * This function deletes a Web Disk account.
     *
     * @param  bool|int  $destroy  Whether to recursively delete the Web Disk account's folder and all of its contents.
     * @param  string  $user  The Web Disk account username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webdisk/webdisk-delete_user
     */
    public function deleteUser(
        bool|int $destroy,
        string $user,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('delete_user', [
            'destroy' => $destroy,
            'user' => $user,
        ], $extra);
    }

    /**
     * Update Web Disk home directory location.
     *
     * This function changes the home directory for a Web Disk account.
     *
     * @param  string  $homedir  The Web Disk account's home directory.
     * @param  string  $user  The Web Disk account username.
     * @param  bool|int|null  $private  Whether to set the Web Disk directory's permissions to public or private.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webdisk/webdisk-set_homedir
     */
    public function setHomedir(
        string $homedir,
        string $user,
        bool|int|null $private = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_homedir', [
            'homedir' => $homedir,
            'user' => $user,
            'private' => $private,
        ], $extra);
    }

    /**
     * Update Web Disk account password.
     *
     * This function changes the Web Disk account's password.
     *
     * @param  string  $password  The Web Disk account's password.
     * @param  string  $user  The Web Disk account username.
     * @param  bool|int|null  $enabledigest  Whether to enable Digest Authentication.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webdisk/webdisk-set_password
     */
    public function setPassword(
        string $password,
        string $user,
        bool|int|null $enabledigest = null,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_password', [
            'password' => $password,
            'user' => $user,
            'enabledigest' => $enabledigest,
        ], $extra);
    }

    /**
     * Update Web Disk home directory permissions.
     *
     * This function changes the Web Disk home directory's permissions.
     *
     * @param  string  $perms  The Web Disk account's home directory file permissions.
     * @param  string  $user  The Web Disk account's username.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/webdisk/webdisk-set_permissions
     */
    public function setPermissions(
        string $perms,
        string $user,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('set_permissions', [
            'perms' => $perms,
            'user' => $user,
        ], $extra);
    }
}
