<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI WordPressBackup module (6 functions), run as one cPanel account through WHM.
 */
final class WordPressBackup extends UapiModule
{
    public const string MODULE = 'WordPressBackup';

    /**
     * Return all WordPress sites' backup status.
     *
     * This function checks for any active WordPress site backups on the cPanel account.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/wordpressbackup/wordpressbackup-any_running
     */
    public function anyRunning(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('any_running', [], $extra);
    }

    /**
     * Stop WordPress site backup.
     *
     * This function cancels a WordPress site backup.
     *
     * @param  mixed  $site  The WordPress site's URL without the protocol prefix.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/wordpressbackup/wordpressbackup-cancel
     */
    public function cancel(
        mixed $site,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('cancel', [
            'site' => $site,
        ], $extra);
    }

    /**
     * Delete WordPress backup temporary files.
     *
     * This function releases any system resources from a previous WordPress site backup.
     *
     * @param  string  $site  The WordPress site's URL without the protocol prefix.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/wordpressbackup/wordpressbackup-cleanup
     */
    public function cleanup(
        string $site,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('cleanup', [
            'site' => $site,
        ], $extra);
    }

    /**
     * Return WordPress site backups.
     *
     * This function retrieves a list of available WordPress site backups of a single site.
     *
     * @param  string  $site  The WordPress site's URL without the protocol prefix.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/wordpressbackup/wordpressbackup-get_available_backups
     */
    public function getAvailableBackups(
        string $site,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('get_available_backups', [
            'site' => $site,
        ], $extra);
    }

    /**
     * Return WordPress site backup status.
     *
     * This function checks for an active WordPress site backup.
     *
     * @param  string  $site  The WordPress site's URL without `http://`.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/wordpressbackup/wordpressbackup-is_running
     */
    public function isRunning(
        string $site,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('is_running', [
            'site' => $site,
        ], $extra);
    }

    /**
     * Backup WordPress site.
     *
     * This function starts a single WordPress site backup.
     *
     * @param  mixed  $site  The WordPress site's URL without the protocol prefix.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/wordpressbackup/wordpressbackup-start
     */
    public function start(
        mixed $site,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('start', [
            'site' => $site,
        ], $extra);
    }
}
