<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI WordPressRestore module (3 functions), run as one cPanel account through WHM.
 */
final class WordPressRestore extends UapiModule
{
    public const string MODULE = 'WordPressRestore';

    /**
     * Return WordPress site restore status.
     *
     * This function returns whether a WordPress site backup restoration is in progress.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/wordpressrestore/wordpressrestore-any_running
     */
    public function anyRunning(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('any_running', [], $extra);
    }

    /**
     * Delete restored WordPress site's temporary files.
     *
     * This function cleans up any temporary system resources after a WordPress site backup restoration.
     *
     * @param  string  $site  The WordPress site's URL without the protocol prefix.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/wordpressrestore/wordpressrestore-cleanup
     */
    public function cleanup(
        string $site,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('cleanup', [
            'site' => $site,
        ], $extra);
    }

    /**
     * Restore WordPress site.
     *
     * This function starts a single WordPress site backup restoration.
     *
     * @param  string  $backupPath  The file path to the backup archive.
     * @param  string  $site  The WordPress site's URL to restore.
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/wordpressrestore/wordpressrestore-start
     */
    public function start(
        string $backupPath,
        string $site,
        array $extra = [],
    ): UapiResult {
        return $this->invoke('start', [
            'backup_path' => $backupPath,
            'site' => $site,
        ], $extra);
    }
}
