<?php

declare(strict_types=1);

// Generated by bin/generate from cPanel's OpenAPI spec. Do not edit; run composer generate. Spec 11.138.0.10.

namespace Itxshakil\CpanelWhm\Api\Uapi;

use Itxshakil\CpanelWhm\Api\UapiModule;
use Itxshakil\CpanelWhm\Data\UapiResult;
use Itxshakil\CpanelWhm\Exceptions\UapiCallFailed;
use Itxshakil\CpanelWhm\Exceptions\WhmException;

/**
 * UAPI WordPressSite module (2 functions), run as one cPanel account through WHM.
 */
final class WordPressSite extends UapiModule
{
    public const string MODULE = 'WordPressSite';

    /**
     * Install WordPress site.
     *
     * This function installs a WordPress site for cPanel user's primary domain.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/wordpresssite/wordpresssite-create
     */
    public function create(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('create', [], $extra);
    }

    /**
     * Return WordPress site information.
     *
     * This function retrieves the installation status and detailed information of the WordPress site for
     * cPanel user's primary domain.
     *
     * @param  array<string, mixed>  $extra  Further parameters, sent as given.
     *
     * @throws UapiCallFailed
     * @throws WhmException
     *
     * @see https://api.docs.cpanel.net/specifications/cpanel.openapi/wordpresssite/wordpresssite-retrieve
     */
    public function retrieve(
        array $extra = [],
    ): UapiResult {
        return $this->invoke('retrieve', [], $extra);
    }
}
